// Native browser smoke test. No npm dependencies.
const {qaDirectory,screenshotOptions}=require('./qa_artifacts.cjs');
const assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {spawn}=require('node:child_process');
const root=process.env.TULDOK_SOURCE_ROOT||path.resolve(__dirname,'..'),temporary=fs.mkdtempSync(path.join(os.tmpdir(),'tuldok-text-classification-proposals-browser-')),children=[];
let ws, inspect;
const extraSockets=[];
const errors=[];
const {pageLoadTracker}=require('./browser_page_load.cjs');const pageLoads=pageLoadTracker();
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function until(fn){for(let i=0;i<150;i++){const value=await fn();if(value)return value;await pause(100);}throw Error('Timed out');}
function launch(command,args,options={}){const child=spawn(command,args,options);children.push(child);return child;}
(async()=>{
  const report=qaDirectory(root,'pumas-typed');
  console.log('Typed Pumas evidence: '+report);
  const server=launch('python3',['-u','tests/browser_pumas_typed_server.py','--port','0','--data',path.join(temporary,'data')],{cwd:root,stdio:['ignore','pipe','pipe']});
  let output='',stderr='';server.stdout.on('data',data=>output+=data);server.stderr.on('data',data=>stderr+=data);
  const port=await until(()=>output.match(/Tuldok: http:\/\/127\.0\.0\.1:(\d+)/)?.[1]);
  launch(process.env.BROWSER||'/usr/bin/chromium',['--headless','--no-sandbox','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--window-size=1400,950','--user-data-dir='+path.join(temporary,'browser'),'about:blank'],{stdio:['ignore','ignore','inherit'],env:{...process.env,HOME:temporary,XDG_CONFIG_HOME:temporary,XDG_CACHE_HOME:temporary}});
  const active=path.join(temporary,'browser','DevToolsActivePort');
  const debugPort=await until(()=>fs.existsSync(active)&&fs.readFileSync(active,'utf8').split('\n')[0]);
  const tabs=await(await fetch('http://127.0.0.1:'+debugPort+'/json')).json();
  const target=tabs.find(tab=>tab.type==='page' && tab.url==='about:blank');
  assert.ok(target,'Expected the explicitly launched blank page target');
  ws=new WebSocket(target.webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
  let id=0;const pending=new Map();
  ws.onmessage=event=>{const message=JSON.parse(event.data);pageLoads.observe(message);if(message.id){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(message.error):task.resolve(message.result);}if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails);};
  const send=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));return result.result.value;};
  inspect=()=>evaluate('JSON.stringify({url:location.href,ready:document.readyState,notice:document.getElementById("notice")?.textContent,classificationStatus:document.getElementById("text-classification-proposal-status")?.textContent,classificationModels:document.getElementById("text-classification-proposal-model")?.options.length,scriptType:typeof refreshTextClassificationProposals,body:document.body?.innerText.slice(0,1500),viewport:innerWidth,documentWidth:document.documentElement.scrollWidth,overflow:[...document.querySelectorAll("body *")].filter(e=>e.getBoundingClientRect().right>innerWidth || e.scrollWidth>e.clientWidth+1).map(e=>({tag:e.tagName,id:e.id,class:e.className,right:e.getBoundingClientRect().right,width:e.getBoundingClientRect().width})).slice(0,30)})');
  const click=id=>evaluate('document.getElementById('+JSON.stringify(id)+').click()');
  const fill=(id,value)=>evaluate('(()=>{const e=document.getElementById('+JSON.stringify(id)+');e.value='+JSON.stringify(value)+';e.dispatchEvent(new Event("input",{bubbles:true}));e.dispatchEvent(new Event("change",{bubbles:true}));})()');
  const base='http://127.0.0.1:'+port,ref=row=>({id:row.id,revision:row.revision,source_revision:row.source_revision});
  const request=async(path,body)=>{const r=await fetch(base+'/api/workbench/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();assert.ok(r.ok,JSON.stringify(data));return data;};
  const makeText=async(name,text)=>request('import',{kind:'text',name,text,groups:[name],rights:'Authored synthetic fixture'});

  const gateway=output.match(/TYPED_GATEWAY=(.+)/)[1],origin=output.match(/TYPED_ORIGIN=(.+)/)[1];
  const source=await makeText('Typed source','The meeting is confirmed.');
  const fixed=await request('selections',{name:'Typed fixed set',items:[ref(source)]});
  await send('Page.enable');await send('Runtime.enable');await send('Page.setLifecycleEventsEnabled',{enabled:true});
  await send('Page.navigate',{url:base+'/workbench'});await until(()=>evaluate('document.getElementById("notice")?.textContent === "Collection ready."'));
  await evaluate('refreshSavedSets('+JSON.stringify(fixed.id)+')');await click('load-selection');await until(()=>evaluate('!savedLoadBusy && selected.size===1'));
  const selectedBefore=await evaluate('releaseBody().items');
  await evaluate('openRecord('+JSON.stringify(source.id)+')');
  const prefix='text-classification-proposal-';
  await evaluate('document.getElementById("text-classification-proposal-panel").open=true');
  await fill(prefix+'protocol','pumas_typed_v1');await fill(prefix+'url',gateway);await click(prefix+'models');
  await until(()=>evaluate('document.getElementById("text-classification-proposal-model").options.length===2'));
  await fill(prefix+'model','controlled-text');await fill(prefix+'labels','["positive","negative"]');
  assert.equal(await evaluate('document.getElementById("text-classification-proposal-seed").disabled'),true);
  await click(prefix+'capabilities');await until(()=>evaluate('document.getElementById("text-classification-proposal-capability-metadata").textContent.includes("observed_sha256")'));
  const manifest=JSON.parse(await evaluate('document.getElementById("text-classification-proposal-capability-metadata").textContent'));
  assert.equal(manifest.capabilities.model,'controlled-text');assert.equal(manifest.capabilities.profile,'controlled-text-cpu');
  // A held observation must not restore stale metadata after a same-value edit.
  await evaluate('window.nativeTypedFetch=fetch;window.heldTypedRelease=null;window.fetch=async(...args)=>{const r=await nativeTypedFetch(...args);if(args[0]==="/api/generation/typed-capabilities")await new Promise(resolve=>heldTypedRelease=resolve);return r;};');
  await click(prefix+'capabilities');await until(()=>evaluate('!!heldTypedRelease'));
  await fill(prefix+'profile','');await evaluate('heldTypedRelease();window.fetch=nativeTypedFetch');await pause(100);
  assert.equal(await evaluate('document.getElementById("text-classification-proposal-capability-metadata").hidden'),true);
  await evaluate('window.typedAdmissionFetch=fetch;window.typedHeldAdmission=false;window.fetch=async(...args)=>{if(args[0]==="/api/workbench/text-classification-proposals"&&args[1]?.method==="POST"){typedHeldAdmission=true;await new Promise(()=>{});}return typedAdmissionFetch(...args);};');
  await click(prefix+'submit');await until(()=>evaluate('typedHeldAdmission'));const pendingBody=await evaluate('textClassificationProposalPendingRequest');
  assert.equal(pendingBody.protocol,'pumas_typed_v1');assert.equal(pendingBody.seed,null);assert.equal(pendingBody.profile,null);
  const reloadFrame= (await send('Page.getFrameTree')).frameTree.frame;await send('Page.reload');await until(()=>pageLoads.reloaded(reloadFrame));await until(()=>evaluate('document.getElementById("notice")?.textContent === "Collection ready."'));
  await click(prefix+'restore');await click(prefix+'open-pending');await until(()=>evaluate('current?.id==='+JSON.stringify(source.id)));
  assert.equal(await evaluate('document.getElementById("text-classification-proposal-protocol").value'),'pumas_typed_v1');
  assert.equal(await evaluate('document.getElementById("text-classification-proposal-seed").disabled'),true);
  assert.deepEqual(await evaluate('textClassificationProposalPendingRequest'),pendingBody);
  // Restore of identical values invalidates a held capabilities reply even without input events.
  await evaluate('window.nativeTypedFetch=fetch;window.heldTypedRelease=null;window.fetch=async(...args)=>{const r=await nativeTypedFetch(...args);if(args[0]==="/api/generation/typed-capabilities")await new Promise(resolve=>heldTypedRelease=resolve);return r;};');
  await click(prefix+'capabilities');await until(()=>evaluate('!!heldTypedRelease'));await click(prefix+'restore');
  await evaluate('heldTypedRelease();window.fetch=nativeTypedFetch');await pause(100);
  assert.equal(await evaluate('document.getElementById("text-classification-proposal-capability-metadata").hidden'),true);
  await click(prefix+'submit');await until(()=>evaluate('textClassificationProposalJobs.some(j=>j.status==="completed")'));
  await evaluate('refreshSavedSets('+JSON.stringify(fixed.id)+')');await click('load-selection');await until(()=>evaluate('!savedLoadBusy && selected.size===1'));

  const job=(await request('text-classification-proposals')).jobs.find(j=>j.status==='completed');
  assert.equal(job.config.protocol,'pumas_typed_v1');assert.equal(job.config.seed,null);assert.equal(job.canonical_request.profile,'controlled-text-cpu');
  assert.deepEqual(await evaluate('releaseBody().items'),selectedBefore);
  await evaluate('[...document.querySelectorAll("#text-classification-proposal-jobs button")].find(b=>b.textContent==="Apply as draft").click()');
  await until(async()=> (await request('records/'+source.id)).review==='draft' && (await request('records/'+source.id)).annotation?.label==='positive');
  assert.deepEqual(await evaluate('releaseBody().items'),selectedBefore);
  let row=await request('records/'+source.id);assert.equal(row.target_proposal.capability_observation.capabilities.profile,'controlled-text-cpu');
  const reviewed=await request('records/'+source.id,{revision:row.revision,source_revision:row.source_revision,task:'text_classification',annotation:row.annotation,groups:row.groups,review:'human_reviewed'});
  await evaluate('openRecord('+JSON.stringify(source.id)+')');
  await fetch(base+'/test/pumas-control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:JSON.stringify({candidates:[{text:'The confirmed meeting will take place.',label:'positive',evidence:[{start:0,end:25,quote:source.text}]}]})})});
  await fill('grounded-protocol','pumas_typed_v1');await fill('grounded-url',gateway);await click('grounded-models');await until(()=>evaluate('document.getElementById("grounded-model").options.length===2'));
  await fill('grounded-model','controlled-text');await fill('grounded-count','1');await fill('grounded-instruction','Rewrite clearly.');
  await evaluate('document.getElementById("grounded-form").requestSubmit()');
  const grounded=await until(async()=> (await request('grounded/jobs')).jobs.find(j=>j.status==='completed'));
  const admitted=await request('grounded/review/'+grounded.id,{revision:grounded.revision,candidate_id:grounded.candidates[0].id,decision:'admit_draft',note:'Controlled source checked; separate annotation review remains.'});
  assert.equal(admitted.record.review,'draft');assert.deepEqual(admitted.record.parents,[source.id]);assert.deepEqual(admitted.record.groups,source.groups);
  await evaluate('document.getElementById("text-classification-proposal-panel").open=true;document.getElementById("text-classification-proposal-panel").scrollIntoView({block:"start"})');
  const screenshot=await send('Page.captureScreenshot',screenshotOptions);fs.writeFileSync(path.join(report,'typed-text-review.jpg'),Buffer.from(screenshot.data,'base64'));
  await send('Page.navigate',{url:base+'/'});await until(()=>evaluate('typeof pumasTypedSettings === "function" && document.getElementById("generate")'));
  await click('generation-view');
  await fill('generation-protocol','pumas_typed_v1');await fill('generation-url',gateway);await click('generation-refresh');await until(()=>evaluate('document.getElementById("generation-model").options.length===2'));
  assert.ok(!await evaluate('document.getElementById("generation-status").textContent.includes("image models ready")'),'Typed alias listing must not claim image readiness');
  await fill('generation-model','controlled-image');await fill('generation-strategy','repeat');await fill('generation-count','1');await fill('generation-width','16');await fill('generation-height','12');await fill('generation-prompt','Literal blue fixture.');await fill('generation-seed','7');
  await click('generate');const batch=await until(async()=> (await(await fetch(base+'/api/generation/jobs')).json()).jobs.find(j=>j.status==='completed'));
  const snapshot=await(await fetch(base+'/api/generation/jobs')).json(),entry=snapshot.entries.find(e=>e.job_id===batch.id);
  assert.equal(entry.metadata.protocol,'pumas_typed_v1');assert.equal(entry.metadata.canonical_request.profile,'controlled-image-cpu');
  const imageReloadFrame=(await send('Page.getFrameTree')).frameTree.frame;await send('Page.reload');await until(()=>pageLoads.reloaded(imageReloadFrame));await until(()=>evaluate('document.getElementById("generation-protocol").value==="pumas_typed_v1"'));
  assert.equal(await evaluate('document.getElementById("generation-width").value'),'16');
  await click('generation-view');await click('generation-refresh');await until(()=>evaluate('document.getElementById("generation-model").options.length===2'));
  await fill('generation-model','controlled-image');await click('generation-capabilities');
  await until(()=>evaluate('document.getElementById("generation-capability-metadata").textContent.includes("observed_sha256")'));
  assert.ok(await evaluate('document.documentElement.scrollWidth<=innerWidth'),'Typed metadata must fit the image studio viewport');
  const imageShot=await send('Page.captureScreenshot',screenshotOptions);fs.writeFileSync(path.join(report,'typed-image-batch.jpg'),Buffer.from(imageShot.data,'base64'));
  fs.writeFileSync(path.join(report,'receipt.json'),JSON.stringify({origin,gateway,manifest,classification:job,grounded,admitted_record:admitted.record,batch,entry,errors},null,2));
  assert.deepEqual(errors,[]);console.log('Typed classification draft, fixed selections, exact profile, held capabilities, grounded family/review, text-to-PNG and settings restore passed: '+origin);
})().catch(async error=>{console.error(error);console.error('Runtime errors:',JSON.stringify(errors));if(inspect)try{console.error('Page diagnostics:',await inspect());}catch(diagnostic){console.error('Diagnostics failed:',diagnostic);}process.exitCode=1;}).finally(async()=>{if(ws)ws.close();for(const socket of extraSockets)socket.close();for(const child of children)child.kill();await pause(200);fs.rmSync(temporary,{recursive:true,force:true});});
