// Source-derived synthetic producer fixture; real loopback HTTP and Chromium.
'use strict';
const crypto=require('node:crypto');const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {spawn,spawnSync}=require('node:child_process');
const {pageLoadTracker}=require('./browser_page_load.cjs');
const {qaDirectory,screenshotOptions}=require('./qa_artifacts.cjs');
const root=path.resolve(process.env.TULDOK_SOURCE_ROOT||path.join(__dirname,'..')),report=qaDirectory(root,'producer-v2-synthetic');
const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'tuldok-sequence-browser-')),children=[];
const errors=[],tracker=pageLoadTracker(),pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
let ws;
async function until(fn){for(let i=0;i<150;i++){const result=await fn();if(result)return result;await pause(100);}throw Error('Timed out');}
function launch(command,args,options={}){const child=spawn(command,args,options);children.push(child);return child;}
(async()=>{
  const seeded=spawnSync('python3',['-c',"import sys; from pathlib import Path; sys.path.insert(0,'tests'); from fixtures.rheon_synthetic_v2 import fixture; p=Path(sys.argv[1]); run,frames,controls=fixture(); (p/'run.json').write_bytes(run); (p/'frames.jsonl').write_bytes(frames); (p/'controls.json').write_bytes(controls)",temporary],{cwd:root,encoding:'utf8'});
  assert.equal(seeded.status,0,seeded.stderr);
  const server=launch('python3',['-u','app.py','--port','0','--data',path.join(temporary,'data')],{cwd:root,stdio:['ignore','pipe','pipe']});
  let output='';server.stdout.on('data',chunk=>output+=chunk);
  const port=await until(()=>output.match(/127\.0\.0\.1:(\d+)/)?.[1]),base='http://127.0.0.1:'+port;
  const api=async(route,body)=>{const response=await fetch(base+'/api/workbench/'+route,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();assert.ok(response.ok,JSON.stringify(result));return result;};
  const seed=await api('import',{kind:'text',text:'Independent editor stays intact.',name:'Existing editor',groups:['existing-source'],rights:'Authored'});
  launch(process.env.BROWSER||'/usr/bin/chromium',['--headless','--no-sandbox','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--window-size=1400,950','--user-data-dir='+path.join(temporary,'browser'),'about:blank'],{stdio:['ignore','ignore','ignore'],env:{...process.env,XDG_CONFIG_HOME:temporary,XDG_CACHE_HOME:temporary}});
  const active=path.join(temporary,'browser','DevToolsActivePort'),debugPort=await until(()=>fs.existsSync(active)&&fs.readFileSync(active,'utf8').split('\n')[0]);
  const tabs=await(await fetch('http://127.0.0.1:'+debugPort+'/json')).json(),target=tabs.find(tab=>tab.type==='page'&&tab.url==='about:blank');
  assert.ok(target);ws=new WebSocket(target.webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
  let id=0;const pending=new Map();
  const send=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
  ws.onmessage=event=>{const message=JSON.parse(event.data);tracker.observe(message);if(message.id){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(message.error):task.resolve(message.result);}if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails);if(message.method==='Page.javascriptDialogOpening')send('Page.handleJavaScriptDialog',{accept:true}).catch(error=>errors.push(error));};
  const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));return result.result.value;};
  const fill=(id,value)=>evaluate(`(()=>{const e=document.getElementById(${JSON.stringify(id)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  const choose=(id,name,contents)=>evaluate(`(()=>{const raw=Uint8Array.from(atob(${JSON.stringify((contents||fs.readFileSync(path.join(temporary,name))).toString('base64'))}),c=>c.charCodeAt(0)),dt=new DataTransfer();dt.items.add(new File([raw],${JSON.stringify(name)}));document.getElementById(${JSON.stringify(id)}).files=dt.files;})()`);
  await send('Page.enable');await send('Page.setLifecycleEventsEnabled',{enabled:true});await send('Runtime.enable');
  const blank=(await send('Page.getFrameTree')).frameTree.frame;await send('Page.navigate',{url:base+'/workbench'});await until(()=>tracker.reloaded(blank));await until(()=>evaluate('document.getElementById("notice")?.textContent==="Collection ready."'));
  await evaluate('openRecord('+JSON.stringify(seed.id)+')');await fill('label','retain unsaved target');
  await evaluate('document.querySelector(".record input").click();document.getElementById("sequence-import-panel").open=true');
  await choose('sequence-run','run.json');await choose('sequence-frames','frames.jsonl');await choose('sequence-controls','controls.json');
  await fill('sequence-name','Synthetic source-derived trajectory');
  // Hold a real committed response, then verify a second submit issues no POST.
  await evaluate(`(()=>{const original=window.fetch;window.sequencePosts=0;window.holdSequence=true;window.fetch=async(...args)=>{if(String(args[0]).endsWith('/sequence-import')){window.sequencePosts++;const response=await original(...args);if(window.holdSequence){window.holdSequence=false;await new Promise(resolve=>window.releaseSequence=resolve);}return response;}return original(...args);};})()`);
  await evaluate('document.getElementById("sequence-import-form").requestSubmit()');await until(()=>evaluate('!!window.releaseSequence'));
  await evaluate('document.getElementById("sequence-import-form").requestSubmit()');assert.equal(await evaluate('sequencePosts'),1);
  assert.equal((await api('records?kind=sequence')).total,1);
  await evaluate('window.releaseSequence()');await until(()=>evaluate('!sequenceImportBusy'));
  assert.match(await evaluate('document.getElementById("sequence-import-status").textContent'),/9 frames, unreviewed/);
  assert.equal(await evaluate('current.id'),seed.id);assert.equal(await evaluate('dirty'),true);
  assert.equal(await evaluate('document.getElementById("label").value'),'retain unsaved target');assert.equal(await evaluate('selected.size'),1);
  const row=(await api('records?kind=sequence')).items[0];assert.equal(row.review,'draft');assert.equal(row.annotation,null);
  assert.equal(row.sequence.manifest.geometry.field_shapes.velocity_x[0],17);assert.equal(row.sequence.frame_index.length,9);
  // Wrong hash and wrong selected filename admit no second record.
  await choose('sequence-frames','frames.jsonl',Buffer.from('malformed\n'));
  await evaluate('document.getElementById("sequence-import-form").requestSubmit()');await until(()=>evaluate('!sequenceImportBusy'));
  assert.match(await evaluate('document.getElementById("sequence-import-status").textContent'),/byte count/);
  await choose('sequence-frames','wrong.jsonl',Buffer.from('malformed\n'));
  await evaluate('document.getElementById("sequence-import-form").requestSubmit()');await until(()=>evaluate('!sequenceImportBusy'));
  assert.match(await evaluate('document.getElementById("sequence-import-status").textContent'),/Choose frames.jsonl/);
  assert.equal((await api('records?kind=sequence')).total,1);
  await evaluate('dirty=false');await evaluate('openRecord('+JSON.stringify(row.id)+')');
  assert.equal(await evaluate('document.getElementById("task").value'),'sequence_transport');
  assert.equal(await evaluate('document.getElementById("sequence-inspection").hidden'),false);
  assert.match(await evaluate('document.getElementById("sequence-metadata").textContent'),/"pressure_semantics"/);
  assert.match(await evaluate('document.getElementById("sequence-metadata").textContent'),/synthetic/);
  await fill('sequence-probe-frame','0');await evaluate('document.getElementById("sequence-probe-read").click()');
  await until(()=>evaluate('document.getElementById("sequence-probe-status").textContent.includes("Declared producer-v2 controls validated")'));
  let probe=JSON.parse(await evaluate('document.getElementById("sequence-probe-output").textContent'));assert.equal(probe.accepted_interval,null);assert.equal(probe.interval_controls_emitted.selected_interval,null);
  await fill('sequence-probe-frame','8');await fill('sequence-probe-i','16');await fill('sequence-probe-j','7');await fill('sequence-probe-k','3');await evaluate('document.getElementById("sequence-probe-read").click()');
  await until(()=>evaluate('document.getElementById("sequence-probe-status").textContent.includes("Declared producer-v2 controls validated")'));
  probe=JSON.parse(await evaluate('document.getElementById("sequence-probe-output").textContent'));assert.equal(probe.interval_controls_emitted.selected_interval.start_frame,7);assert.equal(probe.interval_controls_emitted.scope,'producer_controls_validated');assert.deepEqual(probe.field.shape,[17,8,4]);assert.equal(probe.field.dtype,'f32');assert.equal(await evaluate('dirty'),false);
  await fill('sequence-note','Inspected MAC fields, accepted intervals and transport-only limits.');
  await fill('record-review','human_reviewed');await evaluate('document.getElementById("editor").requestSubmit()');
  await until(()=>evaluate('current.review==="human_reviewed"&&!dirty&&current.revision===2'));
  assert.equal((await api('history/'+row.id)).length,2);
  const asset=await fetch(base+'/api/workbench/asset/'+row.id);assert.equal(asset.headers.get('content-type'),'application/zip');
  const bundle=Buffer.from(await asset.arrayBuffer());fs.writeFileSync(path.join(temporary,'download.zip'),bundle);fs.writeFileSync(path.join(report,'synthetic-three-file-bundle.zip'),bundle);
  const fixtureProof={};for(const name of ['run.json','frames.jsonl','controls.json']){const raw=fs.readFileSync(path.join(temporary,name));fs.writeFileSync(path.join(report,'synthetic-'+name),raw);fixtureProof[name]={bytes:raw.length,sha256:sha(raw)};}
  const check=spawnSync('python3',['-c',"import sys,zipfile; from pathlib import Path; p=Path(sys.argv[1]); z=zipfile.ZipFile(p/'download.zip'); assert z.read('run.json')==(p/'run.json').read_bytes(); assert z.read('frames.jsonl')==(p/'frames.jsonl').read_bytes(); assert z.read('controls.json')==(p/'controls.json').read_bytes(); assert len(z.namelist())==3",temporary],{cwd:root,encoding:'utf8'});assert.equal(check.status,0,check.stderr);
  await evaluate('document.getElementById("clear-selection").click()');
  await evaluate('document.querySelector('+JSON.stringify('input[aria-label="Select '+row.name+'"]')+').click()');
  await fill('train',100);await fill('validation',0);await fill('test',0);
  await evaluate('document.getElementById("preview-release").click()');await until(()=>evaluate('!document.getElementById("freeze-release").disabled'));
  assert.match(await evaluate('document.getElementById("release-preview").textContent'),/transport-only/);
  await evaluate('document.getElementById("release-form").requestSubmit()');await until(()=>evaluate('!!document.querySelector("#release-result a")'));
  const frozenUrl=await evaluate('document.querySelector("#release-result a").href');const frozen=await fetch(frozenUrl);assert.equal(frozen.status,200);const frozenBytes=Buffer.from(await frozen.arrayBuffer());fs.writeFileSync(path.join(report,'synthetic-frozen-release.zip'),frozenBytes);
  const frozenCheck=spawnSync('python3',['-c',"import json,sys,zipfile;from pathlib import Path;p=Path(sys.argv[1]);z=zipfile.ZipFile(p/'synthetic-frozen-release.zip');m=json.loads(z.read('manifest.json'));assert len(m['records'])==1;assert z.read(m['records'][0]['asset'])==(p/'synthetic-three-file-bundle.zip').read_bytes()",report],{cwd:root,encoding:'utf8'});assert.equal(frozenCheck.status,0,frozenCheck.stderr);
  const previous=(await send('Page.getFrameTree')).frameTree.frame;await send('Page.reload',{ignoreCache:true});await until(()=>tracker.reloaded(previous));await until(()=>evaluate('document.getElementById("notice")?.textContent==="Collection ready."'));
  assert.equal((await api('records?kind=sequence')).total,1);
  await evaluate('openRecord('+JSON.stringify(row.id)+')');assert.equal(await evaluate('current.review'),'human_reviewed');assert.match(await evaluate('document.getElementById("sequence-download").textContent'),/controls.json/);
  const frozenAgain=Buffer.from(await(await fetch(frozenUrl)).arrayBuffer());assert.equal(sha(frozenAgain),sha(frozenBytes));
  await fill('sequence-probe-frame','8');await fill('sequence-probe-i','16');await fill('sequence-probe-j','7');await fill('sequence-probe-k','3');await evaluate('document.getElementById("sequence-probe-read").click()');await until(()=>evaluate('document.getElementById("sequence-probe-status").textContent.includes("Declared producer-v2 controls validated")'));const reopenedProbe=JSON.parse(await evaluate('document.getElementById("sequence-probe-output").textContent'));assert.deepEqual(reopenedProbe.interval_controls_emitted,probe.interval_controls_emitted);assert.deepEqual(reopenedProbe.field,probe.field);assert.deepEqual(reopenedProbe.accepted_interval,probe.accepted_interval);probe=reopenedProbe;
  await evaluate('document.getElementById("sequence-inspection").scrollIntoView()');
  fs.writeFileSync(path.join(report,'v2-desktop.jpg'),Buffer.from((await send('Page.captureScreenshot',screenshotOptions)).data,'base64'));
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});
  await evaluate('document.getElementById("sequence-inspection").scrollIntoView()');
  assert.ok(await evaluate('document.documentElement.scrollWidth<=innerWidth'),'Sequence metadata fits narrow viewport');
  fs.writeFileSync(path.join(report,'v2-narrow.jpg'),Buffer.from((await send('Page.captureScreenshot',screenshotOptions)).data,'base64'));
  assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(report,'session.json'),JSON.stringify({result:'PASS',fixture:'explicit synthetic source-derived producer-v2; no producer execution or authenticity',record:row.id,fixtureProof,bundle_sha256:sha(bundle),frozen_sha256:sha(frozenBytes),fresh_document_verified:tracker.reloaded(previous),files:['run.json','frames.jsonl','controls.json'],probe,errors},null,2));
  console.log('Synthetic producer-v2 Chromium: source-derived exact bundle import/download, bounded malformed controls, duplicate-submit gate, dirty editor/selection preservation, metadata/frame index, human review/history, whole-trajectory release, reload and narrow layout passed.');
})().catch(error=>{console.error(error);console.error('Runtime errors:',JSON.stringify(errors));process.exitCode=1;}).finally(async()=>{if(ws)ws.close();for(const child of children)child.kill();await pause(200);fs.rmSync(temporary,{recursive:true,force:true});});
