// Actual rendered point-file import/review/export and external reader; authored QA, no models.
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {spawn,execFileSync}=require('node:child_process'),{qaDirectory,screenshotOptions}=require('./qa_artifacts.cjs');
const {waitForDebugger}=require('./browser_startup.cjs'),{pageLoadTracker}=require('./browser_page_load.cjs');
const root=path.resolve(process.env.TULDOK_SOURCE_ROOT||path.join(__dirname,'..')),output=qaDirectory(root,'pointcloud-profile');
const scratch=fs.mkdtempSync(path.join(os.tmpdir(),'tuldok-pointcloud-ui-')),children=[],errors=[],network=new Map(),tracker=pageLoadTracker();
const python=process.env.POINTCLOUD_CONSUMER_PYTHON||process.env.INSTRUCTION_CONSUMER_PYTHON||'python3',sha=raw=>crypto.createHash('sha256').update(raw).digest('hex'),pause=ms=>new Promise(r=>setTimeout(r,ms));
let ws,stage='startup',owner='first';const downloads=[];
async function until(fn){for(let i=0;i<200;i++){if(await fn())return;await pause(75);}throw Error('Timed out: '+stage);}
function launch(cmd,args,opts){const child=spawn(cmd,args,opts);children.push(child);return child;}
async function start(folder,empty=false){fs.mkdirSync(folder,{recursive:true});const child=launch(python,['-u','app.py','--port','0','--data',path.join(folder,'data')],{cwd:root,stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',v=>stdout+=v);child.stderr.on('data',v=>stderr+=v);await until(()=>{if(child.exitCode!==null)throw Error(stderr);return /127\.0\.0\.1:(\d+)/.test(stdout);});return 'http://127.0.0.1:'+stdout.match(/127\.0\.0\.1:(\d+)/)[1];}
(async()=>{
 const base=await start(path.join(scratch,'first')),secondBase=await start(path.join(scratch,'second'),true);
 const browser=launch(process.env.BROWSER||'/usr/bin/chromium',['--headless','--no-sandbox','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--window-size=1400,950','--user-data-dir='+path.join(scratch,'browser'),'about:blank'],{stdio:['ignore','ignore','pipe'],env:{...process.env,XDG_CONFIG_HOME:scratch,XDG_CACHE_HOME:scratch}});
 const port=await waitForDebugger(browser,path.join(scratch,'browser','DevToolsActivePort')),tabs=await(await fetch('http://127.0.0.1:'+port+'/json')).json();
 ws=new WebSocket(tabs.find(t=>t.type==='page'&&t.url==='about:blank').webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
 let id=0;const pending=new Map();
 ws.onmessage=event=>{const message=JSON.parse(event.data);tracker.observe(message);if(message.id){const p=pending.get(message.id);pending.delete(message.id);message.error?p.reject(message.error):p.resolve(message.result);}
  if(message.method==='Browser.downloadWillBegin'||message.method==='Browser.downloadProgress')downloads.push({method:message.method,params:message.params,stage,owner});
  if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails);
  if(message.method==='Network.requestWillBeSent'){const request=message.params.request,u=new URL(request.url);if(u.hostname==='127.0.0.1')network.set(message.params.requestId,{request_id:message.params.requestId,owner,method:request.method,path:u.pathname,stage,body_sha256:request.postData?sha(request.postData):null,status:null});}
  if(message.method==='Network.responseReceived'){const r=network.get(message.params.requestId);if(r)r.status=message.params.response.status;}
 };
 const send=(method,params={})=>new Promise((resolve,reject)=>{const request=++id,t=setTimeout(()=>{pending.delete(request);reject(Error('CDP timeout '+method));},15000);pending.set(request,{resolve:v=>{clearTimeout(t);resolve(v);},reject:e=>{clearTimeout(t);reject(e);}});ws.send(JSON.stringify({id:request,method,params}));});
 const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
 const click=id=>evaluate('document.getElementById('+JSON.stringify(id)+').click()');
 const fill=(id,value)=>evaluate(`(()=>{const e=document.getElementById(${JSON.stringify(id)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));if(e.tagName==='SELECT')e.dispatchEvent(new Event('change',{bubbles:true}));})()`);
 const submit=id=>evaluate('document.getElementById('+JSON.stringify(id)+').requestSubmit()');
 const get=async(base,name)=>(await(await fetch(base+'/api/workbench/'+name)).json());
 const api=async(base,name,body)=>{const response=await fetch(base+'/api/workbench/'+name,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const row=await response.json();assert.ok(response.ok,JSON.stringify(row));return row;};
 const fixtures=path.join(root,'tests/fixtures/pointclouds'),meshFixtures=path.join(root,'tests/fixtures/meshes');
 const mesh=await api(base,'mesh-import',{name:'Retained triangle',files:{'mesh.ply':fs.readFileSync(path.join(meshFixtures,'tetrahedron.ply')).toString('base64'),'mesh.json':fs.readFileSync(path.join(meshFixtures,'tetrahedron.json')).toString('base64')}});
 const image=await api(base,'import',{kind:'image',name:'Retained polygon',image:fs.readFileSync(path.join(root,'tests/fixtures/workbench-ui/blue-book-qa.png')).toString('base64'),groups:['unrelated-point-ui-image']});
 const open=async row=>{stage='rendered open '+row.name;await evaluate('window.qaPreviousCurrent=current');await evaluate(`(()=>{const e=[...document.querySelectorAll('#records .record')].find(r=>r.querySelector('input')?.getAttribute('aria-label')===${JSON.stringify('Select '+row.name)});if(!e)throw Error('Row not rendered');e.querySelector('button').click();})()`);await until(()=>evaluate('current!==window.qaPreviousCurrent&&current?.id==='+JSON.stringify(row.id)+'&&!dirty'));};
 const navigate=async url=>{const old=(await send('Page.getFrameTree')).frameTree.frame;await send('Page.navigate',{url});await until(()=>tracker.reloaded(old));await until(()=>evaluate('document.readyState==="complete"&&document.getElementById("notice")?.textContent==="Collection ready."'));};
 const reload=async()=>{await evaluate('window.qaPreviousCurrent=current');await click('reload');await until(()=>evaluate('current!==window.qaPreviousCurrent&&!dirty&&!document.getElementById("reload").dataset.busy'));};
 const discardReload=async()=>{const promise=click('reload');await pause(80);await send('Page.handleJavaScriptDialog',{accept:true});await promise;await until(()=>evaluate('!dirty&&!document.getElementById("reload").dataset.busy'));};
 const choose=(id,name,raw)=>evaluate(`(()=>{const dt=new DataTransfer();dt.items.add(new File([Uint8Array.from(atob(${JSON.stringify(raw.toString('base64'))}),c=>c.charCodeAt(0))],${JSON.stringify(name)}));document.getElementById(${JSON.stringify(id)}).files=dt.files;})()`);
 const importPair=async(name,raw,sidecar)=>{stage='rendered point import '+name;await choose('pointcloud-ply','points.ply',raw);await choose('pointcloud-manifest','points.json',sidecar);await fill('pointcloud-name',name);await submit('pointcloud-import-form');await until(()=>evaluate('!pointcloudImportBusy'));assert.match(await evaluate('document.getElementById("pointcloud-import-status").textContent'),/unreviewed/);};
 const actualDownload=async(selector,name)=>{stage='rendered file download '+name;const url=await evaluate(`document.querySelector(${JSON.stringify(selector)}).href`),folder=path.join(output,'downloads',name);fs.mkdirSync(folder,{recursive:true});await send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:folder,eventsEnabled:true});await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);await until(()=>downloads.some(d=>d.method==='Browser.downloadWillBegin'&&d.params.url===url));const begun=downloads.findLast(d=>d.method==='Browser.downloadWillBegin'&&d.params.url===url);await until(()=>downloads.some(d=>d.method==='Browser.downloadProgress'&&d.params.guid===begun.params.guid&&d.params.state==='completed'));const archive=path.join(folder,begun.params.suggestedFilename);return {url,archive,sha256:sha(fs.readFileSync(archive)),guid:begun.params.guid};};
 const save=async()=>{await submit('editor');await until(()=>evaluate('!document.getElementById("editor").dataset.busy'));assert.equal(await evaluate('dirty'),false);};
 const inspect=()=>until(()=>evaluate('document.querySelectorAll("#pointcloud-projections circle").length===current.pointcloud.point_count*3'));
 const reviewRow=async row=>{await open(row);await fill('pointcloud-note','QA authored fixture inspected; not training qualification.');await fill('record-review','draft');await save();await reload();assert.equal(await evaluate('current.review'),'draft');await fill('record-review','human_reviewed');await save();assert.equal(await evaluate('current.review'),'human_reviewed');};
 const selectRows=async rows=>{await click('clear-selection');for(const row of rows)await evaluate(`document.querySelector('input[aria-label='+${JSON.stringify(JSON.stringify('Select '+row.name))}+']').click()`);assert.equal(await evaluate('selected.size'),rows.length);};
 const freeze=async(name,rows)=>{await selectRows(rows);await fill('train',50);await fill('validation',50);await fill('test',0);await click('preview-release');await until(()=>evaluate('!releaseBusy'));assert.equal(await evaluate('releasePreview.eligible'),true);await submit('release-form');await until(()=>evaluate('!releaseBusy&&!!document.querySelector("#release-result a")'));const file=await actualDownload('#release-result a',name),expected=path.join(output,name+'-expected.json');fs.writeFileSync(expected,JSON.stringify(rows,null,2)+'\n');assert.ok(file.url.includes(file.sha256));execFileSync(python,['tests/check_pointcloud_consumer.py','--archive',file.archive,'--expected',expected,'--output',path.join(output,name+'-consumer')],{cwd:root,stdio:'inherit',timeout:60000});return file;};
 await send('Page.enable');await send('Runtime.enable');await send('Network.enable');await send('Page.setLifecycleEventsEnabled',{enabled:true});await navigate(base+'/workbench');
 await open(mesh);await fill('mesh-note','Keep unsaved triangle inspection');await evaluate('document.querySelector('+JSON.stringify('input[aria-label="Select '+mesh.name+'"]')+').click();document.getElementById("pointcloud-import-panel").open=true');
 const raw=fs.readFileSync(path.join(fixtures,'colored.ply')),sidecar=fs.readFileSync(path.join(fixtures,'colored.json'));
 // Real admitted HTTP response is held; repeated rendered submit cannot publish twice.
 await evaluate('window.qaFetch=window.fetch;window.qaPointPosts=0;window.qaHoldImport=true;window.fetch=async(...args)=>{const response=await qaFetch(...args);if(String(args[0]).endsWith("/pointcloud-import")){qaPointPosts++;if(qaHoldImport){qaHoldImport=false;await new Promise(resolve=>window.qaImportRelease=resolve);}}return response;}');
 await choose('pointcloud-ply','points.ply',raw);await choose('pointcloud-manifest','points.json',sidecar);await fill('pointcloud-name','Colored scan');await submit('pointcloud-import-form');await until(()=>evaluate('!!window.qaImportRelease'));await submit('pointcloud-import-form');assert.equal(await evaluate('qaPointPosts'),1);await evaluate('qaImportRelease()');await until(()=>evaluate('!pointcloudImportBusy'));
 assert.equal(await evaluate('current.id'),mesh.id);assert.equal(await evaluate('document.getElementById("mesh-note").value'),'Keep unsaved triangle inspection');assert.equal(await evaluate('dirty'),true);assert.equal(await evaluate('selected.size'),1);
 let rows=(await get(base,'records?kind=pointcloud')).items;assert.equal(rows.length,1);let colored=rows[0];assert.equal(colored.review,'draft');assert.equal(colored.annotation,null);assert.equal(colored.provenance.rights,'unknown');
 await choose('pointcloud-ply','points.ply',Buffer.from(raw.toString().replace('1 2 0','bad!!')));await submit('pointcloud-import-form');await until(()=>evaluate('!pointcloudImportBusy'));assert.match(await evaluate('document.getElementById("pointcloud-import-status").textContent'),/SHA256 mismatch/);
 await choose('pointcloud-ply','wrong.ply',raw);await submit('pointcloud-import-form');await until(()=>evaluate('!pointcloudImportBusy'));assert.match(await evaluate('document.getElementById("pointcloud-import-status").textContent'),/Choose points.ply/);assert.equal((await get(base,'records?kind=pointcloud')).total,1);
 await discardReload();await open(image);await fill('task','image_segmentation');await fill('label','Retained QA polygon');await fill('polygon-points','1,1\n4,1\n4,4\n1,4');await click('add-polygon');const pendingPolygon=await evaluate('JSON.stringify(targets)');
 await importPair('XYZ scan',fs.readFileSync(path.join(fixtures,'xyz.ply')),fs.readFileSync(path.join(fixtures,'xyz.json')));assert.equal(await evaluate('current.id'),image.id);assert.equal(await evaluate('JSON.stringify(targets)'),pendingPolygon);assert.equal(await evaluate('dirty'),true);await discardReload();
 const variantRaw=Buffer.from(raw.toString().replace('255 0 0','254 0 0')),variantManifest=JSON.parse(sidecar);variantManifest.geometry_bytes=variantRaw.length;variantManifest.geometry_sha256=sha(variantRaw);variantManifest.provenance.revision='QA-attribute-variant';variantManifest.lineage.source_id='colored-variant';
 await importPair('Colored attribute variant',variantRaw,Buffer.from(JSON.stringify(variantManifest)));
 rows=(await get(base,'records?kind=pointcloud')).items;colored=rows.find(r=>r.name==='Colored scan');const xyz=rows.find(r=>r.name==='XYZ scan'),variant=rows.find(r=>r.name==='Colored attribute variant');
 await open(colored);await inspect();assert.equal(await evaluate('document.getElementById("task").value'),'pointcloud_geometry');assert.match(await evaluate('document.getElementById("pointcloud-metadata").textContent'),/uchar/);assert.match(await evaluate('document.getElementById("pointcloud-preview-status").textContent'),/first 4 original points/);
 // Lost committed save is not an invitation to replay a new revision.
 await fill('pointcloud-note','Lost-ack QA note');await evaluate(`window.qaBaseFetch=window.fetch;window.qaLoseSave=true;window.fetch=async(input,options)=>{const response=await qaBaseFetch(input,options);if(String(input)==='/api/workbench/records/${colored.id}'&&options?.method==='POST'&&qaLoseSave){qaLoseSave=false;throw Error('Controlled lost point save acknowledgement');}return response;}`);await submit('editor');await until(()=>evaluate('!document.getElementById("editor").dataset.busy'));assert.equal(await evaluate('dirty'),true);assert.equal((await get(base,'history/'+colored.id)).length,2);await submit('editor');await until(()=>evaluate('!document.getElementById("editor").dataset.busy'));assert.equal((await get(base,'history/'+colored.id)).length,2);await discardReload();assert.equal(await evaluate('current.review'),'draft');assert.equal(await evaluate('document.getElementById("pointcloud-note").value'),'Lost-ack QA note');
 await fill('pointcloud-note','Held-save QA note');await evaluate(`window.qaSaveFetch=window.fetch;window.qaHoldSave=true;window.fetch=async(input,options)=>{const response=await qaSaveFetch(input,options);if(String(input)==='/api/workbench/records/${colored.id}'&&options?.method==='POST'&&qaHoldSave){qaHoldSave=false;await new Promise(resolve=>window.qaSaveRelease=resolve);}return response;}`);await submit('editor');await until(()=>evaluate('!!window.qaSaveRelease'));await submit('editor');await fill('pointcloud-note','Later unsaved point note');await evaluate('qaSaveRelease()');await until(()=>evaluate('!document.getElementById("editor").dataset.busy'));assert.equal(await evaluate('document.getElementById("pointcloud-note").value'),'Later unsaved point note');assert.equal(await evaluate('dirty'),true);assert.equal((await get(base,'history/'+colored.id)).length,3);await discardReload();
 // An old response may neither replace another kind nor a later same-ID editor.
 await evaluate('window.qaInspectionFetch=window.fetch;window.qaHoldInspection=true;window.fetch=async(...args)=>{const response=await qaInspectionFetch(...args);if(String(args[0]).includes("/pointcloud-inspection/")&&qaHoldInspection){qaHoldInspection=false;await new Promise(resolve=>window.qaInspectionRelease=resolve);}return response;}');
 await open(colored);await until(()=>evaluate('!!window.qaInspectionRelease'));await open(mesh);assert.equal(await evaluate('document.getElementById("pointcloud-inspection").hidden'),true);await open(colored);await inspect();await fill('pointcloud-note','Later inspection note');await evaluate('qaInspectionRelease()');await pause(100);assert.equal(await evaluate('document.getElementById("pointcloud-note").value'),'Later inspection note');await save();await reload();assert.equal(await evaluate('current.review'),'draft');await fill('record-review','human_reviewed');await save();
 for(const row of [xyz,variant])await reviewRow(row);
 rows=await Promise.all([colored,xyz,variant].map(r=>get(base,'records/'+r.id)));await open(rows[0]);await inspect();const rawDownload=await actualDownload('#pointcloud-download','original-raw-pair');
 execFileSync(python,['-c',"import sys,zipfile;from pathlib import Path;a=zipfile.ZipFile(sys.argv[1]);f=Path(sys.argv[2]);assert a.read('points.ply')==(f/'colored.ply').read_bytes();assert a.read('points.json')==(f/'colored.json').read_bytes()",rawDownload.archive,fixtures],{cwd:root});
 const first=await freeze('first-points',rows),firstBytes=fs.readFileSync(first.archive);
 await evaluate('document.getElementById("pointcloud-inspection").scrollIntoView()');fs.writeFileSync(path.join(output,'pointcloud-desktop.jpg'),Buffer.from((await send('Page.captureScreenshot',screenshotOptions)).data,'base64'));
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});await evaluate('document.getElementById("pointcloud-inspection").scrollIntoView()');assert.ok(await evaluate('document.documentElement.scrollWidth<=innerWidth'));fs.writeFileSync(path.join(output,'pointcloud-narrow.jpg'),Buffer.from((await send('Page.captureScreenshot',screenshotOptions)).data,'base64'));await send('Emulation.clearDeviceMetricsOverride');
 owner='second';await navigate(secondBase+'/workbench');let transferred=[];
 for(const original of rows){const pair=path.join(output,'first-points-consumer','first-extracted',original.id);await importPair(original.name,fs.readFileSync(path.join(pair,'points.ply')),fs.readFileSync(path.join(pair,'points.json')));const row=(await get(secondBase,'records?kind=pointcloud')).items.find(r=>r.name===original.name);assert.equal(row.review,'draft');assert.equal(row.annotation,null);assert.equal(row.provenance.rights,'unknown');assert.notEqual(row.id,original.id);assert.equal(row.source_split,original.source_split);assert.deepEqual(row.pointcloud,original.pointcloud);transferred.push(row);}
 for(const row of transferred){await open(row);await fill('pointcloud-note','Second-owner QA inspection draft');await save();await reload();assert.equal(await evaluate('current.review'),'draft');await fill('rights-note-value','Second owner local QA permission note');await submit('rights-note-form');await until(()=>evaluate('!rightsBusy'));assert.equal(await evaluate('current.review'),'draft');await fill('record-review','human_reviewed');await save();}
 transferred=await Promise.all(transferred.map(r=>get(secondBase,'records/'+r.id)));const second=await freeze('second-points',transferred),secondBytes=fs.readFileSync(second.archive);
 await open(transferred[0]);await fill('pointcloud-note','New draft after frozen second-owner release');await save();await click('preview-release');await until(()=>evaluate('!releaseBusy'));assert.equal(await evaluate('releasePreview.eligible'),false);assert.deepEqual(fs.readFileSync(first.archive),firstBytes);assert.deepEqual(fs.readFileSync(second.archive),secondBytes);assert.equal(sha(Buffer.from(await(await fetch(second.url)).arrayBuffer())),second.sha256);
 // Explicit sample cap and zero-span projection; final unseen point still affects whole-cloud bounds.
 const sampleRaw=Buffer.from('ply\nformat ascii 1.0\nelement vertex 513\nproperty double x\nproperty double y\nproperty double z\nend_header\n'+'0 0 0\n'.repeat(512)+'99 1 2\n'),sampleManifest=JSON.parse(sidecar);sampleManifest.geometry_bytes=sampleRaw.length;sampleManifest.geometry_sha256=sha(sampleRaw);sampleManifest.lineage={namespace:'tuldok-point-ui-samples',source_id:'513-points',family_id:'sample-family',split:'unassigned'};
 await importPair('Bounded sample',sampleRaw,Buffer.from(JSON.stringify(sampleManifest)));const sampled=(await get(secondBase,'records?kind=pointcloud')).items.find(r=>r.name==='Bounded sample');await open(sampled);await until(()=>evaluate('document.querySelectorAll("#pointcloud-projections circle").length===1536'));assert.match(await evaluate('document.getElementById("pointcloud-preview-status").textContent'),/first 512 original points/);assert.equal(await evaluate('current.pointcloud.bounds.max[0]'),99);assert.ok(await evaluate('[...document.querySelectorAll("#pointcloud-projections circle")].every(p=>Number.isFinite(Number(p.getAttribute("cx")))&&Number.isFinite(Number(p.getAttribute("cy"))))'));
 const zeroRaw=Buffer.from('ply\nformat ascii 1.0\nelement vertex 1\nproperty float x\nproperty float y\nproperty float z\nend_header\n0 0 0\n');sampleManifest.geometry_bytes=zeroRaw.length;sampleManifest.geometry_sha256=sha(zeroRaw);sampleManifest.lineage.source_id='zero-span';sampleManifest.lineage.family_id='zero-span-family';await importPair('Zero-span cloud',zeroRaw,Buffer.from(JSON.stringify(sampleManifest)));const zero=(await get(secondBase,'records?kind=pointcloud')).items.find(r=>r.name==='Zero-span cloud');await open(zero);await inspect();assert.ok(await evaluate('[...document.querySelectorAll("#pointcloud-projections circle")].every(p=>p.getAttribute("cx")==="120"&&p.getAttribute("cy")==="110")'));
 assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(output,'pointcloud-ui-report.json'),JSON.stringify({status:'PASS',source_records:rows,second_owner_records:transferred,raw_download:rawDownload,first_release:first,second_release:second,download_events:downloads,network:[...network.values()],review_basis:'Authored tiny QA fixtures and simulated separate draft/reopen/review clicks; no curated benchmark or training claim.',preserved_dirty_mesh_and_polygon:true,lost_save_CAS_no_duplicate_history:true,held_repeated_save_and_later_note:true,stale_inspection_same_ID_and_kind_switch:true,byte_exact_second_owner_native_lineage_fixed_splits:true,bounded_512_sample_and_all_bounds:true,zero_span_finite_projections:true,source_unknown_rights_and_local_review:true,post_edit_selection_ineligible_and_frozen_first_bytes_unchanged:true,no_model_or_training:true},null,2)+'\n');
 console.log('Point-cloud actual Chromium import/review/raw+release download/two-owner/pinned-reader/lineage/sample/CAS PASS: '+output);
})().catch(error=>{console.error('Stage:',stage,error);console.error('Runtime errors:',JSON.stringify(errors));process.exitCode=1;}).finally(async()=>{if(ws)ws.close();for(const child of children)child.kill();await pause(250);for(const child of children)if(child.exitCode===null&&child.signalCode===null)child.kill('SIGKILL');fs.rmSync(scratch,{recursive:true,force:true});});
