// Recorded actual producer bytes. Never invokes an exporter or a simulation.
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {spawn,spawnSync}=require('node:child_process');
const {pageLoadTracker}=require('./browser_page_load.cjs');
const {qaDirectory,screenshotOptions}=require('./qa_artifacts.cjs');
const root=path.resolve(process.env.TULDOK_SOURCE_ROOT||path.join(__dirname,'..')),source=path.join(root,'tests/fixtures/rheon_actual_fee7b4a');
const report=qaDirectory(root,'sequence-temporal-labels',process.env.TULDOK_TEMPORAL_LABELS_REPORT_ROOT||process.env.TULDOK_QA_OUTPUT_ROOT);
const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'tuldok-temporal-labels-browser-')),children=[],errors=[],tracker=pageLoadTracker();
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms)),sha=raw=>crypto.createHash('sha256').update(raw).digest('hex');
let ws,inspect;
async function until(fn){for(let i=0;i<150;i++){const result=await fn();if(result)return result;await pause(100);}throw Error('Timed out');}
function launch(command,args,options={}){const child=spawn(command,args,options);children.push(child);return child;}
function python(code,...args){const result=spawnSync('python3',['-c',code,...args],{cwd:root,encoding:'utf8',timeout:30000});assert.equal(result.status,0,result.stderr);return result.stdout;}
(async()=>{
  const run=fs.readFileSync(path.join(source,'run.json')),frames=fs.readFileSync(path.join(source,'frames.jsonl'));
  const manifest=JSON.parse(run),receipt=JSON.parse(fs.readFileSync(path.join(source,'producer-receipt.json')));
  assert.equal(sha(run),receipt.run_sha256);assert.equal(sha(frames),receipt.frames_sha256);
  assert.equal(manifest.provenance.source_commit,'fee7b4a139574f87b259796b1ba8698a41d31ac1');assert.equal(manifest.provenance.source_dirty,false);
  assert.equal(manifest.provenance.base_commit,'9cd4587a54befa61bdfddc8e35014bd3c34f02fb');
  assert.deepEqual(manifest.provenance.build_command,['cargo','build','--locked','--no-default-features','--example','dense3d_sequence']);
  assert.equal(manifest.frames_bytes,frames.length);assert.equal(manifest.frames_sha256,sha(frames));
  assert.equal(manifest.frame_count,9);assert.match(receipt.basis,/actual producer execution/);
  const evidence={basis:'recorded actual one-shot capped producer output; no exporter/simulation invoked by browser test',producer_receipt:receipt,manifest,run_sha256:sha(run),frames_sha256:sha(frames),checks:[]};
  // Source-derived comparison remains explicitly synthetic, with its placeholders.
  python("import sys,json; from pathlib import Path; sys.path.insert(0,'tests'); from test_sequences import fixture; p=Path(sys.argv[1]); run,frames=fixture(); (p/'synthetic-run.json').write_bytes(run); (p/'synthetic-frames.jsonl').write_bytes(frames)",temporary);
  const server=launch('python3',['-u','app.py','--port','0','--data',path.join(temporary,'data')],{cwd:root,stdio:['ignore','pipe','pipe']});
  let output='';server.stdout.on('data',chunk=>output+=chunk);
  const port=await until(()=>output.match(/127\.0\.0\.1:(\d+)/)?.[1]),base='http://127.0.0.1:'+port;
  const request=async(route,body)=>{const response=await fetch(base+'/api/workbench/'+route,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});return {status:response.status,result:await response.json()};};
  const api=async(route,body)=>{const response=await request(route,body);assert.ok(response.status<300,JSON.stringify(response));return response.result;};
  launch(process.env.BROWSER||'/usr/bin/chromium',['--headless','--no-sandbox','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--window-size=1400,950','--user-data-dir='+path.join(temporary,'browser'),'about:blank'],{stdio:['ignore','ignore','ignore'],env:{...process.env,XDG_CONFIG_HOME:temporary,XDG_CACHE_HOME:temporary}});
  const active=path.join(temporary,'browser','DevToolsActivePort'),debugPort=await until(()=>fs.existsSync(active)&&fs.readFileSync(active,'utf8').split('\n')[0]);
  const tabs=await(await fetch('http://127.0.0.1:'+debugPort+'/json')).json(),target=tabs.find(tab=>tab.type==='page'&&tab.url==='about:blank');assert.ok(target);
  ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
  let id=0;const pending=new Map();const send=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
  ws.onmessage=event=>{const message=JSON.parse(event.data);tracker.observe(message);if(message.id){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(message.error):task.resolve(message.result);}if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails);if(message.method==='Page.javascriptDialogOpening')send('Page.handleJavaScriptDialog',{accept:true}).catch(error=>errors.push(error));};
  const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));return result.result.value;};
  inspect=()=>evaluate('JSON.stringify({notice:document.getElementById("notice")?.textContent,status:document.getElementById("sequence-import-status")?.textContent,current:current?.id,dirty,selected:selected.size,preview:releasePreview})');
  const fill=(id,value)=>evaluate(`(()=>{const e=document.getElementById(${JSON.stringify(id)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  const choose=(id,name,contents)=>evaluate(`(()=>{const raw=Uint8Array.from(atob(${JSON.stringify(contents.toString('base64'))}),c=>c.charCodeAt(0)),dt=new DataTransfer();dt.items.add(new File([raw],${JSON.stringify(name)}));document.getElementById(${JSON.stringify(id)}).files=dt.files;})()`);
  await send('Page.enable');await send('Page.setLifecycleEventsEnabled',{enabled:true});await send('Runtime.enable');
  await send('Page.navigate',{url:base+'/workbench'});await until(()=>evaluate('document.getElementById("notice")?.textContent==="Collection ready."'));
  const actual=await api('sequence-import',{files:{'run.json':run.toString('base64'),'frames.jsonl':frames.toString('base64')},name:'Actual trajectory temporal authoring'});
  await evaluate(`openRecord(${JSON.stringify(actual.id)})`);assert.equal(await evaluate('document.getElementById("sequence-temporal").closest("form").id'),'editor');
  const owner=()=>evaluate('JSON.stringify({current:current.id,revision:current.revision,dirty,editorEpoch,note:document.getElementById("sequence-note").value,review:document.getElementById("record-review").value,selected:[...selected],query:document.getElementById("query").value,ranges:sequenceTemporalRanges})');
  await fill('sequence-note','Retain 🦋 human whole-trajectory review note');await fill('query','temporal');await evaluate('selected.set(current.id,current);selection(true)');
  // Actual native inspection stays independent of human target drafting.
  const beforeInspect=await owner();await evaluate('document.getElementById("sequence-review-load").click()');await until(()=>evaluate('sequenceReviewData!==null'));await fill('sequence-review-frame',8);assert.equal(await owner(),beforeInspect);
  const add=async(label,first,last,rationale)=>{await fill('sequence-temporal-label',label);await fill('sequence-temporal-first',first);await fill('sequence-temporal-last',last);await fill('sequence-temporal-rationale',rationale);await evaluate('document.getElementById("sequence-temporal-add").click()');};
  await fill('sequence-temporal-label','Pending human range');await evaluate('document.getElementById("editor").requestSubmit()');await until(()=>evaluate('!document.getElementById("editor").dataset.busy'));assert.match(await evaluate('document.getElementById("notice").textContent'),/pending temporal/);assert.equal((await api('history/'+actual.id)).length,1);assert.equal((await api('records/'+actual.id)).annotation,null);
  await evaluate('document.getElementById("sequence-temporal-cancel").click()');await add('Human transition',0,1,'Visual appearance changed across these source frames; human judgment only.');await add('Human later appearance',2,8,'Reviewer-defined useful later range; no solver-truth claim.');
  assert.equal(await evaluate('sequenceTemporalRanges.length'),2);assert.equal(await evaluate('dirty'),true);assert.equal(await evaluate('document.getElementById("record-review").value'),'draft');assert.equal(await evaluate('document.getElementById("sequence-note").value'),'Retain 🦋 human whole-trajectory review note');
  const staged=await evaluate('JSON.stringify(sequenceTemporalRanges)');await add(' Human transition ',0,1,'Duplicate attempt');assert.equal(await evaluate('JSON.stringify(sequenceTemporalRanges)'),staged);assert.match(await evaluate('document.getElementById("sequence-temporal-status").textContent'),/Duplicate/);
  await evaluate('document.getElementById("sequence-temporal-clear").dispatchEvent(new MouseEvent("click"))');assert.equal(await evaluate('JSON.stringify(sequenceTemporalRanges)'),staged);assert.match(await evaluate('document.getElementById("sequence-temporal-status").textContent'),/pending/);await evaluate('document.getElementById("sequence-temporal-cancel").click()');
  await evaluate('document.querySelectorAll("#sequence-temporal-list button")[0].click()');await fill('sequence-temporal-label','Human early transition');await evaluate('document.getElementById("sequence-temporal-add").click()');assert.equal(await evaluate('sequenceTemporalRanges[0].label'),'Human early transition');
  await add('Temporary constructor judgment',0,0,'One-frame constructor judgment for UI remove coverage.');await evaluate('document.querySelectorAll("#sequence-temporal-list button")[5].click()');assert.equal(await evaluate('sequenceTemporalRanges.length'),2);
  // Real browser JSON.stringify sends time0; server persists canonical metadata float0.0.
  await evaluate('document.getElementById("editor").requestSubmit()');await until(()=>evaluate('!dirty&&current.revision===2'));
  const drafted=await api('records/'+actual.id);assert.equal(drafted.review,'draft');assert.equal(drafted.annotation.temporal_labels.ranges.length,2);assert.equal(drafted.annotation.temporal_labels.origin,'human_defined_annotation');assert.equal(drafted.annotation.temporal_labels.ranges[0].start.time_s,0);
  assert.deepEqual(drafted.sequence,actual.sequence);assert.deepEqual(drafted.provenance,actual.provenance);assert.equal((await api('history/'+actual.id)).length,2);
  const items=row=>[{id:row.id,revision:row.revision,source_revision:row.source_revision}],ratios={train:100,validation:0,test:0};assert.equal((await api('releases/preview',{items:items(drafted),ratios,seed:42})).eligible,false);
  await evaluate(`openRecord(${JSON.stringify(actual.id)})`);assert.deepEqual(await evaluate('sequenceTemporalRanges'),drafted.annotation.temporal_labels.ranges);
  // Retained drafts across dispatched lifecycle restore, with pending form retained.
  await fill('sequence-temporal-label','Retain pending proposal');const pendingBefore=await evaluate('JSON.stringify({ranges:sequenceTemporalRanges,label:document.getElementById("sequence-temporal-label").value,note:document.getElementById("sequence-note").value})');await evaluate('window.dispatchEvent(new PageTransitionEvent("pagehide"));window.dispatchEvent(new PageTransitionEvent("pageshow",{persisted:true}))');assert.equal(await evaluate('JSON.stringify({ranges:sequenceTemporalRanges,label:document.getElementById("sequence-temporal-label").value,note:document.getElementById("sequence-note").value})'),pendingBefore);assert.equal(await evaluate('sequenceTemporalPending'),true);await evaluate('document.getElementById("sequence-temporal-cancel").click()');
  await fill('record-review','human_reviewed');await evaluate('document.getElementById("editor").requestSubmit()');await until(()=>evaluate('!dirty&&current.revision===3&&current.review==="human_reviewed"'));const reviewed=await api('records/'+actual.id);
  evidence.checks.push('actual retained source/native inspection independent; pending Save refusal publishes nothing; Add/Edit/Remove/Cancel/duplicate/destructive guard; human frame0..1+2..8 draft save/reopen, separate review/history and lifecycle-retained pending drafts');
  // Actual competing writer makes the UI exact target revision stale.
  await evaluate('document.querySelectorAll("#sequence-temporal-list button")[0].click()');await fill('sequence-temporal-label','Local conflicting human opinion');await evaluate('document.getElementById("sequence-temporal-add").click()');const localRanges=await evaluate('JSON.stringify(sequenceTemporalRanges)');
  const other=structuredClone(reviewed.annotation);other.temporal_labels.ranges[0].label='Other human opinion';
  const external=await api('records/'+actual.id,{revision:3,source_revision:1,task:'sequence_transport',annotation:other,groups:reviewed.groups,review:'draft'});assert.equal(external.revision,4);
  await evaluate('document.getElementById("editor").requestSubmit()');await until(()=>evaluate('!document.getElementById("editor").dataset.busy'));assert.match(await evaluate('document.getElementById("notice").textContent'),/changed.*Reload/);assert.equal(await evaluate('current.revision'),3);assert.equal(await evaluate('JSON.stringify(sequenceTemporalRanges)'),localRanges);assert.equal(await evaluate('dirty'),true);assert.deepEqual(await api('records/'+actual.id),external);
  // Controlled lifecycle mismatch with the actual backend's new record. This is
  // dispatched restore coverage, not a claim of an actual browser BFCache trip.
  await evaluate(`window.dispatchEvent(new PageTransitionEvent("pagehide"));current=${JSON.stringify(external)};window.dispatchEvent(new PageTransitionEvent("pageshow",{persisted:true}))`);
  assert.equal(await evaluate('document.getElementById("sequence-temporal-label").disabled'),true);assert.equal(await evaluate('JSON.stringify(sequenceTemporalRanges)'),localRanges);
  await evaluate('document.getElementById("reload").click()');await until(()=>evaluate('!dirty&&current.revision===4'));assert.equal(await evaluate('sequenceTemporalRanges[0].label'),'Other human opinion');assert.equal(await evaluate('document.getElementById("sequence-temporal-label").disabled'),false);
  await add('Recovered authoring probe',0,0,'Explicit reload restores human authoring after a stale lifecycle owner.');assert.equal(await evaluate('sequenceTemporalRanges.length'),3);await evaluate('document.querySelectorAll("#sequence-temporal-list button")[5].click()');assert.equal(await evaluate('sequenceTemporalRanges.length'),2);
  await fill('record-review','human_reviewed');await evaluate('document.getElementById("editor").requestSubmit()');await until(()=>evaluate('!dirty&&current.revision===5'));const final=await api('records/'+actual.id);assert.equal(final.review,'human_reviewed');
  const filter=await api('records?label='+encodeURIComponent('Other human opinion'));assert.equal(filter.total,1);assert.equal(filter.analysis.labels['Other human opinion'],1);
  evidence.checks.push('actual competing writer yields409, local staged targets preserved without overwrite; controlled persisted-restore owner mismatch disables authoring, deliberate backend reload recovers Add/Remove and separate rereview; saved-label exact metadata filter/analysis');
  const synthetic=await api('sequence-import',{files:{'run.json':fs.readFileSync(path.join(temporary,'synthetic-run.json')).toString('base64'),'frames.jsonl':fs.readFileSync(path.join(temporary,'synthetic-frames.jsonl')).toString('base64')},name:'Synthetic unselected initial-family relative'});
  const syntheticReviewed=await api('records/'+synthetic.id,{revision:1,source_revision:1,task:'sequence_transport',annotation:{note:'Legacy note-only synthetic review for grouping control'},groups:synthetic.groups,review:'human_reviewed'});
  const split=await api('releases/preview',{items:[...items(final),...items(syntheticReviewed)],ratios:{train:50,validation:50,test:0},seed:42});assert.equal(split.eligible,false);assert.ok(split.blockers.some(b=>/Too few independent/.test(b.message)));evidence.family_split_preview=split;
  const pre=await api('releases/preview',{items:items(final),ratios,seed:42});assert.equal(pre.eligible,true);assert.deepEqual(new Set(pre.lineage[0].member_ids),new Set([final.id,synthetic.id]));evidence.single_selection_preview=pre;
  await fill('query','');await fill('kind','sequence');await evaluate('refresh()');await until(()=>evaluate('page.total===2'));await evaluate('document.getElementById("clear-selection").click()');await until(()=>evaluate('!document.getElementById("clear-selection").dataset.busy'));await evaluate('document.querySelector('+JSON.stringify('input[aria-label="Select '+actual.name+'"]')+').click()');await fill('train',100);await fill('validation',0);await fill('test',0);
  await evaluate('document.getElementById("preview-release").click()');await until(()=>evaluate('!document.getElementById("freeze-release").disabled'));await evaluate('document.getElementById("release-form").requestSubmit()');await until(()=>evaluate('!!document.querySelector("#release-result a")'));
  const frozen=Buffer.from(await(await fetch(await evaluate('document.querySelector("#release-result a").href'))).arrayBuffer());const archive=path.join(report,'whole-trajectory-labelled-release.zip');fs.writeFileSync(archive,frozen);
  const checked=JSON.parse(python("import sys,json,zipfile,hashlib,io;from pathlib import Path;z=zipfile.ZipFile(sys.argv[1]);m=json.loads(z.read('manifest.json'));assert len(m['records'])==1;r=m['records'][0];assert r['kind']=='sequence' and r['split']=='train' and r['review']=='human_reviewed';assert [json.loads(line) for line in z.read('train/records.jsonl').splitlines()]==[r];a=r['annotation']['temporal_labels'];assert a['version']==1 and a['origin']=='human_defined_annotation' and len(a['ranges'])==2;assert a['ranges'][0]['label']=='Other human opinion';b=z.read(r['asset']);assert hashlib.sha256(b).hexdigest()==r['content_hash']==a['source']['content_hash'];inner=zipfile.ZipFile(io.BytesIO(b));p=Path(sys.argv[2]);run=(p/'run.json').read_bytes();raw=(p/'frames.jsonl').read_bytes();assert inner.read('run.json')==run and inner.read('frames.jsonl')==raw;assert a['source']['run_sha256']==hashlib.sha256(run).hexdigest() and a['source']['frames_sha256']==hashlib.sha256(raw).hexdigest();lines=raw.splitlines(keepends=True);frames=[json.loads(line) for line in lines];assert len(frames)==9;checks=[(target,key,target[key],frames[target[key+'_frame']],lines[target[key+'_frame']]) for target in a['ranges'] for key in ('start','end')];assert all(e['sha256']==hashlib.sha256(line).hexdigest() and e['frame']==f['frame'] and e['time_s']==f['time_s'] and e['carrier_stamp']==f['carrier_stamp'] and e['liquid_stamp']==f['liquid_stamp'] for target,key,e,f,line in checks);assert type(a['ranges'][0]['start']['time_s']) is float;print(json.dumps(dict(result='PASS',byte_exact_raw_bundle=True,human_targets_separate=True,all_endpoint_hash_time_stamp_associations=True,canonical_constructor_time_float=True,record_count=1,frames=9)))",archive,source));evidence.frozen_check=checked;evidence.release_sha256=sha(frozen);evidence.final_record=final;
  // Label edits do not change an already frozen archive.
  await evaluate('document.querySelectorAll("#sequence-temporal-list button")[0].click()');await fill('sequence-temporal-label','After-freeze draft opinion');await evaluate('document.getElementById("sequence-temporal-add").click();document.getElementById("editor").requestSubmit()');await until(()=>evaluate('!dirty&&current.revision===6'));assert.equal(sha(fs.readFileSync(archive)),evidence.release_sha256);
  evidence.checks.push('existing selected UI freeze: one whole trajectory, reviewed human labels in canonical JSONL/manifest, independent raw-line endpoint alignment/canonical float0.0; exact raw run+frames; family-safe split and unselected closure; frozen release unchanged after label edit');
  await evaluate('document.getElementById("sequence-temporal").scrollIntoView()');fs.writeFileSync(path.join(report,'temporal-desktop.jpg'),Buffer.from((await send('Page.captureScreenshot',screenshotOptions)).data,'base64'));await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});await evaluate('document.getElementById("sequence-temporal-list").scrollIntoView()');assert.ok(await evaluate('document.documentElement.scrollWidth<=innerWidth'));fs.writeFileSync(path.join(report,'temporal-narrow.jpg'),Buffer.from((await send('Page.captureScreenshot',screenshotOptions)).data,'base64'));
  const previous=(await send('Page.getFrameTree')).frameTree.frame;await send('Page.reload');await until(()=>tracker.reloaded(previous));await until(()=>evaluate('document.getElementById("notice")?.textContent==="Collection ready."'));await evaluate(`openRecord(${JSON.stringify(actual.id)})`);assert.equal(await evaluate('sequenceTemporalRanges[0].label'),'After-freeze draft opinion');assert.equal(await evaluate('current.review'),'draft');
  // Separate synthetic v2 controls remain source evidence, never overwritten by targets.
  const v2files=JSON.parse(python("import sys,json,base64;sys.path.insert(0,'tests');from fixtures.rheon_synthetic_v2 import fixture;print(json.dumps({n:base64.b64encode(raw).decode() for n,raw in zip(('run.json','frames.jsonl','controls.json'),fixture())}))"));const v2row=await api('sequence-import',{files:v2files,name:'Explicit synthetic v2 temporal labels'});await evaluate(`openRecord(${JSON.stringify(v2row.id)})`);await add('Human v2 final-state judgment',8,8,'Authored judgment on synthetic source-derived fixture.');
  // Actual Save succeeds at server; held old response cannot overwrite restored local drafts.
  await evaluate('window.originalTemporalFetch=fetch;window.fetch=async(...args)=>{const r=await originalTemporalFetch(...args);if(args[1]?.method==="POST"&&String(args[0]).includes("/records/"))await new Promise(resolve=>window.releaseTemporalSave=resolve);return r};document.getElementById("editor").requestSubmit()');await until(()=>evaluate('typeof releaseTemporalSave==="function"'));const v2staged=await evaluate('JSON.stringify(sequenceTemporalRanges)');await evaluate('window.dispatchEvent(new PageTransitionEvent("pagehide"));window.dispatchEvent(new PageTransitionEvent("pageshow",{persisted:true}));releaseTemporalSave();delete window.releaseTemporalSave');await until(()=>evaluate('!document.getElementById("editor").dataset.busy'));assert.equal(await evaluate('current.revision'),1);assert.equal(await evaluate('JSON.stringify(sequenceTemporalRanges)'),v2staged);assert.equal(await evaluate('dirty'),true);assert.equal((await api('records/'+v2row.id)).revision,2);await evaluate('window.fetch=originalTemporalFetch');
  await evaluate('document.getElementById("editor").requestSubmit()');await until(()=>evaluate('!document.getElementById("editor").dataset.busy'));assert.match(await evaluate('document.getElementById("notice").textContent'),/changed.*Reload/);await evaluate('document.getElementById("reload").click()');await until(()=>evaluate('!dirty&&current.revision===2'));const v2saved=await api('records/'+v2row.id);assert.deepEqual(v2saved.sequence,v2row.sequence);assert.deepEqual(v2saved.provenance,v2row.provenance);assert.equal(v2saved.annotation.temporal_labels.ranges[0].start_frame,8);
  const rawv2=Buffer.from(await(await fetch(base+'/api/workbench/asset/'+v2row.id)).arrayBuffer());fs.writeFileSync(path.join(report,'synthetic-v2-original-bundle.zip'),rawv2);evidence.synthetic_v2_record=v2saved;evidence.checks.push('real CDP reload persists targets/draft state; separately synthetic v2 labels retain controls/provenance/rawbundle; held actual Save response departure/restore retires old callback, retains staged draft, nextCAS409 requires deliberate reload');
  assert.deepEqual(errors,[]);evidence.errors=errors;evidence.result='PASS';fs.writeFileSync(path.join(report,'session.json'),JSON.stringify(evidence,null,2)+'\n');
  console.log('Human temporal labels Chromium PASS: actual native source inspection, explicit range authoring/edit/remove/cancel/pending refusal, draft save/reopen/rereview, competing409 and held Save lifecycle fencing, label filters, family-safe exact raw+target export alignment/immutability, synthetic v2 evidence separated, reload390px. No producer/model/training execution.');
})().catch(async error=>{console.error(error);if(inspect)try{console.error(await inspect());}catch{}process.exitCode=1;}).finally(async()=>{if(ws)ws.close();for(const child of children)child.kill();await pause(200);fs.rmSync(temporary,{recursive:true,force:true});});
