// Real composed controls, delayed actual HTTP, fixed pairs and both downloaded formats.
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {spawn,spawnSync}=require('node:child_process'),crypto=require('node:crypto');
const {pageLoadTracker}=require('./browser_page_load.cjs');
const root=path.resolve(__dirname,'..'),temporary=fs.mkdtempSync(path.join(os.tmpdir(),'tuldok-native-text-browser-')),children=[];
const errors=[],tracker=pageLoadTracker(),pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
let ws,inspect;let dialogAccept=false;
async function until(fn){for(let i=0;i<150;i++){const value=await fn();if(value)return value;await pause(100);}throw Error('Timed out');}
function launch(command,args,options={}){const child=spawn(command,args,options);children.push(child);return child;}
function python(code,...args){const result=spawnSync('python3',['-c',code,...args],{cwd:root,encoding:'utf8'});assert.equal(result.status,0,result.stderr);return result.stdout;}
(async()=>{
  python("import sys; from pathlib import Path; sys.path.insert(0,'tests'); from test_native_text_import import native_fixture,rewrite; p=Path(sys.argv[1]); (p/'source.zip').write_bytes(native_fixture(p/'native-source')); (p/'stop.zip').write_bytes(native_fixture(p/'native-stop',('Stop first.','Stop later.'),name_prefix='Stop')); (p/'lost.zip').write_bytes(native_fixture(p/'native-lost',('Lost first.','Lost later.'),name_prefix='Lost'))",temporary);
  const server=launch('python3',['-u','app.py','--port','0','--data',path.join(temporary,'data')],{cwd:root,stdio:['ignore','pipe','pipe']});
  let output='';server.stdout.on('data',data=>output+=data);server.stderr.on('data',data=>{if(process.env.NATIVE_TEXT_BROWSER_DEBUG)process.stderr.write(data);});
  const port=await until(()=>output.match(/127\.0\.0\.1:(\d+)/)?.[1]),base='http://127.0.0.1:'+port;
  const api=async(route,body)=>{const response=await fetch(base+'/api/workbench/'+route,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();assert.ok(response.ok,JSON.stringify(result));return result;};
  const seed=await api('import',{kind:'text',text:'Keep this editor intact.',name:'Existing editor',groups:['existing-source'],rights:'Authored'});
  const browser=launch(process.env.BROWSER||'/usr/bin/chromium',['--headless','--no-sandbox','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--window-size=1400,950','--user-data-dir='+path.join(temporary,'browser'),'about:blank'],{stdio:['ignore','ignore','inherit'],env:{...process.env,XDG_CONFIG_HOME:temporary,XDG_CACHE_HOME:temporary}});
  const active=path.join(temporary,'browser','DevToolsActivePort');
  const debugPort=await require('./browser_startup.cjs').waitForDebugger(browser,active);
  const tabs=await(await fetch('http://127.0.0.1:'+debugPort+'/json')).json(),target=tabs.find(tab=>tab.type==='page'&&tab.url==='about:blank');
  assert.ok(target,'Expected explicitly launched page');ws=new WebSocket(target.webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
  let id=0;const pending=new Map();
  ws.onmessage=event=>{const message=JSON.parse(event.data);tracker.observe(message);if(message.id){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(message.error):task.resolve(message.result);}if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails);if(message.method==='Page.javascriptDialogOpening')send('Page.handleJavaScriptDialog',{accept:dialogAccept}).catch(error=>errors.push(error));};
  const send=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));return result.result.value;};
  inspect=()=>evaluate('JSON.stringify({url:location.href,notice:document.getElementById("notice")?.textContent,status:document.getElementById("native-text-status")?.textContent,results:document.getElementById("native-text-results")?.textContent,body:document.body?.innerText.slice(0,1800)})');
  const click=id=>evaluate('document.getElementById('+JSON.stringify(id)+').click()');
  const fill=(id,value)=>evaluate(`(()=>{const e=document.getElementById(${JSON.stringify(id)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  const choose=name=>evaluate(`(()=>{const dt=new DataTransfer(),raw=Uint8Array.from(atob(${JSON.stringify(fs.readFileSync(path.join(temporary,name)).toString('base64'))}),c=>c.charCodeAt(0));dt.items.add(new File([raw],${JSON.stringify(name)},{type:'application/zip'}));document.getElementById('native-text-archive').files=dt.files;})()`);
  const submit=()=>evaluate('document.getElementById("native-text-form").requestSubmit()');
  const idle=()=>until(()=>evaluate('!document.getElementById("native-text-start").disabled'));
  await send('Page.enable');await send('Page.setLifecycleEventsEnabled',{enabled:true});await send('Runtime.enable');
  const report=path.join(root,'docs/plans/combined-workbench-local/reports');fs.mkdirSync(report,{recursive:true});
  const downloads=path.join(temporary,'downloads');fs.mkdirSync(downloads);await send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloads});
  const sourceIdentity=spawnSync('git',['rev-parse','HEAD','HEAD^{tree}'],{cwd:root,encoding:'utf8'}).stdout.trim().split('\n');
  const sourceDiff=spawnSync('git',['diff','HEAD','--','app.py','workbench.py','curation.py','dataset_releases.py','native_text_import.py','static','tests'],{cwd:root,encoding:'utf8'}).stdout;
  const evidence={source_head:sourceIdentity[0],source_tree:sourceIdentity[1],source_state:sourceDiff?'working_tree':'committed',source_diff_sha256:crypto.createHash('sha256').update(sourceDiff).digest('hex'),steps:[],screenshots:[]};
  async function capture(name,selector){for(const narrow of [false,true]){
    await send('Emulation.setDeviceMetricsOverride',{width:narrow?390:1400,height:narrow?844:1000,deviceScaleFactor:1,mobile:false});
    await pause(100);
    await evaluate('document.querySelector('+JSON.stringify(selector)+').scrollIntoView({block:"start"})');await pause(100);
    assert.ok(await evaluate('document.documentElement.scrollWidth<=innerWidth'),'Combined layout must fit');
    assert.ok(await evaluate('(()=>{const r=document.querySelector('+JSON.stringify(selector)+').getBoundingClientRect();return r.top>=0&&r.top<innerHeight&&r.bottom>0})()'),'Captured panel must be in the viewport');
    const file='combined-'+name+(narrow?'-narrow':'-desktop')+'.png',bytes=Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64');
    fs.writeFileSync(path.join(report,file),bytes);evidence.screenshots.push({file,sha256:crypto.createHash('sha256').update(bytes).digest('hex')});
  }}
  const answerPairs=()=>evaluate('JSON.stringify(responseReleaseBody().items)'),recordPairs=()=>evaluate('JSON.stringify(releaseBody().items)');
  const respond=async completion=>{await click('response-new');await fill('response-entry-format','json');await fill('response-completion',JSON.stringify(completion));await fill('response-review','human_reviewed');await evaluate('document.getElementById("response-form").requestSubmit()');await until(()=>evaluate('!responseBusy&&!responseDirty&&!responseListBusy'));};
  await send('Page.navigate',{url:base+'/workbench'});await until(()=>evaluate('document.getElementById("notice")?.textContent==="Collection ready."'));
  await evaluate('openRecord('+JSON.stringify(seed.id)+')');await until(()=>evaluate('!responseListBusy && !!responseParent'));
  await respond(' exact answer\r\ne\u0301 😀\ufeff '+'x'.repeat(1100));await respond('Independent reviewed answer');
  await evaluate('document.querySelectorAll("#response-list input").forEach(box=>box.click());document.querySelector("#records .record input").click()');
  const initialAnswers=await answerPairs(),initialRecords=await recordPairs();
  await evaluate(`(()=>{const original=window.fetch;window.recordReads=0;window.nativePosts=0;window.resultReads=0;window.answerPosts=0;window.fetch=async(...args)=>{
    const url=String(args[0]);if(url.endsWith('/records/${seed.id}')){window.recordReads++;if(window.holdInspection){window.holdInspection=false;const response=await original(...args);await new Promise(resolve=>window.releaseInspection=resolve);window.inspectionDelivered=true;return response;}}
    if(url.endsWith('/rights/${seed.id}')&&window.holdRights){window.holdRights=false;const response=await original(...args);await new Promise(resolve=>window.releaseRights=resolve);return response;}
    if(url.endsWith('/api/workbench/responses'))window.answerPosts++;
    if(url.endsWith('/native-text-import/prepare')&&window.holdPreparation){window.holdPreparation=false;const response=await original(...args);await new Promise(resolve=>window.releasePreparation=resolve);return response;}
    if(url.endsWith('/native-text-import/row')){window.nativePosts++;const response=await original(...args);if(window.holdNative){window.holdNative=false;await new Promise(resolve=>window.releaseNative=resolve);}if(window.loseNative){window.loseNative=false;throw Error('Held committed native response lost');}return response;}
    if(url.includes('/import-result/'))window.resultReads++;return original(...args);
  };})()`);
  console.log('Combined browser: curation later response intent');
  await click('response-new');await fill('curation-category','unlabeled');await click('curation-refresh');await until(()=>evaluate('!!curationReport&&!curationBusy'));
  await evaluate('window.holdInspection=true;document.querySelector("#curation-results button").click()');await until(()=>evaluate('!!window.releaseInspection'));
  await fill('response-entry-format','json');await fill('response-completion',JSON.stringify('Later inspection draft\r\n😀'));await fill('response-review','human_reviewed');
  const inspectionDraft=await evaluate('({id:responseEditor.id,value:document.getElementById("response-completion").value,review:document.getElementById("response-review").value,epoch:responseEditEpoch})');
  await evaluate('window.releaseInspection();window.releaseInspection=null');await until(()=>evaluate('window.inspectionDelivered'));
  assert.equal(await evaluate('responseDirty'),true);assert.deepEqual(await evaluate('({id:responseEditor.id,value:document.getElementById("response-completion").value,review:document.getElementById("response-review").value,epoch:responseEditEpoch})'),inspectionDraft);
  const reads=await evaluate('window.recordReads');await evaluate('document.querySelector("#curation-results button").click()');await pause(100);assert.equal(await evaluate('window.recordReads'),reads,'Discard refusal must not send another inspection');
  evidence.steps.push({stage:'curation-held-get',exact_draft:inspectionDraft,discard_refusal:true});await capture('01-curation-draft','#responses-panel');
  await click('response-cancel');await click('response-new');
  console.log('Combined browser: rights later response intent');
  await fill('rights-note-value','Local current note');await evaluate('window.holdRights=true;document.getElementById("rights-note-form").requestSubmit()');await until(()=>evaluate('!!window.releaseRights'));
  await fill('response-entry-format','json');await fill('response-completion',JSON.stringify('Later rights draft\r\n😀'));await fill('response-review','human_reviewed');
  await evaluate('document.getElementById("response-form").requestSubmit()');assert.equal(await evaluate('window.answerPosts'),0,'Rights ownership blocks answer persistence while retaining its draft');
  const rightsDraft=await evaluate('({id:responseEditor.id,value:document.getElementById("response-completion").value,review:document.getElementById("response-review").value,epoch:responseEditEpoch})');
  await evaluate('window.releaseRights();window.releaseRights=null');await until(()=>evaluate('!rightsBusy&&document.getElementById("rights-note-status").textContent.includes("Earlier note saved")'));
  assert.equal(await evaluate('responseDirty'),true);assert.deepEqual(await evaluate('({id:responseEditor.id,value:document.getElementById("response-completion").value,review:document.getElementById("response-review").value,epoch:responseEditEpoch})'),rightsDraft);
  assert.equal(await evaluate('current.revision'),seed.revision);assert.equal(await evaluate('responsePreview'),null);
  assert.equal(await answerPairs(),initialAnswers);assert.equal(await recordPairs(),initialRecords);
  const changedSeed=await api('records/'+seed.id);assert.equal(changedSeed.revision,seed.revision+1);assert.equal(changedSeed.review,'draft');
  evidence.steps.push({stage:'rights-held-ack',exact_draft:rightsDraft,pairs_retained:true,record_not_adopted:true});
  console.log('Combined browser: native Stop/lost acknowledgement with response draft');
  await choose('source.zip');await evaluate('window.holdPreparation=true');await submit();await until(()=>evaluate('!!window.releasePreparation'));
  await click('native-text-stop');await evaluate('window.releasePreparation();window.releasePreparation=null');await idle();
  assert.equal(await evaluate('window.nativePosts'),0,'Preparation cancellation admits no rows');assert.equal(await evaluate('responseEditor.id'),rightsDraft.id);
  await choose('source.zip');await evaluate('window.holdNative=true');await submit();await until(()=>evaluate('!!window.releaseNative'));
  await fill('query','No records match this fixture filter');await evaluate('document.getElementById("filters").requestSubmit()');await until(()=>evaluate('page.total===0'));
  await click('native-text-stop');await evaluate('window.releaseNative();window.releaseNative=null');await idle();
  assert.match(await evaluate('document.getElementById("native-text-status").textContent'),/Stopped: 1 created/);
  assert.deepEqual(await evaluate('({id:responseEditor.id,value:document.getElementById("response-completion").value,review:document.getElementById("response-review").value,epoch:responseEditEpoch})'),rightsDraft);
  assert.equal(await evaluate('responseDirty'),true);assert.equal(await answerPairs(),initialAnswers);assert.equal(await recordPairs(),initialRecords);
  await choose('lost.zip');await evaluate('window.loseNative=true');await submit();await idle();assert.ok(await evaluate('!!nativeTextPending'));
  const admissions=await evaluate('window.nativePosts');await click('native-text-check');await idle();assert.equal(await evaluate('window.nativePosts'),admissions);assert.equal(await evaluate('window.resultReads'),1);
  assert.equal(await evaluate('responseDirty'),true);assert.equal(await evaluate('responseEditor.id'),rightsDraft.id);assert.equal(await recordPairs(),initialRecords);assert.equal(await answerPairs(),initialAnswers);
  const drafts=(await api('records')).items.filter(row=>row.id!==seed.id);assert.equal(drafts.length,2);assert.ok(drafts.every(row=>row.review==='draft'&&row.rights_note==='unknown'));
  evidence.steps.push({stage:'native-stop-and-loss',created:2,lost_lookup_without_replay:true,exact_response_draft_retained:true});await capture('02-native-draft','#native-text-import-panel');
  await click('response-cancel');await click('rights-note-cancel');await click('reload');await until(()=>evaluate('current.revision===2&&!responseListBusy&&!rightsDirty'));
  await fill('response-train','100');await fill('response-validation','0');await fill('response-test','0');await click('response-preview');await until(()=>evaluate('!responseReleaseBusy&&!!responsePreview'));
  assert.equal(await evaluate('responsePreview.eligible'),false,'Original parent pairs remain stale');assert.equal(await answerPairs(),initialAnswers);
  await click('response-clear');await evaluate('document.querySelectorAll("#response-list input").forEach(box=>box.click())');await click('response-preview');await until(()=>evaluate('!responseReleaseBusy&&responsePreview?.eligible'));
  const freshAnswers=await answerPairs();await evaluate('document.getElementById("response-release-form").requestSubmit()');await until(()=>evaluate('!responseReleaseBusy&&!!document.querySelector("#response-release-result a")'));
  await evaluate('document.querySelector("#response-release-result a").click()');await until(()=>fs.readdirSync(downloads).filter(n=>n.endsWith('.zip')).length===1);
  const instruction=path.join(downloads,fs.readdirSync(downloads).find(n=>n.endsWith('.zip')));
  const consumerRun=spawnSync(process.env.INSTRUCTION_CONSUMER_PYTHON||'python3',['tests/check_instruction_consumer.py',instruction],{cwd:root,encoding:'utf8',timeout:120000});assert.equal(consumerRun.status,0,consumerRun.stdout+'\n'+consumerRun.stderr);
  const consumer=JSON.parse(consumerRun.stdout.trim().split('\n').at(-1));assert.equal(consumer.result,'PASS');assert.equal(consumer.examples,2);assert.equal(consumer.over_default_1024_tokens,true);
  fs.writeFileSync(path.join(report,'combined-instruction-downloaded.zip'),fs.readFileSync(instruction));
  console.log('Combined browser: explicit imported-label review, note, canonical download');
  await fill('query','');await evaluate('document.getElementById("filters").requestSubmit()');await until(()=>evaluate('page.total===3'));assert.equal(await answerPairs(),freshAnswers);
  const imported=drafts.find(row=>row.name.startsWith('Source'));assert.ok(imported);
  await evaluate(`Array.from(document.querySelectorAll('#records .record')).find(row=>row.querySelector('button').firstChild.textContent===${JSON.stringify(imported.name)}).querySelector('button').click()`);
  await until(()=>evaluate('current.id==='+JSON.stringify(imported.id)+'&&!responseListBusy'));
  await fill('record-review','human_reviewed');await evaluate('document.getElementById("editor").requestSubmit()');await until(()=>evaluate('!dirty&&current.review==="human_reviewed"&&!document.getElementById("editor").dataset.busy'));
  await fill('rights-note-value','Imported local note');await evaluate('document.getElementById("rights-note-form").requestSubmit()');await until(()=>evaluate('!rightsBusy&&!rightsDirty&&current.revision===3'));
  assert.equal(await evaluate('current.review'),'human_reviewed');assert.equal(await answerPairs(),freshAnswers);
  await click('clear-selection');await evaluate(`document.querySelector(${JSON.stringify('#records input[aria-label="Select '+imported.name+'"]')}).click()`);
  await fill('train','100');await fill('validation','0');await fill('test','0');await click('preview-release');await until(()=>evaluate('!document.getElementById("freeze-release").disabled'));
  await evaluate('document.getElementById("release-form").requestSubmit()');await until(()=>evaluate('!!document.querySelector("#release-result a")'));await evaluate('document.querySelector("#release-result a").click()');
  await until(()=>fs.readdirSync(downloads).filter(n=>n.endsWith('.zip')).length===2);const canonical=path.join(downloads,fs.readdirSync(downloads).filter(n=>n.endsWith('.zip')).find(n=>n!==path.basename(instruction)));
  python("import json,sys,zipfile; z=zipfile.ZipFile(sys.argv[1]);m=json.loads(z.read('manifest.json'));r=m['records'][0];assert len(m['records'])==1 and r['revision']==3 and r['review']=='human_reviewed';assert r['provenance']['rights_note_correction']['note']=='Imported local note';assert r['provenance']['acquisition']['declared']['upstream']['original_status']=='unavailable';assert z.read(r['asset'])==r['text'].encode()",canonical);
  fs.writeFileSync(path.join(report,'combined-canonical-downloaded.zip'),fs.readFileSync(canonical));
  await fill('selection-name','Combined imported record');await evaluate('document.getElementById("save-selection-form").requestSubmit()');await until(()=>evaluate('document.getElementById("saved-selection-status").textContent.startsWith("Saved “Combined imported record”")'));
  const savedId=await evaluate('document.getElementById("saved-selection").value'),savedPairs=await recordPairs();
  await click('clear-selection');await click('load-selection');await until(()=>evaluate('selected.size===1&&!savedLoadBusy'));assert.equal(await recordPairs(),savedPairs);
  const previousFrame=(await send('Page.getFrameTree')).frameTree.frame;
  await send('Page.reload');await until(()=>tracker.reloaded(previousFrame));
  await until(()=>evaluate(`document.getElementById('saved-selection')?.value===${JSON.stringify(savedId)}&&selected.size===1&&!savedLoadBusy`));assert.equal(await recordPairs(),savedPairs);
  await evaluate('history.back()');await until(()=>evaluate('selected.size===0'));await evaluate('history.forward()');await until(()=>evaluate('selected.size===1&&!savedLoadBusy'));assert.equal(await recordPairs(),savedPairs);
  assert.equal((await api('records')).total,3,'Navigation does not replay admissions');
  evidence.steps.push({stage:'both-real-downloads',consumer,canonical_revision:3,annotation_review_explicit:true,saved_pairs:savedPairs,reload_back_forward:true});await capture('03-frozen-selection','#saved-selection-panel');
  assert.deepEqual(errors,[]);evidence.result='PASS';fs.writeFileSync(path.join(report,'combined-session.json'),JSON.stringify(evidence,null,2)+'\n');
  console.log('Combined actual Chromium: held curation/rights results retain exact later answers; native Stop/lost-result lookup retains draft and fixed pairs; explicit reselection/review, both real downloads + unchanged pinned consumer, saved reload/back/forward and desktop/narrow passed.');
})().catch(async error=>{console.error(error);console.error('Runtime errors:',JSON.stringify(errors));if(inspect)try{console.error('Page diagnostics:',await inspect());}catch(diagnostic){console.error('Diagnostics failed:',diagnostic);}process.exitCode=1;}).finally(async()=>{if(ws)ws.close();for(const child of children)child.kill();await pause(200);fs.rmSync(temporary,{recursive:true,force:true});});
