// Real local HTTP and Chromium controls; no human corpus/training claim.
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {spawn,execFileSync}=require('node:child_process');
const {qaDirectory,screenshotOptions}=require('./qa_artifacts.cjs');
const {waitForDebugger}=require('./browser_startup.cjs'),{pageLoadTracker}=require('./browser_page_load.cjs');
const root=path.resolve(process.env.TULDOK_SOURCE_ROOT||path.join(__dirname,'..'));
const output=qaDirectory(root,'general-coco');
const scratch=fs.mkdtempSync(path.join(os.tmpdir(),'tuldok-coco-ui-')),children=[],errors=[],network=new Map(),tracker=pageLoadTracker();
const python=process.env.INSTRUCTION_CONSUMER_PYTHON||'python3',sha=raw=>crypto.createHash('sha256').update(raw).digest('hex');
const pause=ms=>new Promise(r=>setTimeout(r,ms));let ws,evaluate,uiAction='initial load',owner='first';
async function until(fn){for(let i=0;i<200;i++){if(await fn())return;await pause(75);}throw Error('Timed out');}
function launch(cmd,args,opts={}){const child=spawn(cmd,args,opts);children.push(child);return child;}
async function start(folder,empty=false){fs.mkdirSync(folder,{recursive:true});const child=launch(python,['-u','tests/browser_general_coco_server.py','--port','0','--data',path.join(folder,'data'),...(empty?['--empty']:[])],{cwd:root,stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',v=>stdout+=v);child.stderr.on('data',v=>stderr+=v);await until(()=>{if(child.exitCode!==null)throw Error(stderr);return /127\.0\.0\.1:(\d+)/.test(stdout);});return 'http://127.0.0.1:'+stdout.match(/127\.0\.0\.1:(\d+)/)[1];}
const pair=r=>({id:r.id,revision:r.revision,source_revision:r.source_revision});
(async()=>{
 const base=await start(path.join(scratch,'first')),secondBase=await start(path.join(scratch,'second'),true);
 const browser=launch(process.env.BROWSER||'/usr/bin/chromium',['--headless','--no-sandbox','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--window-size=1400,950','--user-data-dir='+path.join(scratch,'browser'),'about:blank'],{stdio:['ignore','ignore','pipe'],env:{...process.env,XDG_CONFIG_HOME:scratch,XDG_CACHE_HOME:scratch}});
 const port=await waitForDebugger(browser,path.join(scratch,'browser','DevToolsActivePort'));
 const tabs=await(await fetch('http://127.0.0.1:'+port+'/json')).json();ws=new WebSocket(tabs.find(t=>t.type==='page'&&t.url==='about:blank').webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
 let id=0;const pending=new Map();
 ws.onmessage=event=>{const message=JSON.parse(event.data);tracker.observe(message);if(message.id){const p=pending.get(message.id);pending.delete(message.id);message.error?p.reject(message.error):p.resolve(message.result);}
  if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails);
  if(message.method==='Network.requestWillBeSent'){const r=message.params.request,u=new URL(r.url);if(u.hostname==='127.0.0.1')network.set(message.params.requestId,{request_id:message.params.requestId,owner,method:r.method,path:u.pathname,ui_action:uiAction,role:r.method==='POST'&&!u.pathname.endsWith('/preview')&&!u.pathname.endsWith('/prepare')?'mutation':'observation',body_bytes:r.postData?Buffer.byteLength(r.postData):0,body_sha256:r.postData?sha(r.postData):null,status:null});}
  if(message.method==='Network.responseReceived'){const r=network.get(message.params.requestId);if(r)r.status=message.params.response.status;}
 };
 const send=(method,params={})=>new Promise((resolve,reject)=>{const request=++id,t=setTimeout(()=>{pending.delete(request);reject(Error('CDP timeout '+method));},15000);pending.set(request,{resolve:v=>{clearTimeout(t);resolve(v);},reject:e=>{clearTimeout(t);reject(e);}});ws.send(JSON.stringify({id:request,method,params}));});
 evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
 const click=id=>{uiAction='rendered click '+id;return evaluate('document.getElementById('+JSON.stringify(id)+').click()');};
 const fill=(id,value)=>evaluate(`(()=>{const e=document.getElementById(${JSON.stringify(id)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));})()`);
 const submit=id=>{uiAction='rendered submit '+id;return evaluate('document.getElementById('+JSON.stringify(id)+').requestSubmit()');};
 const get=async(base,path)=>(await(await fetch(base+'/api/workbench/'+path)).json());
 const pairs=()=>evaluate('([...selected.values()].map(({id,revision,source_revision})=>({id,revision,source_revision}))).sort((a,b)=>a.id.localeCompare(b.id))');
 const open=async row=>{uiAction='rendered open '+row.id;await evaluate('window.qaPreviousCurrent=current');await evaluate(`(()=>{const r=[...document.querySelectorAll('#records .record')].find(r=>r.querySelector('input')?.getAttribute('aria-label')===${JSON.stringify('Select '+row.name)});if(!r)throw Error('Row not rendered');r.querySelector('button').click();})()`);await until(()=>evaluate('current!==window.qaPreviousCurrent&&current?.id==='+JSON.stringify(row.id)+'&&!dirty&&!document.getElementById("editor").dataset.busy'));};
 const navigate=async url=>{const old=(await send('Page.getFrameTree')).frameTree.frame;await send('Page.navigate',{url});await until(()=>tracker.reloaded(old));await until(()=>evaluate('document.readyState==="complete"&&document.getElementById("notice")?.textContent==="Collection ready."'));};
 const importArchive=async raw=>{uiAction='rendered native ZIP input/submit';await evaluate(`(()=>{const dt=new DataTransfer();dt.items.add(new File([Uint8Array.from(atob(${JSON.stringify(raw.toString('base64'))}),c=>c.charCodeAt(0))],'native-coco.zip',{type:'application/zip'}));document.getElementById('native-detection-archive').files=dt.files;document.getElementById('native-detection-form').requestSubmit();})()`);await until(()=>evaluate('!detectionRunning&&document.getElementById("native-detection-status").textContent.includes("6 created")'));};
 const review=async row=>{await open(row);await fill('record-review','human_reviewed');await submit('editor');await until(()=>evaluate('!dirty&&current?.id==='+JSON.stringify(row.id)+'&&current.review==="human_reviewed"&&!document.getElementById("editor").dataset.busy'));};
 const selectAll=async()=>{await submit('filters');await until(()=>evaluate('!document.getElementById("filters").dataset.busy'));await click('clear-selection');uiAction='rendered detection checkboxes';await evaluate("for(const r of page.items.filter(r=>r.kind==='image'))document.querySelector('input[aria-label=\"Select '+r.name+'\"]')?.click()");assert.equal(await evaluate('selected.size'),6);};
 const saveOpenReload=async name=>{const expected=await pairs();await fill('selection-name',name);await submit('save-selection-form');await until(()=>evaluate('!document.getElementById("save-selection-form").dataset.busy&&document.getElementById("saved-selection-status").textContent.startsWith("Saved “")'));const savedId=await evaluate('document.getElementById("saved-selection").value');await click('clear-selection');await click('load-selection');await until(()=>evaluate('!savedLoadBusy&&selected.size===6'));assert.deepEqual(await pairs(),expected);const old=(await send('Page.getFrameTree')).frameTree.frame;await send('Page.reload');await until(()=>tracker.reloaded(old));await until(()=>evaluate('document.readyState==="complete"&&!savedLoadBusy&&selected.size===6&&document.getElementById("saved-selection-status").textContent.startsWith("Opened “")'));assert.deepEqual(await pairs(),expected);assert.equal(await evaluate('releasePreview'),null);return {id:savedId,pairs:expected};};
 const preview=async()=>{await click('preview-release');await until(()=>evaluate('!releaseBusy'));};
 const freeze=async(name,base,rows)=>{await preview();assert.equal(await evaluate('releasePreview.eligible'),true);const categories=await evaluate('releasePreview.coco_categories');await submit('release-form');await until(()=>evaluate('!releaseBusy&&!!document.querySelector("#release-result a")'));const url=await evaluate('document.querySelector("#release-result a").href');const response=await fetch(url);assert.equal(response.status,200);const raw=Buffer.from(await response.arrayBuffer()),archive=path.join(output,name+'.zip');fs.writeFileSync(archive,raw);assert.ok(url.includes(sha(raw)));const expected=path.join(output,name+'-expected-records.json');fs.writeFileSync(expected,JSON.stringify(rows,null,2)+'\n');execFileSync(python,['tests/check_general_coco.py','--archive',archive,'--expected',expected,'--output',path.join(output,name+'-reader')],{cwd:root,timeout:90000,stdio:'inherit'});return {url,sha256:sha(raw),categories,archive,raw};};
 await send('Page.enable');await send('Runtime.enable');await send('Network.enable');await send('Page.setLifecycleEventsEnabled',{enabled:true});await navigate(base+'/workbench');
 uiAction='rendered unrelated record';await evaluate('document.querySelector("#records .record button").click()');await until(()=>evaluate('!!current'));const unrelatedId=await evaluate('current.id');await fill('label','Unrelated dirty draft retained');
 const sourceRaw=fs.readFileSync(path.join(scratch,'first','native.zip'));await importArchive(sourceRaw);assert.equal(await evaluate('current.id'),unrelatedId);assert.equal(await evaluate('document.getElementById("label").value'),'Unrelated dirty draft retained');
 let rows=(await get(base,'records?')).items.filter(r=>r.kind==='image');assert.equal(rows.length,6);assert.ok(rows.every(r=>r.review==='draft'&&r.rights_note==='unknown'));
 await evaluate('window.qaPreviousCurrent=current');const discard=click('reload');await pause(100);await send('Page.handleJavaScriptDialog',{accept:true});await discard;await until(()=>evaluate('current!==window.qaPreviousCurrent&&!dirty&&!document.getElementById("reload").dataset.busy&&!document.getElementById("editor").dataset.busy'));
 const authored=rows.find(r=>r.annotation.boxes.length>0),boxes=JSON.parse(fs.readFileSync(path.join(scratch,'first','boxes.json')));
 await open(authored);
 for(const input of ['box-x','box-y','box-width','box-height'])assert.equal(await evaluate('document.getElementById('+JSON.stringify(input)+').step'),'any');
 while(await evaluate('targets.length'))await evaluate('document.querySelector("#targets button").click()');
 // A zero extent remains an owner-level rejection; no implicit clipping/drop.
 await fill('label','Object');await fill('box-width',0);await click('add-box');await submit('editor');await until(()=>evaluate('!document.getElementById("editor").dataset.busy&&document.getElementById("notice").textContent.includes("positive width and height")'));assert.equal((await get(base,'records/'+authored.id)).revision,authored.revision);await evaluate('document.querySelector("#targets button").click()');
 for(const box of boxes){await fill('label',box.label);for(const [key,value] of Object.entries(box).filter(([key])=>key!=='label'))await fill('box-'+key,value);await click('add-box');}
 assert.equal(await evaluate('document.getElementById("editor").checkValidity()'),true);assert.equal(await evaluate('document.getElementById("record-review").value'),'draft');
 await evaluate('document.getElementById("detection-controls").scrollIntoView()');fs.writeFileSync(path.join(output,'coco-authoring.jpg'),Buffer.from((await send('Page.captureScreenshot',screenshotOptions)).data,'base64'));
 await submit('editor');await until(()=>evaluate('!dirty&&current?.id==='+JSON.stringify(authored.id)+'&&current.review==="draft"&&!document.getElementById("editor").dataset.busy'));const savedDraft=await get(base,'records/'+authored.id);assert.deepEqual(savedDraft.annotation.boxes,boxes);
 await evaluate('window.qaPreviousCurrent=current');await click('reload');await until(()=>evaluate('current!==window.qaPreviousCurrent&&!dirty&&current?.id==='+JSON.stringify(authored.id)+'&&current.revision==='+savedDraft.revision+'&&!document.getElementById("reload").dataset.busy&&!document.getElementById("editor").dataset.busy'));assert.deepEqual(await evaluate('targets'),boxes);
 for(const row of rows)await review(row);
 rows=(await get(base,'records?')).items.filter(r=>r.kind==='image');assert.ok(rows.every(r=>r.review==='human_reviewed'&&r.rights_note==='unknown'));
 const negative=rows.find(r=>!r.annotation.boxes.length);await open(negative);assert.equal(await evaluate('targets.length'),0);
 await selectAll();const firstSet=await saveOpenReload('General COCO QA · exact multibox revisions');const saved=await get(base,'selections/'+firstSet.id);assert.equal(saved.current,true);assert.deepEqual(saved.selection.items.map(pair).sort((a,b)=>a.id.localeCompare(b.id)),firstSet.pairs);fs.writeFileSync(path.join(output,'first-fixed-selection.json'),JSON.stringify(saved,null,2)+'\n');
 await fill('release-format','image_detection_v1');await preview();assert.equal(await evaluate('releasePreview.eligible'),false);assert.ok((await evaluate('document.getElementById("release-preview").textContent')).includes('at most one box'));assert.equal(await evaluate('document.getElementById("freeze-release").disabled'),true);
 await fill('release-format','canonical_v1');assert.equal(await evaluate('document.getElementById("canonical-export-help").hidden'),false);assert.equal(await evaluate('document.getElementById("detection-export-help").hidden'),true);await preview();
 assert.equal(await evaluate('releasePreview.eligible'),true);const previewText=await evaluate('document.getElementById("release-preview").textContent');assert.ok(previewText.includes('"Object" → COCO category'));assert.ok(previewText.includes('"object" → COCO category'));assert.ok(previewText.includes('<img src=x onerror=alert(1)>'));assert.equal(await evaluate('document.querySelectorAll("#release-preview img,#release-preview script").length'),0);assert.deepEqual(await pairs(),firstSet.pairs);
 const first=await freeze('first-coco',base,rows);
 await evaluate('document.getElementById("release-form").scrollIntoView()');await until(()=>evaluate('document.getElementById("release-format").getBoundingClientRect().top>=0&&document.getElementById("release-format").getBoundingClientRect().bottom<innerHeight'));fs.writeFileSync(path.join(output,'coco-desktop.jpg'),Buffer.from((await send('Page.captureScreenshot',screenshotOptions)).data,'base64'));
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});await evaluate('document.getElementById("release-preview").scrollIntoView()');assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);fs.writeFileSync(path.join(output,'coco-narrow.jpg'),Buffer.from((await send('Page.captureScreenshot',screenshotOptions)).data,'base64'));
 const unselected=await get(base,'records/'+unrelatedId);assert.equal(unselected.review,'draft');assert.equal(unselected.annotation,null);
 // Second independent scratch owner prevents same-pixel duplicate skips.
 owner='second';await navigate(secondBase+'/workbench');await importArchive(first.raw);let imported=(await get(secondBase,'records?')).items;assert.equal(imported.length,6);assert.ok(imported.every(r=>r.review==='draft'&&r.rights_note==='unknown'));
 for(const row of imported){const acq=row.provenance.acquisition,up=acq.declared.upstream,before=rows.find(r=>r.id===up.record.id);assert.ok(before);assert.notEqual(row.id,before.id);assert.deepEqual(row.annotation,before.annotation);assert.equal(row.pixel_hash,before.pixel_hash);assert.equal(row.content_hash,before.content_hash);assert.equal(acq.archive_sha256,first.sha256);assert.deepEqual(up.category_table,first.categories);const mapping=new Map(first.categories.map(c=>[c.name,c.id]));assert.deepEqual(up.annotation_category_ids,before.annotation.boxes.map(b=>mapping.get(b.label)));await open(row);assert.ok((await evaluate('document.getElementById("record-provenance").textContent')).includes(first.sha256));await review(row);}
 imported=(await get(secondBase,'records?')).items;await selectAll();const secondSet=await saveOpenReload('Imported COCO QA · new IDs, exact revisions');const second=await freeze('roundtrip-coco',secondBase,imported);assert.deepEqual(second.categories,first.categories);
 const secondReport=JSON.parse(fs.readFileSync(path.join(output,'roundtrip-coco-reader','coco-reader-report.json')));assert.equal(secondReport.reader_records,6);assert.equal(secondReport.objects,12);
 const old=await fetch(first.url);assert.deepEqual(Buffer.from(await old.arrayBuffer()),first.raw);
 // A later local annotation change invalidates the held canonical pairs and saved set.
 const staleRow=imported.find(r=>r.annotation.boxes.length>0);await open(staleRow);await evaluate('document.querySelector("#targets button").click()');await submit('editor');await until(()=>evaluate('!dirty&&current?.id==='+JSON.stringify(staleRow.id)+'&&current.revision>'+staleRow.revision+'&&current.review==="draft"&&!document.getElementById("editor").dataset.busy'));
 assert.equal((await get(secondBase,'selections/'+secondSet.id)).current,false);await click('clear-selection');await click('load-selection');await until(()=>evaluate('!savedLoadBusy&&selected.size===6'));assert.deepEqual(await pairs(),secondSet.pairs);await preview();assert.equal(await evaluate('releasePreview.eligible'),false);assert.equal(await evaluate('document.getElementById("freeze-release").disabled'),true);assert.equal((await get(secondBase,'selections/'+secondSet.id)).current,false);
 assert.deepEqual(Buffer.from(await(await fetch(second.url)).arrayBuffer()),second.raw);assert.deepEqual(Buffer.from(await(await fetch(first.url)).arrayBuffer()),first.raw);assert.deepEqual(errors,[]);
 const snapshot=JSON.parse(execFileSync(python,['-c','import json;from scripts.qualify_text_classification_local import source_snapshot;print(json.dumps(source_snapshot()))'],{cwd:root,encoding:'utf8'}));
 const ledger=[...network.values()];assert.equal(ledger.filter(r=>r.path==='/api/workbench/releases'&&r.status===201).length,2);
 fs.writeFileSync(path.join(output,'session.json'),JSON.stringify({result:'PASS',candidate_head:snapshot.head,candidate_tree:execFileSync('git',['write-tree'],{cwd:root,encoding:'utf8'}).trim(),source_snapshot_sha256:snapshot.sha256,basis:'Retained authored PNG pixels and automated QA annotations/review; not genuine human labels or independent physical data.',source_archive_sha256:sha(sourceRaw),first:{url:first.url,sha256:first.sha256,categories:first.categories,fixed_set:firstSet},roundtrip:{url:second.url,sha256:second.sha256,categories:second.categories,fixed_set:secondSet},first_records:rows,imported_records:imported,initial_native_drafts_unknown_rights:true,new_scratch_owner_no_duplicate_skips:true,rendered_multiple_same_label_boxes_and_case_unicode:true,rendered_fractional_subpixel_controls:true,zero_extent_HTTP400_preserved_revision:true,separate_draft_save_reload_review:true,fresh_document_owner_navigation:true,post_freeze_canonical_stale_pairs_refused:true,frozen_exports_immutable_after_edit:true,Chapter9_multibox_refusal:true,unselected_unrelated_draft:{id:unrelatedId,review:unselected.review},network:ledger,network_scope:'Browser CDP requests for both owners; Node archive/record verification reads are separate and read-only.',mutating_requests:ledger.filter(r=>r.role==='mutation').length,errors,training_executed:false,UI_provisional:true},null,2)+'\n');
 console.log('General COCO browser: rendered fractional/multi-box/case-Unicode review, fixed-set reload, exact canonical freeze, real readers and separate-owner native review/export roundtrip passed.');
})().catch(async error=>{console.error(error);if(evaluate)try{console.error(await evaluate('document.body.innerText.slice(-9000)'));}catch{}process.exitCode=1;}).finally(async()=>{if(ws)ws.close();for(const c of children)c.kill();await pause(200);fs.rmSync(scratch,{recursive:true,force:true});});
