// Actual authored PLY files; real loopback HTTP and Chromium, JPEG85 output only.
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {spawn,spawnSync,execFileSync}=require('node:child_process');
const {qaDirectory,screenshotOptions}=require('./qa_artifacts.cjs');
const {pageLoadTracker}=require('./browser_page_load.cjs');
const root=path.resolve(process.env.TULDOK_SOURCE_ROOT||path.join(__dirname,'..')),report=qaDirectory(root,'static-mesh'),temporary=fs.mkdtempSync(path.join(os.tmpdir(),'tuldok-mesh-')),children=[];
const python=process.env.MESH_CONSUMER_PYTHON||process.env.POINTCLOUD_CONSUMER_PYTHON||process.env.INSTRUCTION_CONSUMER_PYTHON||'python3',sha=raw=>crypto.createHash('sha256').update(raw).digest('hex');
const downloads=[],network=new Map();let owner='first';
const errors=[],tracker=pageLoadTracker(),pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));let ws;
async function until(fn){for(let i=0;i<150;i++){const result=await fn();if(result)return result;await pause(100);}throw Error('Timed out');}
function launch(command,args,options={}){const child=spawn(command,args,options);children.push(child);return child;}
(async()=>{
  const fixture=path.join(root,'tests/fixtures/meshes');
  const ply=fs.readFileSync(path.join(fixture,'tetrahedron.ply')),sidecar=fs.readFileSync(path.join(fixture,'tetrahedron.json'));
  const server=launch(python,['-u','app.py','--port','0','--data',path.join(temporary,'data')],{cwd:root,stdio:['ignore','pipe','pipe']});
  let output='',serverErrors='';let secondErrors='';server.stdout.on('data',chunk=>output+=chunk);server.stderr.on('data',chunk=>serverErrors+=chunk);
  const port=await until(()=>output.match(/127\.0\.0\.1:(\d+)/)?.[1]),base='http://127.0.0.1:'+port;
  const recordSnapshots=new Map();
  const apiAt=async(origin,route,body)=>{const response=await fetch(origin+'/api/workbench/'+route,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const raw=await response.text(),result=JSON.parse(raw);assert.ok(response.ok,JSON.stringify(result));if(/^records\/[a-f0-9]{32}$/.test(route))recordSnapshots.set(origin+':'+result.id,{raw,row:result});return result;};
  const api=(route,body)=>apiAt(base,route,body);
  const seed=await api('import',{kind:'text',text:'Independent editor stays intact.',name:'Existing editor',groups:['existing-source'],rights:'Authored'});
  launch(process.env.BROWSER||'/usr/bin/chromium',['--headless','--no-sandbox','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--window-size=1400,950','--user-data-dir='+path.join(temporary,'browser'),'about:blank'],{stdio:['ignore','ignore','ignore'],env:{...process.env,XDG_CONFIG_HOME:temporary,XDG_CACHE_HOME:temporary}});
  const active=path.join(temporary,'browser','DevToolsActivePort'),debugPort=await until(()=>fs.existsSync(active)&&fs.readFileSync(active,'utf8').split('\n')[0]);
  const tabs=await(await fetch('http://127.0.0.1:'+debugPort+'/json')).json(),target=tabs.find(tab=>tab.type==='page'&&tab.url==='about:blank');
  assert.ok(target);ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
  let id=0;const pending=new Map();
  const send=(method,params={})=>new Promise((resolve,reject)=>{const key=++id,timer=setTimeout(()=>{pending.delete(key);reject(Error('CDP timeout '+method));},20000);pending.set(key,{resolve:value=>{clearTimeout(timer);resolve(value);},reject:error=>{clearTimeout(timer);reject(error);}});ws.send(JSON.stringify({id:key,method,params}));});
  ws.onmessage=event=>{const message=JSON.parse(event.data);tracker.observe(message);if(message.id){const task=pending.get(message.id);if(!task)return;pending.delete(message.id);message.error?task.reject(message.error):task.resolve(message.result);}if(message.method==='Browser.downloadWillBegin'||message.method==='Browser.downloadProgress')downloads.push({method:message.method,params:message.params,owner});
    if(message.method==='Network.requestWillBeSent'){const request=message.params.request,url=new URL(request.url);if(url.hostname==='127.0.0.1')network.set(message.params.requestId,{owner,method:request.method,path:url.pathname,body_sha256:request.postData?sha(request.postData):null,status:null});}
    if(message.method==='Network.responseReceived'){const request=network.get(message.params.requestId);if(request)request.status=message.params.response.status;}
    if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails);if(message.method==='Page.javascriptDialogOpening')send('Page.handleJavaScriptDialog',{accept:true}).catch(error=>errors.push(String(error)));};
  const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));return result.result.value;};
  const fill=(id,value)=>evaluate(`(()=>{const e=document.getElementById(${JSON.stringify(id)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  const choose=(id,name,raw)=>evaluate(`(()=>{const raw=Uint8Array.from(atob(${JSON.stringify(raw.toString('base64'))}),c=>c.charCodeAt(0)),dt=new DataTransfer();dt.items.add(new File([raw],${JSON.stringify(name)}));document.getElementById(${JSON.stringify(id)}).files=dt.files;})()`);
  const open=async row=>{await evaluate('window.qaPreviousCurrent=current');await evaluate(`(()=>{const item=[...document.querySelectorAll('#records .record')].find(item=>item.querySelector('input')?.getAttribute('aria-label')===${JSON.stringify('Select '+row.name)});if(!item)throw Error('Expected mesh source not rendered');item.querySelector('button').click();})()`);await until(()=>evaluate('current!==qaPreviousCurrent&&current?.id==='+JSON.stringify(row.id)+'&&!dirty&&!document.getElementById("editor").dataset.busy'));};
  const save=async()=>{await evaluate('document.getElementById("editor").requestSubmit()');await until(()=>evaluate('!document.getElementById("editor").dataset.busy'));assert.equal(await evaluate('dirty'),false);};
  const reload=async()=>{await evaluate('window.qaPreviousCurrent=current');await evaluate('document.getElementById("reload").click()');await until(()=>evaluate('current!==qaPreviousCurrent&&!dirty&&!document.getElementById("reload").dataset.busy'));};
  const clearSelection=async()=>{await evaluate('document.getElementById("clear-selection").click()');await until(()=>evaluate('!document.getElementById("clear-selection").dataset.busy&&selected.size===0'));};
  const download=async(selector,name)=>{const url=await evaluate('document.querySelector('+JSON.stringify(selector)+').href'),folder=path.join(report,'downloads',name);fs.mkdirSync(folder,{recursive:true});await send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:folder,eventsEnabled:true});await evaluate('document.querySelector('+JSON.stringify(selector)+').click()');await until(()=>downloads.some(event=>event.method==='Browser.downloadWillBegin'&&event.params.url===url));const started=downloads.findLast(event=>event.method==='Browser.downloadWillBegin'&&event.params.url===url);await until(()=>downloads.some(event=>event.method==='Browser.downloadProgress'&&event.params.guid===started.params.guid&&event.params.state==='completed'));const archive=path.join(folder,started.params.suggestedFilename);return {url,archive,bytes:fs.statSync(archive).size,sha256:sha(fs.readFileSync(archive)),guid:started.params.guid};};
  const importPair=async(name,raw,sidecar)=>{await evaluate('document.getElementById("mesh-import-panel").open=true');await choose('mesh-ply','mesh.ply',raw);await choose('mesh-manifest','mesh.json',sidecar);await fill('mesh-name',name);await evaluate('document.getElementById("mesh-import-form").requestSubmit()');await until(()=>evaluate('!meshImportBusy'));assert.match(await evaluate('document.getElementById("mesh-import-status").textContent'),/unreviewed/);};
  const review=async(row,localRights=false)=>{await open(row);await fill('mesh-note',row.annotation?.note||'Authored native mesh draft inspection; no simulation/training qualification.');await fill('record-review','draft');await save();await reload();assert.equal(await evaluate('current.review'),'draft');if(localRights){await fill('rights-note-value','Second owner local authored mesh QA rights note');await evaluate('document.getElementById("rights-note-form").requestSubmit()');await until(()=>evaluate('!rightsBusy&&!rightsDirty'));assert.equal(await evaluate('current.provenance.rights'),'unknown');assert.equal(await evaluate('current.review'),'draft');}await fill('record-review','human_reviewed');await save();};
  const verifyConsumer=(file,rows,folder)=>{
    const reportPath=path.join(folder,'report.json'),result=JSON.parse(fs.readFileSync(reportPath));
    assert.equal(result.status,'PASS');assert.equal(result.packet_origin,'actual_browser_or_supplied_owner_release');assert.equal(result.release_sha256,file.sha256);assert.equal(result.records,rows.length);assert.equal(result.first.release.sha256,file.sha256);assert.equal(result.first.release.bytes,file.bytes);
    assert.deepEqual(result.samples.map(sample=>sample.id).sort(),rows.map(row=>row.id).sort());
    const verifyFile=identity=>{const relative=path.relative(folder,identity.path);assert.ok(relative&&!relative.startsWith('..')&&!path.isAbsolute(relative));const raw=fs.readFileSync(identity.path);assert.equal(raw.length,identity.bytes);assert.equal(sha(raw),identity.sha256);return raw;};
    for(const sample of result.samples){
      const original=rows.find(row=>row.id===sample.id),metadata=sample.metadata;
      for(const [key,value] of Object.entries(original))assert.deepEqual(metadata.record[key],value,'Original browser owner record '+key);
      assert.equal(metadata.schema,'native_mesh_sample_v1');assert.equal(metadata.release_sha256,file.sha256);assert.equal(metadata.split,sample.split);assert.equal(metadata.record.split,sample.split);assert.match(metadata.record.export_group,/^component:[a-f0-9]{64}$/);
      assert.deepEqual(metadata.array_axes,{vertex_properties:['vertex'],vertex_indices:['triangle','corner']});assert.equal(metadata.units,original.mesh.manifest.units);assert.deepEqual(metadata.coordinate_system,original.mesh.manifest.coordinate_system);assert.equal(metadata.declared_family_context.length,result.declared_context_members);assert.ok(metadata.declared_family_context.some(row=>row.id===original.id&&row.revision===original.revision&&row.content_hash===original.content_hash));
      const schema=original.mesh.properties.map(property=>({name:property.name,shape:[original.mesh.vertex_count],dtype:{float:'<f4',double:'<f8'}[property.dtype]}));schema.push({name:'vertex_indices',shape:[original.mesh.triangle_count,3],dtype:'<i4'});
      assert.deepEqual(sample.attributes.map(({name,shape,dtype})=>({name,shape,dtype})),schema);assert.deepEqual(metadata.properties,schema);
      assert.equal(sample.actual_binary_read.status,'PASS');assert.equal(sample.external_writer_reader.status,'PASS');assert.deepEqual(sample.actual_binary_read.attributes,sample.attributes);assert.deepEqual(sample.external_writer_reader.attributes,sample.attributes);
      const derived=verifyFile(sample.derived_ply.file);assert.ok(derived.subarray(0,80).toString().startsWith('ply\nformat binary_little_endian 1.0\n'));assert.equal(sample.derived_ply.source_byte_identical,false);assert.equal(sample.derived_ply.source_geometry_sha256,original.mesh.manifest.geometry_sha256);assert.equal(sample.derived_ply.original_sidecar_sha256,original.mesh.manifest_sha256);assert.equal(metadata.derivation.format,'binary_little_endian PLY 1.0');assert.equal(metadata.derivation.sha256,sample.derived_ply.file.sha256);assert.equal(metadata.derivation.record_id,original.id);assert.equal(metadata.derivation.release_sha256,file.sha256);assert.equal(sha(Buffer.from(metadata.derivation.original_mesh_json_base64,'base64')),original.mesh.manifest_sha256);
      assert.equal(sample.actual_binary_read.file.sha256,sample.derived_ply.file.sha256);verifyFile(sample.external_writer_roundtrip.file);const npz=verifyFile(sample.npz);assert.ok(npz.length>0&&npz.length<=16*1024*1024);
      if(original.name==='Authored mixed-native midpoint triangle'){assert.ok(sample.attributes.find(attribute=>attribute.name==='x').native_hex.startsWith('0100803f'));assert.ok(sample.attributes.find(attribute=>attribute.name==='ny').native_hex.startsWith('0100803f'));assert.deepEqual(sample.attributes.find(attribute=>attribute.name==='nz').values,[2,2,2]);assert.deepEqual(sample.attributes.find(attribute=>attribute.name==='vertex_indices').values,[[0,2,1]]);}
    }
    return {output:folder,report_identity:{path:reportPath,bytes:fs.statSync(reportPath).size,sha256:sha(fs.readFileSync(reportPath))},report:result};
  };
  const freeze=async(origin,name,rows)=>{await clearSelection();for(const row of rows)await evaluate('document.querySelector('+JSON.stringify('input[aria-label="Select '+row.name+'"]')+').click()');assert.equal(await evaluate('selected.size'),rows.length);await fill('train',50);await fill('validation',50);await fill('test',0);await evaluate('document.getElementById("preview-release").click()');await until(()=>evaluate('!releaseBusy'));assert.equal(await evaluate('releasePreview.eligible'),true);assert.match(await evaluate('document.getElementById("release-preview").textContent'),/Static mesh assets/);await evaluate('document.getElementById("release-form").requestSubmit()');await until(()=>evaluate('!releaseBusy&&!!document.querySelector("#release-result a")'));const file=await download('#release-result a',name);assert.ok(file.url.includes(file.sha256));assert.equal((await fetch(file.url)).status,200);const expected=path.join(report,name+'-expected.json');const rawRows=rows.map(row=>{const captured=recordSnapshots.get(origin+':'+row.id);assert.ok(captured);assert.deepEqual(captured.row,row);return captured.raw;});fs.writeFileSync(expected,'[\n'+rawRows.join(',\n')+'\n]\n');const output=path.join(report,name+'-native-consumer');execFileSync(python,['tests/check_native_mesh_consumer.py','--release',file.archive,'--expected-rows',expected,'--output',output],{cwd:root,stdio:'inherit',timeout:90000});file.native_consumer=verifyConsumer(file,rows,output);return file;};
  await send('Page.enable');await send('Page.setLifecycleEventsEnabled',{enabled:true});await send('Runtime.enable');await send('Network.enable');
  await send('Page.navigate',{url:base+'/workbench'});await until(()=>evaluate('document.getElementById("notice")?.textContent==="Collection ready."'));
  await evaluate('openRecord('+JSON.stringify(seed.id)+')');await fill('label','retain unsaved target');
  await evaluate('document.querySelector(".record input").click();document.getElementById("mesh-import-panel").open=true');
  await choose('mesh-ply','mesh.ply',ply);await choose('mesh-manifest','mesh.json',sidecar);await fill('mesh-name','Authored tetrahedron');
  await evaluate(`(()=>{const original=window.fetch;window.meshPosts=0;window.holdMesh=true;window.fetch=async(...args)=>{if(String(args[0]).endsWith('/mesh-import')){window.meshPosts++;const response=await original(...args);if(window.holdMesh){window.holdMesh=false;await new Promise(resolve=>window.releaseMesh=resolve);}return response;}return original(...args);};})()`);
  await evaluate('document.getElementById("mesh-import-form").requestSubmit()');await until(()=>evaluate('!!window.releaseMesh'));
  await evaluate('document.getElementById("mesh-import-form").requestSubmit()');assert.equal(await evaluate('meshPosts'),1);
  await evaluate('window.releaseMesh()');await until(()=>evaluate('!meshImportBusy'));
  assert.match(await evaluate('document.getElementById("mesh-import-status").textContent'),/4 vertices, 4 triangles, unreviewed/);
  assert.equal(await evaluate('current.id'),seed.id);assert.equal(await evaluate('dirty'),true);assert.equal(await evaluate('selected.size'),1);assert.equal(await evaluate('document.getElementById("label").value'),'retain unsaved target');
  const row=(await api('records?kind=mesh')).items[0];assert.equal(row.review,'draft');assert.equal(row.annotation,null);
  await choose('mesh-ply','mesh.ply',Buffer.from(ply.toString().replace('0 0 0','bad!!')));
  await evaluate('document.getElementById("mesh-import-form").requestSubmit()');await until(()=>evaluate('!meshImportBusy'));
  assert.match(await evaluate('document.getElementById("mesh-import-status").textContent'),/SHA256 mismatch/);
  await choose('mesh-ply','wrong.ply',ply);await evaluate('document.getElementById("mesh-import-form").requestSubmit()');await until(()=>evaluate('!meshImportBusy'));
  assert.match(await evaluate('document.getElementById("mesh-import-status").textContent'),/Choose mesh.ply/);assert.equal((await api('records?kind=mesh')).total,1);
  await evaluate('dirty=false');await evaluate('openRecord('+JSON.stringify(row.id)+')');
  await until(()=>evaluate('document.querySelectorAll("#mesh-projections polygon").length===12'));
  assert.equal(await evaluate('document.getElementById("task").value'),'mesh_geometry');assert.match(await evaluate('document.getElementById("mesh-preview-status").textContent'),/right-handed, z up/);
  assert.equal(await evaluate('document.querySelectorAll("#mesh-projections svg[role=img]").length'),3);assert.match(await evaluate('document.getElementById("mesh-metadata").textContent'),/fixture-world/);
  // Completed-but-delayed inspection cannot replace another record or a later same-ID editor.
  await evaluate(`(()=>{const original=window.fetch;window.holdInspection=true;window.fetch=async(...args)=>{const response=await original(...args);if(String(args[0]).includes('/mesh-inspection/')&&window.holdInspection){window.holdInspection=false;await new Promise(resolve=>window.releaseInspection=resolve);}return response;};})()`);
  await evaluate('openRecord('+JSON.stringify(row.id)+')');await until(()=>evaluate('!!window.releaseInspection'));
  await evaluate('openRecord('+JSON.stringify(seed.id)+')');assert.equal(await evaluate('document.getElementById("mesh-inspection").hidden'),true);
  await evaluate('openRecord('+JSON.stringify(row.id)+')');await until(()=>evaluate('document.querySelectorAll("#mesh-projections polygon").length===12'));
  await fill('mesh-note','Unsaved inspection note survives old preview');await evaluate('window.releaseInspection()');await pause(250);
  assert.equal(await evaluate('document.getElementById("mesh-note").value'),'Unsaved inspection note survives old preview');assert.equal(await evaluate('dirty'),true);
  assert.equal(await evaluate('document.querySelectorAll("#mesh-projections polygon").length'),12);
  const draftPreview=await api('releases/preview',{items:[{id:row.id,revision:1,source_revision:1}],ratios:{train:100,validation:0,test:0},seed:4});assert.equal(draftPreview.eligible,false);
  // Native keyboard activation submits the real review form.
  await fill('record-review','human_reviewed');
  await evaluate('document.querySelector("#editor button:not([type=button])").focus()');
  await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,text:'\r'});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});
  try {await until(()=>evaluate('current.review==="human_reviewed"&&!dirty&&current.revision===2'));} catch(error) {console.error(await evaluate('({review:current.review,revision:current.revision,dirty,notice:document.getElementById("notice").textContent,valid:document.getElementById("editor").checkValidity(),focused:document.activeElement.id})'));throw error;}
  assert.equal((await api('history/'+row.id)).length,2);
  const asset=await fetch(base+'/api/workbench/asset/'+row.id);assert.equal(asset.headers.get('content-type'),'application/zip');
  fs.writeFileSync(path.join(temporary,'download.zip'),Buffer.from(await asset.arrayBuffer()));
  const check=spawnSync(python,['-c',"import sys,zipfile;from pathlib import Path;p=Path(sys.argv[1]);f=Path(sys.argv[2]);z=zipfile.ZipFile(p/'download.zip');assert z.read('mesh.ply')==(f/'tetrahedron.ply').read_bytes();assert z.read('mesh.json')==(f/'tetrahedron.json').read_bytes()",temporary,fixture],{cwd:root,encoding:'utf8'});assert.equal(check.status,0,check.stderr);
  const rawDownload=await download('#mesh-download','original-tetrahedron-pair');
  execFileSync(python,['-c',"import sys,zipfile;from pathlib import Path;a=zipfile.ZipFile(sys.argv[1]);f=Path(sys.argv[2]);assert a.read('mesh.ply')==(f/'tetrahedron.ply').read_bytes();assert a.read('mesh.json')==(f/'tetrahedron.json').read_bytes()",rawDownload.archive,fixture],{cwd:root});
  const midpoint=JSON.parse(execFileSync(python,['-c',"import sys,json,base64;sys.path.insert(0,'tests/fixtures');from native_mesh_fixture import pair;raw,sidecar=pair();print(json.dumps({'mesh.ply':base64.b64encode(raw).decode(),'mesh.json':base64.b64encode(sidecar).decode()}))"],{cwd:root,encoding:'utf8'}));
  await importPair('Authored mixed-native midpoint triangle',Buffer.from(midpoint['mesh.ply'],'base64'),Buffer.from(midpoint['mesh.json'],'base64'));const midpointRow=(await api('records?kind=mesh')).items.find(item=>item.name==='Authored mixed-native midpoint triangle');assert.equal(midpointRow.review,'draft');assert.equal(midpointRow.provenance.rights,'unknown');
  await review(await api('records/'+row.id));await review(midpointRow);const sourceRows=await Promise.all([row,midpointRow].map(item=>api('records/'+item.id)));
  const first=await freeze(base,'first-meshes',sourceRows),firstBytes=fs.readFileSync(first.archive);
  const priorFrame=(await send('Page.getFrameTree')).frameTree.frame;await send('Page.reload');await until(()=>tracker.reloaded(priorFrame));await until(()=>evaluate('document.readyState==="complete"&&document.getElementById("notice")?.textContent==="Collection ready."'));await open(row);await until(()=>evaluate('document.querySelectorAll("#mesh-projections polygon").length===12'));
  assert.equal(await evaluate('current.review'),'human_reviewed');assert.equal(await evaluate('document.getElementById("mesh-note").value'),'Unsaved inspection note survives old preview');
  await evaluate('document.getElementById("mesh-inspection").scrollIntoView()');fs.writeFileSync(path.join(report,'mesh-desktop.jpg'),Buffer.from((await send('Page.captureScreenshot',screenshotOptions)).data,'base64'));
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});await evaluate('document.getElementById("mesh-inspection").scrollIntoView()');
  assert.ok(await evaluate('document.documentElement.scrollWidth<=innerWidth'),'Mesh inspector fits narrow viewport');
  assert.ok(await evaluate('[...document.querySelectorAll("#mesh-projections polygon")].every(p=>!p.getAttribute("points").includes("NaN")&&!p.getAttribute("points").includes("Infinity"))'));
  fs.writeFileSync(path.join(report,'mesh-narrow.jpg'),Buffer.from((await send('Page.captureScreenshot',screenshotOptions)).data,'base64'));
  await send('Emulation.clearDeviceMetricsOverride');
  const secondServer=launch(python,['-u','app.py','--port','0','--data',path.join(temporary,'second-owner')],{cwd:root,stdio:['ignore','pipe','pipe']});let secondOutput='';secondServer.stdout.on('data',chunk=>secondOutput+=chunk);secondServer.stderr.on('data',chunk=>secondErrors+=chunk);const secondPort=await until(()=>secondOutput.match(/127\.0\.0\.1:(\d+)/)?.[1]),secondBase='http://127.0.0.1:'+secondPort;
  const pairs=path.join(report,'browser-source-raw-pairs');execFileSync(python,['-c',"import sys,json,zipfile,io;from pathlib import Path;a=zipfile.ZipFile(sys.argv[1]);out=Path(sys.argv[2]);rows=json.loads(a.read('manifest.json'))['records'];[(out/r['id']).mkdir(parents=True,exist_ok=True) for r in rows];[(out/r['id']/name).write_bytes(zipfile.ZipFile(io.BytesIO(a.read(r['asset']))).read(name)) for r in rows for name in ('mesh.ply','mesh.json')]",first.archive,pairs],{cwd:root});
  owner='second';const oldFrame=(await send('Page.getFrameTree')).frameTree.frame;await send('Page.navigate',{url:secondBase+'/workbench'});await until(()=>tracker.reloaded(oldFrame));await until(()=>evaluate('document.readyState==="complete"&&document.getElementById("notice")?.textContent==="Collection ready."'));
  const localRows=[];for(const original of sourceRows){const folder=path.join(pairs,original.id);await importPair(original.name,fs.readFileSync(path.join(folder,'mesh.ply')),fs.readFileSync(path.join(folder,'mesh.json')));const local=(await apiAt(secondBase,'records?kind=mesh')).items.find(item=>item.name===original.name);assert.notEqual(local.id,original.id);assert.equal(local.review,'draft');assert.equal(local.annotation,null);assert.equal(local.provenance.rights,'unknown');assert.equal(local.content_hash,original.content_hash);assert.deepEqual(local.mesh,original.mesh);localRows.push(local);}
  for(const local of localRows)await review(local,true);const secondRows=await Promise.all(localRows.map(local=>apiAt(secondBase,'records/'+local.id)));const second=await freeze(secondBase,'second-meshes',secondRows),secondBytes=fs.readFileSync(second.archive);
  for(const source of first.native_consumer.report.samples){const local=second.native_consumer.report.samples.find(sample=>sample.metadata.record.name===source.metadata.record.name);assert.notEqual(local.id,source.id);assert.deepEqual(local.attributes,source.attributes);assert.deepEqual(local.metadata.record.mesh,source.metadata.record.mesh);assert.equal(local.metadata.record.provenance.rights,'unknown');assert.ok(local.metadata.record.provenance.rights_note_correction?.note);}
  await open(secondRows[0]);await evaluate('document.getElementById("record-provenance").scrollIntoView()');fs.writeFileSync(path.join(report,'mesh-second-owner-provenance.jpg'),Buffer.from((await send('Page.captureScreenshot',screenshotOptions)).data,'base64'));await fill('mesh-note','Later local draft after frozen mesh export');await save();assert.equal(await evaluate('current.review'),'draft');await evaluate('document.getElementById("preview-release").click()');await until(()=>evaluate('!releaseBusy'));assert.equal(await evaluate('releasePreview.eligible'),false);assert.deepEqual(fs.readFileSync(first.archive),firstBytes);assert.deepEqual(fs.readFileSync(second.archive),secondBytes);for(const file of [first,second])assert.equal(sha(Buffer.from(await(await fetch(file.url)).arrayBuffer())),file.sha256);
  const completedGUIDs=[...new Set(downloads.filter(event=>event.method==='Browser.downloadProgress'&&event.params.state==='completed').map(event=>event.params.guid))];assert.deepEqual(completedGUIDs.sort(),[rawDownload.guid,first.guid,second.guid].sort());assert.equal(completedGUIDs.length,3);
  const snapshot=JSON.parse(execFileSync(python,['-c','import json;from scripts.qualify_text_classification_local import source_snapshot;print(json.dumps(source_snapshot()))'],{cwd:root,encoding:'utf8'}));
  fs.writeFileSync(path.join(report,'mesh-ui-report.json'),JSON.stringify({status:'PASS',candidate_head:snapshot.head,source_snapshot_sha256:snapshot.sha256,source_records:sourceRows,second_browser_owner_records:secondRows,raw_download:rawDownload,first_release:first,second_release:second,download_events:downloads,completed_chromium_guids:completedGUIDs,network:[...network.values()],scope:'Authored tiny analytic transport/control QA and simulated review; no scanned corpus, geometry/model quality, simulation or training claim.',browser_download_scope:'Exactly one original ASCII tetrahedron pair and two actual browser-owned canonical mesh releases. Consumer-derived NPZ/binary PLY are local files, never claimed as Chromium downloads.',transfer_scope:'Second actual browser owner imports original ASCII pairs extracted from first actual Chromium release, then separately drafts/reopens/corrects local rights/reviews/freezes. Raw pairs preserve native source bytes/metadata; sender-local assignments or extra relationships do not transfer. Checker-created secondary owners are private reader QA, distinct from both browser owners.',preserved_all_prior_UI_regressions:true,actual_native_dataset_npz_and_binary_PLY_both_browser_owners:true,midpoint_literal_native_bits_mixed_dtypes_nonunit_normals_ordered_triangles:true,separate_draft_reopen_review_second_browser_owner:true,old_both_frozen_files_and_URL_bytes_unchanged:true,no_models_training_or_simulation:true,errors},null,2)+'\n');
  assert.deepEqual(errors,[]);assert.ok(!serverErrors.includes('Traceback'),serverErrors);assert.ok(!secondErrors.includes('Traceback'),secondErrors);
  console.log('Mesh Chromium: authored real PLY import/inspection/native projections, hash/name rejection, duplicate-submit fencing, dirty editor/selection and stale same-ID preview ownership, keyboard human review/history, exact raw download, reviewed whole-mesh release/reload/narrow JPEG85, three actual Chromium downloads, second browser-owner drafts/rights/reviews and native NPZ/binary PLY passed.');
})().catch(error=>{console.error(error);console.error('Runtime errors:',JSON.stringify(errors));process.exitCode=1;}).finally(async()=>{if(ws)ws.close();for(const child of children)child.kill();await pause(250);for(const child of children)if(child.exitCode===null&&child.signalCode===null)child.kill('SIGKILL');fs.rmSync(temporary,{recursive:true,force:true});});
