// Native browser smoke test. No npm dependencies.
const {qaDirectory,screenshotOptions}=require('./qa_artifacts.cjs');
const assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {spawn}=require('node:child_process');
const root=path.resolve(__dirname,'..'),temporary=fs.mkdtempSync(path.join(os.tmpdir(),'tuldok-preview-browser-')),children=[];
let ws, inspect;
const errors=[];
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function until(fn){for(let i=0;i<150;i++){const value=await fn();if(value)return value;await pause(100);}throw Error('Timed out');}
function launch(command,args,options={}){const child=spawn(command,args,options);children.push(child);return child;}
(async()=>{
  const server=launch('python3',['-u','tests/browser_server.py','--port','0','--data',path.join(temporary,'data')],{cwd:root,stdio:['ignore','pipe','pipe']});
  let output='',stderr='';server.stdout.on('data',data=>output+=data);server.stderr.on('data',data=>stderr+=data);
  const port=await until(()=>output.match(/127\.0\.0\.1:(\d+)/)?.[1]);
  launch(process.env.BROWSER||'/usr/bin/chromium',['--headless','--no-sandbox','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--window-size=1400,950','--user-data-dir='+path.join(temporary,'browser'),'about:blank'],{stdio:['ignore','ignore','inherit'],env:{...process.env,HOME:temporary,XDG_CONFIG_HOME:temporary,XDG_CACHE_HOME:temporary}});
  const active=path.join(temporary,'browser','DevToolsActivePort');
  const debugPort=await until(()=>fs.existsSync(active)&&fs.readFileSync(active,'utf8').split('\n')[0]);
  const tabs=await(await fetch('http://127.0.0.1:'+debugPort+'/json')).json();
  const target=tabs.find(tab=>tab.type==='page' && tab.url==='about:blank');
  assert.ok(target,'Expected the explicitly launched blank page target');
  ws=new WebSocket(target.webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
  let id=0;const pending=new Map();
  ws.onmessage=event=>{const message=JSON.parse(event.data);if(message.id){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(message.error):task.resolve(message.result);}if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails);};
  const send=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));return result.result.value;};
  inspect=()=>evaluate('JSON.stringify({url:location.href,ready:document.readyState,notice:document.getElementById("notice")?.textContent,body:document.body?.innerText.slice(0,1500),viewport:innerWidth,documentWidth:document.documentElement.scrollWidth,overflow:[...document.querySelectorAll("body *")].filter(e=>e.getBoundingClientRect().right>innerWidth || e.scrollWidth>e.clientWidth+1).map(e=>({tag:e.tagName,id:e.id,class:e.className,right:e.getBoundingClientRect().right,width:e.getBoundingClientRect().width})).slice(0,30)})');
  const click=id=>evaluate('document.getElementById('+JSON.stringify(id)+').click()');
  const fill=(id,value)=>evaluate('(()=>{const e=document.getElementById('+JSON.stringify(id)+');e.value='+JSON.stringify(value)+';e.dispatchEvent(new Event("input",{bubbles:true}));e.dispatchEvent(new Event("change",{bubbles:true}));})()');
  await send('Page.enable');await send('Runtime.enable');
  await send('Page.navigate',{url:'http://127.0.0.1:'+port+'/workbench'});
  await until(()=>evaluate('document.getElementById("notice")?.textContent === "Collection ready."'));
  await fill('recipe','intent-requests-v1');await fill('count',6);
  await evaluate('document.getElementById("generate-form").requestSubmit()');
  await until(()=>evaluate('document.getElementById("notice").textContent.includes("6 candidates created")'));
  await evaluate('[...document.querySelectorAll(".record input[type=checkbox]")].slice(0,2).forEach(e=>e.click())');
  await fill('train',100);await fill('validation',0);await fill('test',0);
  assert.equal(await evaluate('document.getElementById("selection").textContent'),'2 selected');
  assert.ok((await evaluate('document.getElementById("analysis").textContent')).startsWith('6 records'));
  assert.equal(await evaluate('document.getElementById("freeze-release").disabled'),true);
  await click('preview-release');await until(()=>evaluate('!document.getElementById("freeze-release").disabled'));
  assert.ok((await evaluate('document.getElementById("release-preview-status").textContent')).startsWith('2 selected records'));
  assert.ok((await evaluate('document.getElementById("release-preview").textContent')).includes('text classification: 2'));
  assert.equal(fs.readdirSync(path.join(temporary,'data','releases')).length,0,'Preview creates no archive');
  // The actual response is delayed at the browser transport boundary, not replaced by a canned proof.
  await evaluate(`(()=>{const original=window.fetch;window.previewCalls=0;window.releaseCalls=0;window.holdPath=null;window.resumeResponse=null;
    window.fetch=async(...args)=>{const url=String(args[0]);if(url.endsWith('/releases/preview'))window.previewCalls++;
    if(url.endsWith('/releases'))window.releaseCalls++;
    const response=await original(...args);if(window.holdPath && url.endsWith(window.holdPath))await new Promise(resolve=>window.resumeResponse=resolve);return response;};})()`);
  await evaluate('window.holdPath="/releases/preview"');await click('preview-release');await click('preview-release');
  await until(()=>evaluate('typeof window.resumeResponse === "function"'));
  await fill('split-seed',43);await evaluate('window.holdPath=null;window.resumeResponse();window.resumeResponse=null');
  await until(()=>evaluate('!document.getElementById("preview-release").disabled'));
  assert.equal(await evaluate('window.previewCalls'),1,'Repeated preview click is suppressed');
  assert.equal(await evaluate('document.getElementById("freeze-release").disabled'),true);
  assert.equal(await evaluate('document.getElementById("release-preview").textContent'),'','Obsolete preview is ignored');
  await fill('train',80);await fill('validation',10);await fill('test',10);await click('preview-release');
  await until(()=>evaluate('document.getElementById("release-preview").textContent.includes("Too few independent source groups")'));
  assert.equal(await evaluate('document.getElementById("freeze-release").disabled'),true);
  await fill('train',100);await fill('validation',0);await fill('test',0);
  await fill('release-format','image_caption_v1');await click('preview-release');
  await until(()=>evaluate('document.getElementById("release-preview").textContent.includes("human-reviewed image-caption")'));
  await fill('release-format','canonical_v1');
  // A source edit in another client makes selected revision pairs stale.
  await evaluate(`(async()=>{const r=[...selected.values()][0];await api('records/'+r.id,{...r,annotation:{label:'changed elsewhere'},review:'human_reviewed'});})()`);
  await click('preview-release');await until(()=>evaluate('document.getElementById("release-preview").textContent.includes("Selection changed")'));
  await click('clear-selection');await until(()=>evaluate('!document.getElementById("clear-selection").dataset.busy && document.getElementById("selection").textContent === "0 selected"'));
  await click('select-page');await until(()=>evaluate('!document.getElementById("select-page").dataset.busy && document.getElementById("selection").textContent === "6 selected"'));
  await click('preview-release');await until(()=>evaluate('!document.getElementById("freeze-release").disabled'));
  // An unselected bridge changes the relevant family proof without changing selected revisions.
  await evaluate(`(async()=>{const rows=[...selected.values()];await api('import',{kind:'text',name:'unselected bridge',text:'A distinct lineage bridge.',groups:[rows[0].groups[0],rows[1].groups[0]],rights:'owned'});})()`);
  await evaluate('document.getElementById("release-form").requestSubmit()');
  await until(()=>evaluate('document.getElementById("release-preview-status").textContent.includes("Release preview changed")'));
  assert.equal(fs.readdirSync(path.join(temporary,'data','releases')).length,0,'Stale proof creates no archive');
  await click('preview-release');await until(()=>evaluate('!document.getElementById("freeze-release").disabled'));
  assert.equal(await evaluate('releasePreview.lineage.reduce((n,family)=>n+family.member_ids.length,0)'),7);
  await evaluate('window.holdPath="/releases";window.releaseCalls=0');
  await evaluate('document.getElementById("release-form").requestSubmit();document.getElementById("release-form").requestSubmit()');
  await until(()=>evaluate('typeof window.resumeResponse === "function"'));
  await fill('split-seed',44);await evaluate('window.holdPath=null;window.resumeResponse();window.resumeResponse=null');
  await until(()=>evaluate('!document.getElementById("preview-release").disabled'));
  assert.equal(await evaluate('window.releaseCalls'),1,'Repeated export is suppressed');
  assert.equal(await evaluate('document.querySelector("#release-result a")===null'),true,'Old export cannot represent new settings');
  await click('preview-release');await until(()=>evaluate('!document.getElementById("freeze-release").disabled'));
  await evaluate('document.getElementById("release-form").requestSubmit()');await until(()=>evaluate('!!document.querySelector("#release-result a")'));
  const download=await fetch(await evaluate('document.querySelector("#release-result a").href'));
  assert.equal(download.status,200);assert.ok((await download.arrayBuffer()).byteLength>1000);
  await evaluate('document.getElementById("release-form").scrollIntoView()');
  fs.mkdirSync(qaDirectory(root,'selected-release-preview'),{recursive:true});
  const desktop=await send('Page.captureScreenshot',screenshotOptions);
  fs.writeFileSync(path.join(qaDirectory(root,'selected-release-preview'),'preview-desktop.jpg'),Buffer.from(desktop.data,'base64'));
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});
  await evaluate('document.getElementById("release-preview-status").scrollIntoView()');
  const shot=await send('Page.captureScreenshot',screenshotOptions);
  fs.writeFileSync(path.join(qaDirectory(root,'selected-release-preview'),'preview-narrow.jpg'),Buffer.from(shot.data,'base64'));
  assert.ok(await evaluate('document.documentElement.scrollWidth<=innerWidth'),'Narrow preview does not overflow');
  assert.deepEqual(errors,[]);console.log('Exact selection preview, read-only preflight, split/format/stale blockers, changed controls, delayed responses, repeated actions and frozen download passed.');
})().catch(async error=>{console.error(error);console.error('Runtime errors:',JSON.stringify(errors));if(inspect)try{console.error('Page diagnostics:',await inspect());}catch(diagnostic){console.error('Diagnostics failed:',diagnostic);}process.exitCode=1;}).finally(async()=>{if(ws)ws.close();for(const child of children)child.kill();await pause(200);fs.rmSync(temporary,{recursive:true,force:true});});
