// Actual loopback Chromium binary relevance authoring/transfer; authored QA only.
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {spawn,execFileSync}=require('node:child_process'),{qaDirectory,screenshotOptions}=require('./qa_artifacts.cjs');
const {waitForDebugger}=require('./browser_startup.cjs'),{pageLoadTracker}=require('./browser_page_load.cjs');
const root=path.resolve(process.env.TULDOK_SOURCE_ROOT||path.join(__dirname,'..')),output=qaDirectory(root,'retrieval-binary'),scratch=fs.mkdtempSync(path.join(os.tmpdir(),'tuldok-binary-ui-'));
const children=[],errors=[],network=new Map(),downloads=[],tracker=pageLoadTracker(),sha=raw=>crypto.createHash('sha256').update(raw).digest('hex'),pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const python=process.env.RETRIEVAL_BINARY_CONSUMER_PYTHON||process.env.INSTRUCTION_CONSUMER_PYTHON||'python3';
let ws,owner='first',stage='startup';
async function until(check){for(let i=0;i<200;i++){if(await check())return;await pause(75);}throw Error('Timed out: '+stage);}
function launch(command,args,options){const child=spawn(command,args,options);children.push(child);return child;}
async function server(name){const folder=path.join(scratch,name);fs.mkdirSync(folder,{recursive:true});const child=launch(python,['-u','app.py','--port','0','--data',path.join(folder,'data')],{cwd:root,stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',chunk=>stdout+=chunk);child.stderr.on('data',chunk=>stderr+=chunk);await until(()=>{if(child.exitCode!==null)throw Error(stderr);return /127\.0\.0\.1:(\d+)/.test(stdout);});return 'http://127.0.0.1:'+stdout.match(/127\.0\.0\.1:(\d+)/)[1];}
const ref=row=>({id:row.id,revision:row.revision,source_revision:row.source_revision});
(async()=>{
 const base=await server('first'),secondBase=await server('second');
 const get=async(base,route)=>(await(await fetch(base+'/api/workbench/'+route)).json());
 const api=async(route,body)=>{const response=await fetch(base+'/api/workbench/'+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const row=await response.json();assert.ok(response.ok,JSON.stringify(row));return row;};
 const inputs=[['Orchard A','  Cafe\u0301 orchard notes.\r\nWater and sunlight.  ','binary-orchard'],['Orchard B','Orchard transport control B: authored not-relevant.\n','binary-orchard'],['Orchard C','Orchard transport control C: explicit unjudged.\n','binary-orchard'],['Orchard unused','Selected omitted document, never inferred negative.\n','binary-orchard'],['Garden','Garden authored all-unjudged control.\n','binary-garden'],['V1 retained','Retained positive-only document; separate owner.\n','retained-v1']];
 const seeded=[];for(const [name,text,group] of inputs)seeded.push(await api('import',{kind:'text',name,text,groups:[group],rights:'Project-authored QA; no semantic or permission qualification'}));
 const browser=launch(process.env.BROWSER||'/usr/bin/chromium',['--headless','--no-sandbox','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--window-size=1400,950','--user-data-dir='+path.join(scratch,'browser'),'about:blank'],{stdio:['ignore','ignore','pipe'],env:{...process.env,XDG_CONFIG_HOME:scratch,XDG_CACHE_HOME:scratch}});
 const port=await waitForDebugger(browser,path.join(scratch,'browser','DevToolsActivePort')),tabs=await(await fetch('http://127.0.0.1:'+port+'/json')).json();ws=new WebSocket(tabs.find(tab=>tab.type==='page'&&tab.url==='about:blank').webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
 let sequence=0;const pending=new Map();
 ws.onmessage=event=>{const message=JSON.parse(event.data);tracker.observe(message);if(message.id){const request=pending.get(message.id);if(request){pending.delete(message.id);message.error?request.reject(message.error):request.resolve(message.result);}}
  if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails);
  if(['Browser.downloadWillBegin','Browser.downloadProgress'].includes(message.method))downloads.push({method:message.method,params:message.params,stage,owner});
  if(message.method==='Network.requestWillBeSent'){const request=message.params.request,url=new URL(request.url);if(url.hostname==='127.0.0.1')network.set(message.params.requestId,{request_id:message.params.requestId,owner,stage,method:request.method,path:url.pathname,body_sha256:request.postData?sha(request.postData):null,status:null});}
  if(message.method==='Network.responseReceived'){const request=network.get(message.params.requestId);if(request)request.status=message.params.response.status;}
 };
 const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence,timer=setTimeout(()=>{pending.delete(id);reject(Error('CDP timeout '+method));},15000);pending.set(id,{resolve:value=>{clearTimeout(timer);resolve(value);},reject:error=>{clearTimeout(timer);reject(error);}});ws.send(JSON.stringify({id,method,params}));});
 const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));return result.result.value;};
 const click=id=>evaluate('document.getElementById('+JSON.stringify(id)+').click()');
 const submit=id=>evaluate('document.getElementById('+JSON.stringify(id)+').requestSubmit()');
 const fill=(id,value)=>evaluate(`(()=>{const element=document.getElementById(${JSON.stringify(id)});element.value=${JSON.stringify(value)};element.dispatchEvent(new Event('input',{bubbles:true}));if(element.tagName==='SELECT')element.dispatchEvent(new Event('change',{bubbles:true}));})()`);
 const idle=()=>evaluate('!document.getElementById("editor").dataset.busy');
 const open=async row=>{stage='rendered Open '+row.name;await evaluate('window.qaPreviousCurrent=current');await evaluate(`(()=>{const item=[...document.querySelectorAll('#records .record')].find(item=>item.querySelector('input')?.getAttribute('aria-label')===${JSON.stringify('Select '+row.name)});if(!item)throw Error('Expected source not rendered');item.querySelector('button').click();})()`);await until(()=>evaluate('current!==qaPreviousCurrent&&current?.id==='+JSON.stringify(row.id)+'&&!dirty&&!document.getElementById("editor").dataset.busy'));};
 const reload=async(discard=false)=>{stage='rendered reload';await evaluate('window.qaPreviousCurrent=current');const action=click('reload');if(discard){await pause(80);await send('Page.handleJavaScriptDialog',{accept:true});}await action;await until(()=>evaluate('current!==qaPreviousCurrent&&!dirty&&!document.getElementById("reload").dataset.busy'));};
 const save=async()=>{stage='rendered binary draft/review Save';await submit('editor');await until(idle);assert.equal(await evaluate('dirty'),false);};
 const navigate=async url=>{stage='fresh document navigation';const old=(await send('Page.getFrameTree')).frameTree.frame;await send('Page.navigate',{url});await until(()=>tracker.reloaded(old));await until(()=>evaluate('document.readyState==="complete"&&document.getElementById("notice")?.textContent==="Collection ready."'));};
 const clearSelection=async()=>{await click('clear-selection');await until(()=>evaluate('!document.getElementById("clear-selection").dataset.busy&&selected.size===0'));};
 const select=async rows=>{await clearSelection();for(const row of rows){await evaluate(`document.querySelector('input[aria-label='+${JSON.stringify(JSON.stringify('Select '+row.name))}+']').click()`);assert.ok(await evaluate('selected.has('+JSON.stringify(row.id)+')'),'Selection failed for '+JSON.stringify(row));}assert.equal(await evaluate('selected.size'),rows.length);};
 const pairs=()=>evaluate('[...selected.values()].map(({id,revision,source_revision})=>({id,revision,source_revision})).sort((a,b)=>a.id.localeCompare(b.id))');
 const named=async name=>{stage='named fixed selection Save/Open/reload';const expected=await pairs();await fill('selection-name',name);await submit('save-selection-form');await until(()=>evaluate('!document.getElementById("save-selection-form").dataset.busy&&document.getElementById("saved-selection-status").textContent.startsWith("Saved “")'));const id=await evaluate('document.getElementById("saved-selection").value');await clearSelection();await click('load-selection');await until(()=>evaluate('!savedLoadBusy&&selected.size===8'));assert.deepEqual(await pairs(),expected);const old=(await send('Page.getFrameTree')).frameTree.frame;await send('Page.reload');await until(()=>tracker.reloaded(old));await until(()=>evaluate('document.readyState==="complete"&&!savedLoadBusy&&selected.size===8&&document.getElementById("saved-selection-status").textContent.startsWith("Opened “")'));assert.deepEqual(await pairs(),expected);return {id,pairs:expected};};
 const preview=async()=>{await click('preview-release');await until(()=>evaluate('!releaseBusy'));};
 const freeze=async(name,rows)=>{stage='binary preview/freeze';await fill('release-format','text_retrieval_binary_v2');await fill('train',50);await fill('validation',50);await fill('test',0);await preview();assert.equal(await evaluate('releasePreview.eligible'),true);await submit('release-form');await until(()=>evaluate('!releaseBusy&&!!document.querySelector("#release-result a")'));const url=await evaluate('document.querySelector("#release-result a").href'),folder=path.join(output,'downloads',name);fs.mkdirSync(folder,{recursive:true});await send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:folder,eventsEnabled:true});await evaluate('document.querySelector("#release-result a").click()');await until(()=>downloads.some(item=>item.method==='Browser.downloadWillBegin'&&item.params.url===url));const begin=downloads.findLast(item=>item.method==='Browser.downloadWillBegin'&&item.params.url===url);await until(()=>downloads.some(item=>item.method==='Browser.downloadProgress'&&item.params.guid===begin.params.guid&&item.params.state==='completed'));const archive=path.join(folder,begin.params.suggestedFilename),raw=fs.readFileSync(archive),expected=path.join(output,name+'-expected.json');fs.writeFileSync(expected,JSON.stringify(rows,null,2)+'\n');assert.ok(url.includes(sha(raw)));execFileSync(python,['tests/check_retrieval_binary_reader.py','--archive',archive,'--expected',expected,'--output',path.join(output,name+'-reader')],{cwd:root,stdio:'inherit',timeout:90000});return {url,archive,sha256:sha(raw),guid:begin.params.guid,reader:JSON.parse(fs.readFileSync(path.join(output,name+'-reader','report.json')))};};
 const picture=async(name,id)=>{await evaluate('document.getElementById('+JSON.stringify(id)+').scrollIntoView()');fs.writeFileSync(path.join(output,name+'.jpg'),Buffer.from((await send('Page.captureScreenshot',screenshotOptions)).data,'base64'));};
 const reviewDocument=async row=>{await open(row);await fill('task','text_retrieval_binary');await fill('retrieval-binary-role','document');await fill('retrieval-binary-note','QA document draft inspection: '+row.name);await save();await reload();assert.equal(await evaluate('current.review'),'draft');await fill('record-review','human_reviewed');await save();return get(base,'records/'+row.id);};
 const rawQuery=async(name,text,judgments)=>{for(const [key,value] of Object.entries({name,text,group:'binary-query-'+name,rights:'Project-authored query transport QA',judgments:JSON.stringify(judgments)}))await fill('retrieval-binary-query-'+key,value);await submit('retrieval-binary-query-form');await until(()=>evaluate('!retrievalBinaryImports.query.busy'));};
 const queryRole=async row=>{await open(row);await fill('task','text_retrieval_binary');await fill('retrieval-binary-role','query');await fill('retrieval-binary-note','QA explicit states: '+row.name);};
 const refreshRef=async id=>{await evaluate(`document.querySelector('button[aria-label='+${JSON.stringify(JSON.stringify('Refresh document reference '+id))}+']').click()`);await until(()=>evaluate('retrievalBinaryReads.size===0'));};
 await send('Page.enable');await send('Runtime.enable');await send('Network.enable');await send('Page.setLifecycleEventsEnabled',{enabled:true});await navigate(base+'/workbench');
 const docs=[];for(const row of seeded.slice(0,5))docs.push(await reviewDocument(row));
 await open(seeded[5]);await fill('task','text_retrieval');await fill('retrieval-role','document');await fill('retrieval-note','Retained v1 QA note');await save();await reload();await fill('record-review','human_reviewed');await save();const v1=await get(base,'records/'+seeded[5].id);await fill('retrieval-note','Later unsaved v1 note');await evaluate(`document.querySelector('input[aria-label='+${JSON.stringify(JSON.stringify('Select '+v1.name))}+']').click()`);const v1Pair=await pairs();
 const declaredA=docs.slice(0,3).map((doc,i)=>({document:ref(doc),relevance:['relevant','not_relevant','unjudged'][i]}));
 await rawQuery('Query A','  Find cafe\u0301 orchard?\r\n ',declaredA);assert.equal(await evaluate('current.id'),v1.id);assert.equal(await evaluate('document.getElementById("retrieval-note").value'),'Later unsaved v1 note');assert.equal(await evaluate('dirty'),true);assert.deepEqual(await pairs(),v1Pair);
 stage='controlled raw query lost acknowledgement';await evaluate('window.qaFetch=window.fetch;window.qaLoseQuery=true;window.fetch=async(input,options)=>{const response=await qaFetch(input,options);if(String(input)==="/api/workbench/retrieval-binary-query"&&qaLoseQuery){qaLoseQuery=false;throw Error("QA lost binary query acknowledgement");}return response;}');
 const declaredB=[{document:ref(docs[1]),relevance:'not_relevant'},{document:ref(docs[2]),relevance:'unjudged'}];await rawQuery('Query zero-positive','Zero-positive orchard QA?',declaredB);assert.match(await evaluate('document.getElementById("retrieval-binary-query-status").textContent'),/not replayed/);assert.equal((await get(base,'records')).items.filter(row=>row.name==='Query zero-positive').length,1);await evaluate('window.fetch=qaFetch');await submit('filters');await until(()=>evaluate('!document.getElementById("filters").dataset.busy'));
 await rawQuery('Query all-unjudged','Garden all-unjudged QA?',[{document:ref(docs[4]),relevance:'unjudged'}]);await reload(true);
 let all=(await get(base,'records')).items,queryA=all.find(row=>row.name==='Query A'),queryB=all.find(row=>row.name==='Query zero-positive'),queryC=all.find(row=>row.name==='Query all-unjudged');
 await queryRole(queryA);await fill('retrieval-binary-note','');await submit('editor');await until(idle);assert.equal((await get(base,'records/'+queryA.id)).revision,1);await fill('retrieval-binary-note','QA explicit three-state query');
 for(const state of ['not_relevant','unjudged','relevant'])await evaluate(`(()=>{const e=document.querySelector('#retrieval-binary-judgments select');e.value=${JSON.stringify(state)};e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));})()`);
 await evaluate('document.querySelector("#retrieval-binary-judgments button").click()');await fill('retrieval-binary-document-ref',JSON.stringify(ref(docs[0])));await fill('retrieval-binary-relevance','relevant');await click('retrieval-binary-add');assert.equal(await evaluate('retrievalBinaryRows.length'),3);
 stage='lost committed annotation Save and stale retry';await evaluate(`window.qaFetch=window.fetch;window.qaLoseSave=true;window.fetch=async(input,options)=>{const response=await qaFetch(input,options);if(String(input)==='/api/workbench/records/${queryA.id}'&&options?.method==='POST'&&qaLoseSave){qaLoseSave=false;throw Error('QA lost binary Save acknowledgement');}return response;}`);await submit('editor');await until(idle);assert.equal(await evaluate('dirty'),true);assert.equal((await get(base,'history/'+queryA.id)).length,2);await submit('editor');await until(idle);assert.equal((await get(base,'history/'+queryA.id)).length,2);await evaluate('window.fetch=qaFetch');await reload(true);
 stage='held repeated Save with later note/rights intent';await fill('retrieval-binary-note','Held binary query note');await evaluate(`window.qaFetch=window.fetch;window.qaHoldSave=true;window.fetch=async(input,options)=>{const response=await qaFetch(input,options);if(String(input)==='/api/workbench/records/${queryA.id}'&&options?.method==='POST'&&qaHoldSave){qaHoldSave=false;await new Promise(resolve=>window.qaSaveRelease=resolve);}return response;}`);await submit('editor');await until(()=>evaluate('!!window.qaSaveRelease'));await submit('editor');await fill('retrieval-binary-note','Later query note retained');await fill('rights-note-value','Later unsaved rights note retained');await evaluate('qaSaveRelease()');await until(idle);assert.equal(await evaluate('document.getElementById("retrieval-binary-note").value'),'Later query note retained');assert.equal(await evaluate('document.getElementById("rights-note-value").value'),'Later unsaved rights note retained');assert.equal(await evaluate('dirty'),true);assert.equal((await get(base,'history/'+queryA.id)).length,3);await evaluate('window.fetch=qaFetch');await reload(true);await fill('record-review','human_reviewed');await save();
 for(const row of [queryB,queryC]){await queryRole(row);await save();await reload();assert.equal(await evaluate('current.review'),'draft');await fill('record-review','human_reviewed');await save();}
 const bridge=await api('import',{kind:'text',name:'Unselected retained bridge',text:'Authored draft bridge joins orchard source.\n',groups:['binary-orchard'],parents:[docs[0].id],rights:'unknown'});await submit('filters');await until(()=>evaluate('!document.getElementById("filters").dataset.busy'));
 let rows=await Promise.all([...docs,queryA,queryB,queryC].map(row=>get(base,'records/'+row.id)));await select(rows);const oldSet=await named('Before deliberate reference repair');
 await open(docs[0]);await fill('rights-note-value','Local QA document rights correction');await submit('rights-note-form');await until(()=>evaluate('!rightsBusy&&!rightsDirty'));const updated=await get(base,'records/'+docs[0].id);assert.equal(updated.review,'human_reviewed');await open(queryA);const prior=(await get(base,'records/'+queryA.id)).revision;await submit('editor');await until(idle);assert.equal((await get(base,'records/'+queryA.id)).revision,prior);assert.match(await evaluate('document.getElementById("notice").textContent'),/refresh.*revision|document changed/i);
 stage='held reference Refresh versus later note';await evaluate(`window.qaFetch=window.fetch;window.qaHoldRef=true;window.fetch=async(input,options)=>{const response=await qaFetch(input,options);if(String(input)==='/api/workbench/records/${docs[0].id}'&&qaHoldRef){qaHoldRef=false;await new Promise(resolve=>window.qaRefRelease=resolve);}return response;}`);await evaluate(`document.querySelector('button[aria-label='+${JSON.stringify(JSON.stringify('Refresh document reference '+docs[0].id))}+']').click()`);await until(()=>evaluate('!!window.qaRefRelease'));await fill('retrieval-binary-note','Later deliberate repair note');await evaluate('qaRefRelease()');await pause(100);assert.equal(await evaluate(`retrievalBinaryRows.find(row=>row.document.id===${JSON.stringify(docs[0].id)}).document.revision`),docs[0].revision);assert.equal(await evaluate('document.getElementById("retrieval-binary-note").value'),'Later deliberate repair note');await evaluate('window.fetch=qaFetch');await refreshRef(docs[0].id);assert.equal(await evaluate('document.getElementById("record-review").value'),'draft');await save();await reload();assert.equal(await evaluate('current.review'),'draft');await fill('record-review','human_reviewed');await save();
 stage='held reference inspection versus different owner';await evaluate(`window.qaFetch=window.fetch;window.qaHoldOwnerRef=true;window.fetch=async(input,options)=>{const response=await qaFetch(input,options);if(String(input)==='/api/workbench/records/${docs[0].id}'&&qaHoldOwnerRef){qaHoldOwnerRef=false;await new Promise(resolve=>window.qaOwnerRefRelease=resolve);}return response;}`);await evaluate(`document.querySelector('button[aria-label='+${JSON.stringify(JSON.stringify('Refresh document reference '+docs[0].id))}+']').click()`);await until(()=>evaluate('!!window.qaOwnerRefRelease'));await open(v1);await evaluate('qaOwnerRefRelease()');await pause(100);assert.equal(await evaluate('current.id'),v1.id);assert.equal(await evaluate('document.getElementById("retrieval-note").value'),'Retained v1 QA note');assert.equal(await evaluate('document.getElementById("retrieval-binary-controls").hidden'),true);await evaluate('window.fetch=qaFetch');
 rows=await Promise.all(rows.map(row=>get(base,'records/'+row.id)));await select(rows);const firstSet=await named('Reviewed binary exact sources');await fill('release-format','text_retrieval_binary_v2');const first=await freeze('first-binary',rows),firstBytes=fs.readFileSync(first.archive);assert.equal(first.reader.documents,5);assert.equal(first.reader.queries,3);assert.equal(first.reader.judgments,6);assert.deepEqual(first.reader.explicit_state_counts,{relevant:1,not_relevant:2,unjudged:3});
 await open(rows.find(row=>row.id===queryA.id));await picture('binary-desktop','retrieval-binary-controls');await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});await picture('binary-narrow','retrieval-binary-controls');assert.ok(await evaluate('document.documentElement.scrollWidth<=innerWidth'));await send('Emulation.clearDeviceMetricsOverride');
 owner='second';await navigate(secondBase+'/workbench');const native=async raw=>{await evaluate(`(()=>{const dt=new DataTransfer();dt.items.add(new File([Uint8Array.from(atob(${JSON.stringify(raw.toString('base64'))}),c=>c.charCodeAt(0))],'binary-release.zip',{type:'application/zip'}));document.getElementById('retrieval-binary-native-archive').files=dt.files;})()`);await submit('retrieval-binary-native-form');await until(()=>evaluate('!retrievalBinaryImports.native.busy'));};
 stage='actual native whole ZIP atomic import';await native(firstBytes);assert.match(await evaluate('document.getElementById("retrieval-binary-native-status").textContent'),/Draft admission confirmed/);let imported=(await get(secondBase,'records')).items;assert.equal(imported.length,8);assert.ok(imported.every(row=>row.review==='draft'&&row.revision===1&&row.provenance.rights==='unknown'));assert.ok(imported.every(row=>!rows.some(original=>original.id===row.id)));const receipt=await evaluate('JSON.parse(document.getElementById("retrieval-binary-native-evidence").textContent)');assert.equal(receipt.release_sha256,first.sha256);
 await native(firstBytes);assert.equal((await get(secondBase,'records')).items.length,8);assert.match(await evaluate('document.getElementById("retrieval-binary-native-status").textContent'),/not replayed/);const truncated=firstBytes.subarray(0,firstBytes.length-3);await native(truncated);assert.equal((await get(secondBase,'records')).items.length,8);
 const initialImported=structuredClone(imported),documents=imported.filter(row=>row.annotation.role==='document'),queries=imported.filter(row=>row.annotation.role==='query');
 for(const row of documents){await open(row);await fill('retrieval-binary-note','Second-owner QA document draft');await save();await reload();assert.equal(await evaluate('current.review'),'draft');await fill('rights-note-value','Local second-owner document QA rights note');await submit('rights-note-form');await until(()=>evaluate('!rightsBusy&&!rightsDirty'));assert.equal(await evaluate('current.provenance.rights'),'unknown');await fill('record-review','human_reviewed');await save();}
 for(const row of queries){await open(row);await submit('editor');await until(idle);assert.equal((await get(secondBase,'history/'+row.id)).length,1);for(const judgment of row.annotation.judgments)await refreshRef(judgment.document.id);await fill('retrieval-binary-note','Second-owner explicit relation QA draft');await save();await reload();assert.equal(await evaluate('current.review'),'draft');await fill('rights-note-value','Local second-owner query QA rights note');await submit('rights-note-form');await until(()=>evaluate('!rightsBusy&&!rightsDirty'));await fill('record-review','human_reviewed');await save();}
 imported=await Promise.all(imported.map(row=>get(secondBase,'records/'+row.id)));await select(imported);const secondSet=await named('Second-owner reviewed exact binary');const second=await freeze('second-binary',imported),secondBytes=fs.readFileSync(second.archive);assert.deepEqual(second.reader.explicit_state_counts,first.reader.explicit_state_counts);await open(imported.find(row=>row.annotation.role==='query'));await picture('binary-native-provenance','record-provenance');
 await fill('retrieval-binary-note','New query draft after freeze');await save();await clearSelection();await fill('saved-selection',secondSet.id);await click('load-selection');await until(()=>evaluate('!savedLoadBusy&&selected.size===8'));assert.deepEqual(await pairs(),secondSet.pairs);await preview();assert.equal(await evaluate('releasePreview.eligible'),false);assert.equal(await evaluate('document.getElementById("freeze-release").disabled'),true);assert.equal((await get(secondBase,'selections/'+secondSet.id)).current,false);
 assert.deepEqual(fs.readFileSync(first.archive),firstBytes);assert.deepEqual(fs.readFileSync(second.archive),secondBytes);assert.equal(sha(Buffer.from(await(await fetch(first.url)).arrayBuffer())),first.sha256);assert.equal(sha(Buffer.from(await(await fetch(second.url)).arrayBuffer())),second.sha256);assert.deepEqual((await get(base,'records/'+v1.id)).annotation,v1.annotation);assert.equal((await get(base,'records/'+bridge.id)).review,'draft');
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});await picture('binary-stale-selection','release-preview-status');assert.ok(await evaluate('document.documentElement.scrollWidth<=innerWidth'));assert.deepEqual(errors,[]);
 const snapshot=JSON.parse(execFileSync(python,['-c','import json;from scripts.qualify_text_classification_local import source_snapshot;print(json.dumps(source_snapshot()))'],{cwd:root,encoding:'utf8'}));
 fs.writeFileSync(path.join(output,'session.json'),JSON.stringify({status:'PASS',candidate_head:snapshot.head,source_snapshot_sha256:snapshot.sha256,source_records:rows,initial_native_drafts:initialImported,second_owner_records:imported,native_receipt:receipt,first,second,old_pre_repair_set:oldSet,first_fixed_set:firstSet,second_fixed_set:secondSet,unselected_draft_bridge_id:bridge.id,unused_selected_document_id:docs[3].id,raw_query_NFC_LF_source_proof:true,three_explicit_states_and_zero_positive_and_all_unjudged:true,separate_draft_reload_review:true,dirty_v1_editor_and_selection_retained:true,lost_query_and_save_no_automatic_replay:true,held_repeated_Save_later_note_rights_retained:true,stale_document409_and_deliberate_guarded_refresh:true,actual_chromium_downloads:true,actual_external_source_loaded_qrels_reader:true,native_atomic_duplicate_truncated_refusal:true,native_newIDs_draft_unknown_and_original_evidence:true,second_owner_documents_first_then_deliberate_query_refs_review:true,named_fixed_sets_full_reload_exact_and_stale_refusal:true,old_both_frozen_urls_bytes_immutable:true,all_reviews_are_simulated_QA:true,no_ranking_metrics_fitting_models_training:true,network:[...network.values()],download_events:downloads,network_scope:'Actual loopback browser CDP; source document/bridge fixture creation and Node verification reads are separately labelled. Controlled acknowledgement holds/drops retain actual committed server responses.',fixture_basis:'Tiny source-derived authored binary fixture; no authentic human benchmark, retrieval quality or permission claim.',errors},null,2)+'\n');console.log('Binary relevance actual browser/source loaded reader/two-owner workflow PASS: '+output);
})().catch(error=>{console.error('Stage:',stage,error);console.error('Runtime errors:',JSON.stringify(errors));process.exitCode=1;}).finally(async()=>{if(ws)ws.close();for(const child of children)child.kill();await pause(250);for(const child of children)if(child.exitCode===null&&child.signalCode===null)child.kill('SIGKILL');fs.rmSync(scratch,{recursive:true,force:true});});
