// Real manifest files, HTTP admission, cancellation, persistence and Chromium.
'use strict';
const {qaDirectory,screenshotOptions}=require('./qa_artifacts.cjs');
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {spawn,spawnSync}=require('node:child_process'),crypto=require('node:crypto');
const {pageLoadTracker}=require('./browser_page_load.cjs');
const root=path.resolve(__dirname,'..'),temporary=fs.mkdtempSync(path.join(os.tmpdir(),'tuldok-preference-browser-')),children=[];
const errors=[],tracker=pageLoadTracker(),pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
let ws,inspect;
async function until(fn){for(let i=0;i<150;i++){const value=await fn();if(value)return value;await pause(100);}throw Error('Timed out');}
function launch(command,args,options={}){const child=spawn(command,args,options);children.push(child);return child;}
function python(code,...args){const result=spawnSync('python3',['-c',code,...args],{cwd:root,encoding:'utf8'});assert.equal(result.status,0,result.stderr);return result.stdout;}
(async()=>{
  const server=launch('python3',['-u','app.py','--port','0','--data',path.join(temporary,'data')],{cwd:root,stdio:['ignore','pipe','pipe']});
  let output='';server.stdout.on('data',data=>output+=data);server.stderr.on('data',data=>{if(process.env.BULK_BROWSER_DEBUG)process.stderr.write(data);});
  const port=await until(()=>output.match(/127\.0\.0\.1:(\d+)/)?.[1]),base='http://127.0.0.1:'+port;
  const api=async(route,body)=>{const response=await fetch(base+'/api/workbench/'+route,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();assert.ok(response.ok,JSON.stringify(result));return result;};
  launch(process.env.BROWSER||'/usr/bin/chromium',['--headless','--no-sandbox','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--window-size=1400,950','--user-data-dir='+path.join(temporary,'browser'),'about:blank'],{stdio:['ignore','ignore','inherit'],env:{...process.env,XDG_CONFIG_HOME:temporary,XDG_CACHE_HOME:temporary}});
  const active=path.join(temporary,'browser','DevToolsActivePort');
  const debugPort=await until(()=>fs.existsSync(active)&&fs.readFileSync(active,'utf8').split('\n')[0]);
  const tabs=await(await fetch('http://127.0.0.1:'+debugPort+'/json')).json(),target=tabs.find(tab=>tab.type==='page'&&tab.url==='about:blank');
  assert.ok(target,'Expected explicitly launched page');ws=new WebSocket(target.webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
  let id=0;const pending=new Map();
  ws.onmessage=event=>{const message=JSON.parse(event.data);tracker.observe(message);if(message.id){const task=pending.get(message.id);pending.delete(message.id);if(task)message.error?task.reject(message.error):task.resolve(message.result);}if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails);};
  const send=(method,params={})=>new Promise((resolve,reject)=>{const request=++id;const timer=setTimeout(()=>{pending.delete(request);reject(Error('CDP timeout: '+method));},20000);pending.set(request,{resolve:value=>{clearTimeout(timer);resolve(value);},reject:error=>{clearTimeout(timer);reject(error);}});ws.send(JSON.stringify({id:request,method,params}));});
  const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));return result.result.value;};
  inspect=()=>evaluate('JSON.stringify({url:location.href,notice:document.getElementById("notice")?.textContent,preferenceStatus:document.getElementById("preference-editor-status")?.textContent,preferenceBusy,preferenceListBusy,preferenceDirty,preferencePreview,preferenceRows,release:document.getElementById("release-preview-status")?.textContent,releaseBusy,preview:releasePreview?.eligible,results:document.getElementById("caption-results")?.textContent,body:document.body?.innerText.slice(0,1800)})');
  const click=id=>evaluate('document.getElementById('+JSON.stringify(id)+').click()');
  await send('Page.enable');await send('Page.setLifecycleEventsEnabled',{enabled:true});await send('Runtime.enable');
  console.log('Preference browser targets:',JSON.stringify(tabs.map(tab=>({type:tab.type,url:tab.url}))));
  console.log('Preference browser version:',JSON.stringify(await send('Browser.getVersion')));
  assert.ok(!(await send('Page.navigate',{url:base+'/workbench'})).errorText);
  await until(()=>evaluate('document.getElementById("notice")?.textContent==="Collection ready."'));
  const fill=(id,value)=>evaluate('(()=>{const e=document.getElementById('+JSON.stringify(id)+');e.value='+JSON.stringify(value)+';e.dispatchEvent(new Event("input",{bubbles:true}));e.dispatchEvent(new Event("change",{bubbles:true}));})()');
  const submit=async id=>{await evaluate('document.getElementById('+JSON.stringify(id)+').requestSubmit()');await until(()=>evaluate('!document.getElementById('+JSON.stringify(id)+').dataset.busy'));};
  const filter=()=>submit('filters');
  const reports=qaDirectory(root,'preference-pairs');fs.mkdirSync(reports,{recursive:true});
  const identity=spawnSync('git',['rev-parse','HEAD','HEAD^{tree}'],{cwd:root,encoding:'utf8'}).stdout.trim().split('\n');
  const diff=spawnSync('git',['diff','HEAD','--','workbench.py','dataset_releases.py','app.py','static','tests'],{cwd:root,encoding:'utf8'}).stdout;
  const evidence={source_head:identity[0],source_tree:identity[1],source_state:diff?'working_tree':'committed',source_diff_sha256:crypto.createHash('sha256').update(diff).digest('hex'),browser:await send('Browser.getVersion'),screenshots:[],steps:[]};
  async function open(parent){await evaluate('openRecord('+JSON.stringify(parent.id)+')');await until(()=>evaluate('current?.id==='+JSON.stringify(parent.id)+' && !preferenceListBusy && !responseListBusy'));}
  async function saveAnswer(content){await click('response-new');await fill('response-entry-format','json');await fill('response-completion',JSON.stringify(content));await evaluate('document.getElementById("response-form").requestSubmit()');await until(()=>evaluate('!responseBusy&&!responseListBusy&&!responseDirty'));await click('response-cancel');return (await api('records/'+(await evaluate('current.id'))+'/responses')).responses.find(row=>row.completion===content);}
  async function setupJudgment(left,right,outcome='right'){await click('preference-new');await fill('preference-left',left.id);await fill('preference-right',right.id);await fill('preference-outcome',outcome);await fill('preference-rationale','Compared these two exact answers.');assert.equal(await evaluate('document.getElementById("preference-review").value'),'draft');}
  async function saveJudgment(review='human_reviewed'){await fill('preference-review',review);await evaluate('document.getElementById("preference-form").requestSubmit()');await until(()=>evaluate('!preferenceBusy&&!preferenceListBusy&&!preferenceDirty'));return evaluate('preferenceEditor');}
  async function select(row){await evaluate('document.querySelector('+JSON.stringify('#preference-list button[data-preference-id="'+row.id+'"]')+').previousElementSibling.click()');}
  async function preview(){await click('preference-preview');await until(()=>evaluate('!preferenceReleaseBusy&&!!preferencePreview'));return evaluate('preferencePreview');}
  async function capture(name,selector){for(const narrow of [false,true]){
    const viewport={width:narrow?390:1400,height:narrow?844:1000};await send('Emulation.setDeviceMetricsOverride',{...viewport,deviceScaleFactor:1,mobile:false});await evaluate('document.querySelector('+JSON.stringify(selector)+').scrollIntoView({block:"start"})');await pause(100);assert.ok(await evaluate('document.documentElement.scrollWidth<=innerWidth'),'Horizontal overflow');
    const shot=Buffer.from((await send('Page.captureScreenshot',screenshotOptions)).data,'base64'),file='preference-'+name+(narrow?'-narrow':'-desktop')+'.jpg';fs.writeFileSync(path.join(reports,file),shot);evidence.screenshots.push({file,viewport,selector,sha256:crypto.createHash('sha256').update(shot).digest('hex')});
  }await send('Emulation.setDeviceMetricsOverride',{width:1400,height:1000,deviceScaleFactor:1,mobile:false});}
  const parents=[];for(const name of ['primary','second','third'])parents.push(await api('import',{kind:'text',name,text:' prompt '+name+'\r\ne\u0301 😀 '+(name==='primary'?'p'.repeat(1100):''),groups:['preference-'+name],rights:'Authored QA fixture'}));
  const parent=parents[0];await open(parent);
  const exact='\ufeff e\u0301\r\n😀 '+'x'.repeat(1100)+'  ',left=await saveAnswer(exact),right=await saveAnswer(' Alternative <eos>');
  assert.equal(left.review,'draft');assert.equal(right.review,'draft');await click('preference-refresh');await until(()=>evaluate('!preferenceListBusy'));
  await setupJudgment(left,right);
  // Real acknowledgment held while a later rationale is entered; repeated submits cannot replay.
  await fill('preference-review','human_reviewed');await evaluate(`window.baseFetch=fetch;window.held=null;window.holdOnce=true;window.preferenceSaves=0;window.fetch=async(...args)=>{if(String(args[0]).endsWith('/preferences')&&args[1]?.method==='POST')++preferenceSaves;const response=await baseFetch(...args);if(String(args[0]).endsWith('/preferences')&&args[1]?.method==='POST'&&holdOnce){holdOnce=false;await new Promise(resolve=>held=resolve);}return response;};`);
  await evaluate('document.getElementById("preference-form").requestSubmit();document.getElementById("preference-form").requestSubmit()');await until(()=>evaluate('!!held'));assert.equal(await evaluate('preferenceSaves'),1);
  await fill('preference-rationale','Later unsaved comparative rationale');await fill('rights-note-value','Attempt during judgment edit');await evaluate('document.getElementById("rights-note-form").requestSubmit()');assert.match(await evaluate('document.getElementById("rights-note-status").textContent'),/judgment edit/);assert.deepEqual(await api('records/'+parent.id),parent);await click('rights-note-cancel');await evaluate('window.confirm=()=>false');await evaluate('openRecord('+JSON.stringify(parents[1].id)+')');assert.equal(await evaluate('current.id'),parent.id);
  await evaluate('held();held=null');await until(()=>evaluate('!preferenceBusy&&!preferenceListBusy'));assert.equal(await evaluate('preferenceDirty'),true);assert.equal(await evaluate('document.getElementById("preference-rationale").value'),'Later unsaved comparative rationale');assert.equal(await evaluate('document.getElementById("preference-review").value'),'draft');
  await click('preference-cancel');await evaluate('window.fetch=baseFetch;window.confirm=()=>true');
  let row=(await api('records/'+parent.id+'/preferences')).judgments[0];await select(row);const fixed=await evaluate('preferenceReleaseBody().items');let proof=await preview();assert.equal(proof.eligible,true);
  await evaluate('document.querySelector('+JSON.stringify('#preference-list button[data-preference-id="'+row.id+'"]')+').click()');await capture('01-comparison','#preferences-panel');
  // A parent load cannot discard newer independent comparison intent.
  await evaluate(`window.parentFetch=fetch;window.parentHeld=null;window.parentDone=false;window.fetch=async(...args)=>{const response=await parentFetch(...args);if(String(args[0])==='/api/workbench/records/${parents[1].id}')await new Promise(resolve=>parentHeld=resolve);return response;};window.parentTask=openRecord('${parents[1].id}').then(()=>parentDone=true);void 0;`);
  await until(()=>evaluate('!!parentHeld'));await fill('preference-outcome','left');await evaluate('parentHeld();parentHeld=null');await until(()=>evaluate('parentDone'));assert.equal(await evaluate('current.id'),parent.id);assert.equal(await evaluate('preferenceDirty'),true);await click('preference-cancel');await evaluate('window.fetch=parentFetch');
  // Answer edit invalidates judgment evidence, with no conversion from answer review.
  await evaluate('document.querySelector('+JSON.stringify('#response-list button[data-response-id="'+left.id+'"]')+').click()');await fill('response-completion',JSON.stringify(exact+' changed'));await fill('response-review','human_reviewed');await evaluate('document.getElementById("response-form").requestSubmit()');await until(()=>evaluate('!responseBusy&&!responseListBusy&&!responseDirty'));
  assert.equal(await evaluate('preferencePreview'),null);assert.equal(await evaluate('document.getElementById("preference-freeze").disabled'),true);assert.deepEqual(await evaluate('preferenceReleaseBody().items'),fixed);await click('response-cancel');
  let changed={response:(await api('records/'+parent.id+'/responses')).responses.find(answer=>answer.id===left.id)};
  await click('preference-refresh');await until(()=>evaluate('!preferenceListBusy'));assert.deepEqual(await evaluate('preferenceReleaseBody().items'),fixed);proof=await preview();assert.equal(proof.eligible,false);assert.match(proof.blockers[0].message,/Stale judgment/);
  await evaluate('document.querySelector('+JSON.stringify('#preference-list button[data-preference-id="'+row.id+'"]')+').click()');assert.equal(await evaluate('document.getElementById("preference-review").value'),'draft');row=await saveJudgment();assert.deepEqual(await evaluate('preferenceReleaseBody().items'),fixed);await select(row);await select(row);proof=await preview();assert.equal(proof.eligible,true);
  // Unselected current dissent still blocks; direct deletion restores the audited direction.
  await click('preference-cancel');await setupJudgment(right,changed.response,'right');const dissent={judgment:await saveJudgment()};
  assert.equal(await evaluate('preferencePreview'),null);assert.equal(await evaluate('document.getElementById("preference-freeze").disabled'),true);
  proof=await preview();assert.equal(proof.eligible,false);assert.match(proof.blockers[0].message,/Conflicting current/);
  await click('preference-refresh');await until(()=>evaluate('!preferenceListBusy'));await evaluate('document.querySelector('+JSON.stringify('#preference-list button[data-preference-id="'+dissent.judgment.id+'"]')+').click()');await click('preference-delete');await until(()=>evaluate('!preferenceBusy&&!preferenceListBusy'));assert.equal((await api('preference-history/'+dissent.judgment.id)).history.length,2);
  await click('preference-cancel');await setupJudgment(changed.response,right,'tie');const tie=await saveJudgment();await select(tie);await click('preference-cancel');await setupJudgment(changed.response,right,'abstain');const abstain=await saveJudgment();await select(abstain);await click('preference-cancel');proof=await preview();assert.equal(proof.example_count,1);assert.equal(proof.excluded.length,2);
  // Same prompt has two directional pairs, both fixed to explicit outcomes and same family.
  const third=await saveAnswer('Third draft answer');await click('preference-refresh');await until(()=>evaluate('!preferenceListBusy'));await setupJudgment(right,third,'left');await capture('short-comparison','#preferences-panel');await click('preference-cancel');await setupJudgment(changed.response,third,'left');const secondPair=await saveJudgment();await select(secondPair);await click('preference-cancel');
  for(const prompt of parents.slice(1)){await open(prompt);const a=await saveAnswer('Long '+prompt.name+' '+ 'q'.repeat(1100)),b=await saveAnswer('Short '+prompt.name);await click('preference-refresh');await until(()=>evaluate('!preferenceListBusy'));await setupJudgment(a,b,'left');const j=await saveJudgment();await select(j);await click('preference-cancel');}
  await fill('preference-train','50');await fill('preference-validation','25');await fill('preference-test','25');proof=await preview();assert.equal(proof.eligible,true);assert.equal(proof.example_count,4);assert.equal(proof.selected_count,6);assert.deepEqual(proof.split_report.actual_counts,{train:2,validation:1,test:1});await capture('02-preview','#preference-release-panel');
  // Selection changes during a held preview fence the obsolete proof.
  await evaluate(`window.previewFetch=fetch;window.previewHeld=null;window.fetch=async(...args)=>{const response=await previewFetch(...args);if(String(args[0]).endsWith('/releases/preview'))await new Promise(resolve=>previewHeld=resolve);return response;};`);await click('preference-preview');await until(()=>evaluate('!!previewHeld'));await evaluate('preferenceSelectionChanged()');await evaluate('previewHeld();previewHeld=null');await until(()=>evaluate('!preferenceReleaseBusy'));assert.equal(await evaluate('preferencePreview'),null);await evaluate('window.fetch=previewFetch');proof=await preview();assert.equal(proof.eligible,true);
  const downloads=path.join(temporary,'downloads');fs.mkdirSync(downloads);await send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloads,eventsEnabled:true});
  await evaluate('document.getElementById("preference-release-form").requestSubmit();document.getElementById("preference-release-form").requestSubmit()');await until(()=>evaluate('!preferenceReleaseBusy&&!!document.querySelector("#preference-release-result a")'));await evaluate('document.querySelector("#preference-release-result a").click()');await until(()=>fs.readdirSync(downloads).some(name=>name.endsWith('.zip')));const archive=path.join(downloads,fs.readdirSync(downloads).find(name=>name.endsWith('.zip')));
  const consumerRun=spawnSync(process.env.INSTRUCTION_CONSUMER_PYTHON||'python3',['tests/check_preference_consumer.py',archive],{cwd:root,encoding:'utf8',timeout:120000});assert.equal(consumerRun.status,0,consumerRun.stdout+'\n'+consumerRun.stderr);const consumer=JSON.parse(consumerRun.stdout.trim().split('\n').at(-1));assert.equal(consumer.result,'PASS');assert.equal(consumer.examples,4);
  const bytes=fs.readFileSync(archive);assert.equal(consumer.zip_sha256,crypto.createHash('sha256').update(bytes).digest('hex'));fs.writeFileSync(path.join(reports,'preference-downloaded.zip'),bytes);
  // Live mutation/deletion leaves the actual browser downloaded release unchanged.
  const downloadUrl=await evaluate('document.querySelector("#preference-release-result a").href');await api('preferences/delete',Object.fromEntries(['id','revision','prompt_id','parent_revision','source_revision','left_id','left_revision','right_id','right_revision'].map(key=>[key,row[key]])));
  assert.equal(Buffer.compare(Buffer.from(await(await fetch(downloadUrl)).arrayBuffer()),bytes),0);
  await capture('03-download','#preference-release-panel');assert.deepEqual(await api('records/'+parent.id),parent);assert.deepEqual(errors,[]);
  evidence.steps.push({stage:'explicit-comparison',answers_draft:true,held_ack_later_intent:true,held_parent_later_intent:true,stale_answer_review_not_preference:true,unselected_conflict:true,local_bound_answer_invalidates_preview:true,local_unselected_opposing_review_invalidates_preview:true,delete_history:true,tie_abstain_exclusion:true},{stage:'actual-download',preview:proof,consumer,zip_bytes:bytes.length,immutable_after_delete:true});evidence.errors=errors;evidence.result='PASS';fs.writeFileSync(path.join(reports,'preference-session.json'),JSON.stringify(evidence,null,2)+'\n');console.log('PASS real Chromium explicit comparison, stale/rejudge, unselected conflict/delete/history, ties/abstentions, independent review and intent, weighted splits, immutable actual download and pinned DPO preparation/collator; desktop/narrow.');
})().catch(async error=>{console.error(error);console.error('Runtime errors:',JSON.stringify(errors));if(inspect)try{console.error('Page diagnostics:',await inspect());}catch(diagnostic){console.error('Diagnostics failed:',diagnostic);}process.exitCode=1;}).finally(async()=>{if(ws)ws.close();for(const child of children)child.kill();await pause(200);fs.rmSync(temporary,{recursive:true,force:true});});
