// Native browser smoke test. No npm dependencies.
const assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {spawn}=require('node:child_process');
const {pageLoadTracker}=require('./browser_page_load.cjs');
const loads=pageLoadTracker();
const root=path.resolve(__dirname,'..'),temporary=fs.mkdtempSync(path.join(os.tmpdir(),'tuldok-test-')),children=[];
let ws, inspect;
const errors=[];
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function until(fn){for(let i=0;i<150;i++){const value=await fn();if(value)return value;await pause(100);}throw Error('Timed out');}
function launch(command,args,options={}){const child=spawn(command,args,options);children.push(child);return child;}
(async()=>{
  const server=launch('python3',['-u','tests/browser_grounded_server.py','--port','0','--data',path.join(temporary,'data')],{cwd:root,stdio:['ignore','pipe','pipe']});
  let output='',stderr='';server.stdout.on('data',data=>output+=data);server.stderr.on('data',data=>stderr+=data);
  const port=await until(()=>output.match(/127\.0\.0\.1:(\d+)/)?.[1]);
  launch(process.env.BROWSER||'/usr/bin/chromium',['--headless','--no-sandbox','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--window-size=1400,950','--user-data-dir='+path.join(temporary,'browser'),'about:blank'],{stdio:['ignore','ignore','inherit'],env:{...process.env,HOME:temporary,XDG_CONFIG_HOME:temporary,XDG_CACHE_HOME:temporary}});
  const active=path.join(temporary,'browser','DevToolsActivePort');
  const debugPort=await until(()=>fs.existsSync(active)&&fs.readFileSync(active,'utf8').split('\n')[0]);
  const tabs=await(await fetch('http://127.0.0.1:'+debugPort+'/json')).json();
  const target=tabs.find(tab=>tab.type==='page' && tab.url==='about:blank');
  assert.ok(target,'Expected the explicitly launched blank page target');
  ws=new WebSocket(target.webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
  let id=0;const pending=new Map();
  ws.onmessage=event=>{const message=JSON.parse(event.data);loads.observe(message);if(message.id){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(message.error):task.resolve(message.result);}if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails);};
  const send=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));return result.result.value;};
  inspect=()=>evaluate('JSON.stringify({url:location.href,ready:document.readyState,notice:document.getElementById("notice")?.textContent,body:document.body?.innerText.slice(0,1500),groundedJobs:document.getElementById("grounded-jobs")?.textContent,viewport:innerWidth,documentWidth:document.documentElement.scrollWidth,overflow:[...document.querySelectorAll("body *")].filter(e=>e.getBoundingClientRect().right>innerWidth || e.scrollWidth>e.clientWidth+1).map(e=>({tag:e.tagName,id:e.id,class:e.className,right:e.getBoundingClientRect().right,width:e.getBoundingClientRect().width})).slice(0,30)})');
  const click=id=>evaluate('document.getElementById('+JSON.stringify(id)+').click()');
  const fill=(id,value)=>evaluate('(()=>{const e=document.getElementById('+JSON.stringify(id)+');e.value='+JSON.stringify(value)+';e.dispatchEvent(new Event("input",{bubbles:true}));e.dispatchEvent(new Event("change",{bubbles:true}));})()');
  await send('Page.enable');await send('Page.setLifecycleEventsEnabled',{enabled:true});await send('Runtime.enable');
  await send('Page.navigate',{url:'http://127.0.0.1:'+port+'/workbench'});
  await until(()=>evaluate('document.getElementById("notice")?.textContent === "Collection ready."'));
  await fill('import-name','Cancellation source');await fill('import-group','source-family');await fill('import-text','Cancel the café meeting 😀.');
  await evaluate('document.getElementById("import-form").requestSubmit()');
  await until(()=>evaluate('document.getElementById("notice").textContent === "Record imported."'));
  await fill('label','cancel');await fill('record-review','human_reviewed');await evaluate('document.getElementById("editor").requestSubmit()');
  await until(()=>evaluate('!document.getElementById("editor").dataset.busy && document.getElementById("notice").textContent === "Annotation saved."'));
  const modelPort=output.match(/GROUNDED_MODEL_PORT=(\d+)/)[1];
  await fill('grounded-url','http://127.0.0.1:'+modelPort);await click('grounded-models');
  await until(()=>evaluate('document.getElementById("grounded-model").value === "grounded-text-test"'));
  assert.equal(await evaluate('document.getElementById("grounded-model").options.length'),1);
  await fill('grounded-count',2);await evaluate('document.getElementById("grounded-form").requestSubmit()');
  await until(()=>evaluate('document.querySelector(".proposal-job summary")?.textContent.includes("completed")'));
  await evaluate('if(!document.querySelector(".proposal-job").open)document.querySelector(".proposal-job summary").click()');
  const completedJob=await evaluate('document.querySelector(".proposal-job").dataset.jobId');
  assert.equal(await evaluate('document.querySelectorAll(".proposal-candidate").length'),2);
  assert.ok((await evaluate('document.querySelector(".proposal-job").textContent')).includes('Cancel the café meeting 😀.'));
  await evaluate('document.querySelector(".proposal-candidate textarea").value="Check facts separately in annotation review";document.querySelector(".proposal-candidate textarea").dispatchEvent(new Event("input"))');
  await evaluate('[...document.querySelectorAll(".proposal-candidate button")].find(b=>b.textContent==="Admit as draft").click()');
  await until(()=>evaluate('!![...document.querySelectorAll(".proposal-candidate button")].find(b=>b.textContent==="Open admitted draft")'));
  await evaluate('document.querySelector(".proposal-job").open=true;[...document.querySelectorAll(".proposal-candidate button")].find(b=>b.textContent==="Open admitted draft").click()');
  await until(()=>evaluate('document.getElementById("record-name").textContent.startsWith("Rewrite:")'));
  assert.equal(await evaluate('document.getElementById("record-review").value'),'draft');
  await click('select-page');await fill('train',100);await fill('validation',0);await fill('test',0);await evaluate('document.getElementById("release-form").requestSubmit()');
  await until(()=>evaluate('document.getElementById("notice").textContent.includes("reviewed or programmatically verified")'));
  assert.equal(await evaluate('document.querySelector("#release-result a")===null'),true);
  await fill('record-review','human_reviewed');await evaluate('document.getElementById("editor").requestSubmit()');
  await until(()=>evaluate('!document.getElementById("editor").dataset.busy && document.getElementById("notice").textContent === "Annotation saved."'));
  await evaluate('document.getElementById("release-form").requestSubmit()');await until(()=>evaluate('!!document.querySelector("#release-result a")'));
  const archive=await fetch(await evaluate('document.querySelector("#release-result a").href'));assert.equal(archive.status,200);assert.ok((await archive.arrayBuffer()).byteLength>1000);
  await evaluate('document.querySelector(".proposal-job").open=true;document.querySelector(".proposal-candidate textarea").value="Reject this variant after inspection"');
  await evaluate('[...document.querySelectorAll(".proposal-candidate button")].find(b=>b.textContent==="Reject candidate").click()');
  await until(()=>evaluate('document.querySelector("#grounded-jobs").textContent.includes("State: rejected")'));
  await fill('grounded-instruction','slow');await evaluate('document.getElementById("grounded-form").requestSubmit()');
  await until(()=>evaluate('!![...document.querySelectorAll(".proposal-job button")].find(b=>b.textContent==="Cancel request")'));
  await evaluate('[...document.querySelectorAll(".proposal-job button")].find(b=>b.textContent==="Cancel request").click()');
  await until(()=>evaluate('document.querySelector(".proposal-job summary")?.textContent.includes("cancelled")'));
  const cancelledJob=await evaluate('document.querySelector(".proposal-job").dataset.jobId');
  const beforeReload=await evaluate(`(async()=>{const data=await(await fetch('/api/workbench/grounded/jobs')).json();return data.jobs.map(job=>({id:job.id,status:job.status,candidates:job.candidates.map(({id,status,record_id,review_note})=>({id,status,record_id,review_note}))}));})()`);
  assert.deepEqual(beforeReload.find(job=>job.id===completedJob).candidates.map(candidate=>candidate.status),['admitted','rejected']);
  assert.equal(beforeReload.find(job=>job.id===cancelledJob).status,'cancelled');
  const previous=(await send('Page.getFrameTree')).frameTree.frame;
  assert.ok(previous.loaderId,'The reopen check needs the old document loader identity');
  await send('Page.reload');
  // Page.reload acknowledges the request before the old document is replaced.
  // Wait on a new loaded main document before inspecting persisted proposal UI.
  await until(()=>loads.reloaded(previous));
  await until(()=>evaluate(`(()=>{const completed=document.querySelector('[data-job-id="${completedJob}"]');const cancelled=document.querySelector('[data-job-id="${cancelledJob}"]');return completed?.textContent.includes('State: admitted') && completed.textContent.includes('State: rejected') && cancelled?.querySelector('summary').textContent.includes('cancelled');})()`));
  const afterReload=await evaluate(`(async()=>{const data=await(await fetch('/api/workbench/grounded/jobs')).json();return data.jobs.map(job=>({id:job.id,status:job.status,candidates:job.candidates.map(({id,status,record_id,review_note})=>({id,status,record_id,review_note}))}));})()`);
  assert.deepEqual(afterReload,beforeReload,'Reopening must preserve exact proposal decisions, notes and admitted identity');
  const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
  fs.writeFileSync(path.join(root,'docs/plans/dataset-workflows/reports/workbench-grounded.png'),Buffer.from(shot.data,'base64'));
  assert.deepEqual(errors,[]);console.log('Grounded browser source, served catalog, proposals, draft gate, human review, release, rejection, cancellation and reopen passed with a controlled provider.');
})().catch(async error=>{console.error(error);console.error('Runtime errors:',JSON.stringify(errors));if(inspect)try{console.error('Page diagnostics:',await inspect());}catch(diagnostic){console.error('Diagnostics failed:',diagnostic);}process.exitCode=1;}).finally(async()=>{if(ws)ws.close();for(const child of children)child.kill();await pause(200);fs.rmSync(temporary,{recursive:true,force:true});});
