// Actual rendered authoring/import/export/reader flows; authored QA, no models.
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {spawn,execFileSync}=require('node:child_process'),{qaDirectory,screenshotOptions}=require('./qa_artifacts.cjs');
const {waitForDebugger}=require('./browser_startup.cjs'),{pageLoadTracker}=require('./browser_page_load.cjs');
const root=path.resolve(process.env.TULDOK_SOURCE_ROOT||path.join(__dirname,'..')),output=qaDirectory(root,'polygon-segmentation');
const scratch=fs.mkdtempSync(path.join(os.tmpdir(),'tuldok-polygon-ui-')),children=[],errors=[],network=new Map(),tracker=pageLoadTracker();
const python=process.env.INSTRUCTION_CONSUMER_PYTHON||'python3',sha=raw=>crypto.createHash('sha256').update(raw).digest('hex'),pause=ms=>new Promise(r=>setTimeout(r,ms));
let ws,stage='startup',owner='first';const downloads=[];
async function until(fn){for(let i=0;i<200;i++){if(await fn())return;await pause(75);}throw Error('Timed out: '+stage);}
function launch(cmd,args,opts){const child=spawn(cmd,args,opts);children.push(child);return child;}
async function start(folder,empty=false){fs.mkdirSync(folder,{recursive:true});const child=launch(python,['-u','tests/browser_polygon_server.py','--port','0','--data',path.join(folder,'data'),...(empty?['--empty']:[])],{cwd:root,stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',v=>stdout+=v);child.stderr.on('data',v=>stderr+=v);await until(()=>{if(child.exitCode!==null)throw Error(stderr);return /127\.0\.0\.1:(\d+)/.test(stdout);});return 'http://127.0.0.1:'+stdout.match(/127\.0\.0\.1:(\d+)/)[1];}
(async()=>{
 const base=await start(path.join(scratch,'first')),secondBase=await start(path.join(scratch,'second'),true);
 const browser=launch(process.env.BROWSER||'/usr/bin/chromium',['--headless','--no-sandbox','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--window-size=1400,950','--user-data-dir='+path.join(scratch,'browser'),'about:blank'],{stdio:['ignore','ignore','pipe'],env:{...process.env,XDG_CONFIG_HOME:scratch,XDG_CACHE_HOME:scratch}});
 const port=await waitForDebugger(browser,path.join(scratch,'browser','DevToolsActivePort')),tabs=await(await fetch('http://127.0.0.1:'+port+'/json')).json();
 ws=new WebSocket(tabs.find(t=>t.type==='page'&&t.url==='about:blank').webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
 let id=0;const pending=new Map();
 ws.onmessage=event=>{const message=JSON.parse(event.data);tracker.observe(message);if(message.id){const p=pending.get(message.id);pending.delete(message.id);message.error?p.reject(message.error):p.resolve(message.result);}
  if(message.method==='Browser.downloadWillBegin'||message.method==='Browser.downloadProgress')downloads.push({method:message.method,params:message.params,stage,owner});
  if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails);
  if(message.method==='Network.requestWillBeSent'){const request=message.params.request,u=new URL(request.url);if(u.hostname==='127.0.0.1')network.set(message.params.requestId,{request_id:message.params.requestId,owner,method:request.method,path:u.pathname,stage,body_sha256:request.postData?sha(request.postData):null,status:null});}
  if(message.method==='Network.responseReceived'){const r=network.get(message.params.requestId);if(r)r.status=message.params.response.status;}
 };
 const send=(method,params={})=>new Promise((resolve,reject)=>{const request=++id,t=setTimeout(()=>{pending.delete(request);reject(Error('CDP timeout '+method));},15000);pending.set(request,{resolve:v=>{clearTimeout(t);resolve(v);},reject:e=>{clearTimeout(t);reject(e);}});ws.send(JSON.stringify({id:request,method,params}));});
 const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
 const click=id=>evaluate('document.getElementById('+JSON.stringify(id)+').click()');
 const fill=(id,value)=>evaluate(`(()=>{const e=document.getElementById(${JSON.stringify(id)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));if(e.tagName==='SELECT')e.dispatchEvent(new Event('change',{bubbles:true}));})()`);
 const submit=id=>evaluate('document.getElementById('+JSON.stringify(id)+').requestSubmit()');
 const get=async(base,name)=>(await(await fetch(base+'/api/workbench/'+name)).json());
 const fullRows=async base=>{const rows=(await get(base,'records?kind=image')).items;return Promise.all(rows.map(r=>get(base,'records/'+r.id)));};
 const editorIdle=()=>evaluate('!document.getElementById("editor").dataset.busy');
 const open=async row=>{stage='rendered open '+row.id;await evaluate('window.qaPreviousCurrent=current');await evaluate(`(()=>{const e=[...document.querySelectorAll('#records .record')].find(r=>r.querySelector('input')?.getAttribute('aria-label')===${JSON.stringify('Select '+row.name)});if(!e)throw Error('Source row is not rendered');e.querySelector('button').click();})()`);await until(()=>evaluate('current!==window.qaPreviousCurrent&&current?.id==='+JSON.stringify(row.id)+'&&!dirty&&!document.getElementById("editor").dataset.busy'));};
 const reload=async discard=>{stage='explicit rendered reload';await evaluate('window.qaPreviousCurrent=current');const promise=click('reload');if(discard){await pause(80);await send('Page.handleJavaScriptDialog',{accept:true});}await promise;await until(()=>evaluate('current!==window.qaPreviousCurrent&&!dirty&&!document.getElementById("reload").dataset.busy'));};
 const navigate=async url=>{stage='fresh document navigation';const old=(await send('Page.getFrameTree')).frameTree.frame;await send('Page.navigate',{url});await until(()=>tracker.reloaded(old));await until(()=>evaluate('document.readyState==="complete"&&document.getElementById("notice")?.textContent==="Collection ready."'));};
 const importFile=async raw=>{stage='rendered native ZIP import';await evaluate(`(()=>{const dt=new DataTransfer();dt.items.add(new File([Uint8Array.from(atob(${JSON.stringify(raw.toString('base64'))}),c=>c.charCodeAt(0))],'native-polygon.zip',{type:'application/zip'}));document.getElementById('native-detection-archive').files=dt.files;document.getElementById('native-detection-form').requestSubmit();})()`);await until(()=>evaluate('!detectionRunning'));};
 const removeAll=async()=>{while(await evaluate('targets.length'))await evaluate('document.querySelector("#targets button").click()');};
 const add=async instance=>{await fill('label',instance.label);await fill('polygon-points',instance.points.map(p=>p.join(',')).join('\n'));await click('add-polygon');};
 const save=async()=>{stage='rendered annotation save';await submit('editor');await until(()=>editorIdle());assert.equal(await evaluate('dirty'),false);};
 const review=async row=>{await open(row);await fill('record-review','human_reviewed');await save();assert.equal(await evaluate('current.review'),'human_reviewed');};
 const selectAll=async()=>{stage='rendered exact source selection';await click('clear-selection');await evaluate("for(const r of page.items.filter(r=>r.kind==='image'))document.querySelector('input[aria-label=\"Select '+r.name+'\"]')?.click()");assert.equal(await evaluate('selected.size'),6);};
 const pairs=()=>evaluate('([...selected.values()].map(({id,revision,source_revision})=>({id,revision,source_revision}))).sort((a,b)=>a.id.localeCompare(b.id))');
 const namedSet=async name=>{stage='rendered named fixed selection';const expected=await pairs();await fill('selection-name',name);await submit('save-selection-form');await until(()=>evaluate('!document.getElementById("save-selection-form").dataset.busy&&document.getElementById("saved-selection-status").textContent.startsWith("Saved “")'));const id=await evaluate('document.getElementById("saved-selection").value');await click('clear-selection');await click('load-selection');await until(()=>evaluate('!savedLoadBusy&&selected.size===6'));assert.deepEqual(await pairs(),expected);const old=(await send('Page.getFrameTree')).frameTree.frame;await send('Page.reload');await until(()=>tracker.reloaded(old));await until(()=>evaluate('document.readyState==="complete"&&!savedLoadBusy&&selected.size===6&&document.getElementById("saved-selection-status").textContent.startsWith("Opened “")'));assert.deepEqual(await pairs(),expected);return {id,pairs:expected};};
 const preview=async()=>{stage='rendered release preview';await click('preview-release');await until(()=>evaluate('!releaseBusy'));};
 const freeze=async(name,rows)=>{await preview();assert.equal(await evaluate('releasePreview.eligible'),true);stage='rendered freeze and file download';await submit('release-form');await until(()=>evaluate('!releaseBusy&&!!document.querySelector("#release-result a")'));const url=await evaluate('document.querySelector("#release-result a").href'),folder=path.join(output,'downloads',name);fs.mkdirSync(folder,{recursive:true});await send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:folder,eventsEnabled:true});await evaluate('document.querySelector("#release-result a").click()');await until(()=>downloads.some(d=>d.method==='Browser.downloadWillBegin'&&d.params.url===url)&&fs.readdirSync(folder).some(n=>n.endsWith('.zip')));const begun=downloads.findLast(d=>d.method==='Browser.downloadWillBegin'&&d.params.url===url);await until(()=>downloads.some(d=>d.method==='Browser.downloadProgress'&&d.params.guid===begun.params.guid&&d.params.state==='completed'));const archive=path.join(folder,begun.params.suggestedFilename),raw=fs.readFileSync(archive),expected=path.join(output,name+'-expected-records.json');assert.ok(raw.length>0);fs.writeFileSync(expected,JSON.stringify(rows,null,2)+'\n');assert.ok(url.includes(sha(raw)));execFileSync(python,['tests/check_polygon_coco.py','--archive',archive,'--expected',expected,'--output',path.join(output,name+'-reader')],{cwd:root,timeout:90000,stdio:'inherit'});return {url,raw,archive,download_guid:begun.params.guid,sha256:sha(raw),reader:JSON.parse(fs.readFileSync(path.join(output,name+'-reader','polygon-reader-report.json')))};};
 const picture=async(name,element)=>{await evaluate('document.getElementById('+JSON.stringify(element)+').scrollIntoView()');fs.writeFileSync(path.join(output,name+'.jpg'),Buffer.from((await send('Page.captureScreenshot',screenshotOptions)).data,'base64'));};
 const point=async(x,y,button='left',cancel=false)=>{await evaluate('document.getElementById("asset-image").scrollIntoView()');const r=await evaluate('(()=>{const r=document.getElementById("asset-image").getBoundingClientRect();return {x:r.left,y:r.top,w:r.width,h:r.height};})()');const screen={x:r.x+x*r.w/16,y:r.y+y*r.h/12,button,clickCount:1};await send('Input.dispatchMouseEvent',{type:'mousePressed',...screen});if(cancel)await evaluate('document.getElementById("asset-image").dispatchEvent(new PointerEvent("pointercancel",{pointerId:1,isPrimary:true}))');await send('Input.dispatchMouseEvent',{type:'mouseReleased',...screen});};
 await send('Page.enable');await send('Runtime.enable');await send('Network.enable');await send('Page.setLifecycleEventsEnabled',{enabled:true});await navigate(base+'/workbench');
 await evaluate('document.querySelector("#records .record button").click()');await until(()=>evaluate('!!current'));const unrelated=await evaluate('current.id');await fill('label','Unrelated draft retained');
 const sourceRaw=fs.readFileSync(path.join(scratch,'first','native.zip'));await importFile(sourceRaw);assert.equal(await evaluate('detectionCounts.created'),6);assert.equal(await evaluate('current.id'),unrelated);assert.equal(await evaluate('document.getElementById("label").value'),'Unrelated draft retained');await reload(true);
 let rows=await fullRows(base),authored=rows.find(r=>r.annotation.instances.length),instances=structuredClone(authored.annotation.instances);assert.equal(rows.length,6);assert.ok(rows.every(r=>r.review==='draft'&&r.provenance.rights==='unknown'));
 // Controlled HTTP target fixture: source JSON contains integral floats and signed zero.
 const primitiveAnnotation='{"instances":[{"label":"Primitive QA","points":[[-0.0,1.0],[4.0,1.0],[4.0,5],[0.0,5]]}]}';
 const seeded=await fetch(base+'/api/workbench/records/'+authored.id,{method:'POST',headers:{'Content-Type':'application/json'},body:'{"revision":'+authored.revision+',"source_revision":'+authored.source_revision+',"groups":'+JSON.stringify(authored.groups)+',"task":"image_segmentation","annotation":'+primitiveAnnotation+',"review":"draft"}'});assert.equal(seeded.status,200,await seeded.text());
 await open(authored);stage='rendered point-token integrity refusal';await evaluate('window.qaTokens=polygonNumberSources.get(targets[0]);polygonNumberSources.set(targets[0],[["0],1],\\"bad\\":1", "1.0"],["4.0","1.0"],["4.0","5"],["0.0","5"]])');await submit('editor');await until(()=>editorIdle());assert.ok((await evaluate('document.getElementById("notice").textContent')).includes('coordinate evidence changed'));assert.equal((await get(base,'records/'+authored.id)).revision,authored.revision+1);await evaluate('polygonNumberSources.set(targets[0],qaTokens);targets[0].points[0][0]=0');await submit('editor');await until(()=>editorIdle());assert.ok((await evaluate('document.getElementById("notice").textContent')).includes('coordinate evidence changed'));assert.equal((await get(base,'records/'+authored.id)).revision,authored.revision+1);await evaluate('targets[0].points[0][0]=-0');await save();await reload(false);await fill('record-review','human_reviewed');await save();
 let primitiveRaw=await(await fetch(base+'/api/workbench/records/'+authored.id)).text();
 const checkPrimitives=raw=>execFileSync(python,['-c','import json,sys,math;r=json.loads(sys.argv[1]);p=r["annotation"]["instances"][0]["points"];assert type(p[0][0]) is float and math.copysign(1,p[0][0])==-1;assert type(p[0][1]) is float and type(p[1][0]) is float and type(p[2][1]) is int;assert p==[[-0.0,1.0],[4.0,1.0],[4.0,5],[0.0,5]];assert r["review"]=="human_reviewed"',raw],{cwd:root});
 checkPrimitives(primitiveRaw);await removeAll();await fill('label','Primitive QA');await fill('polygon-points','-0.0,1.0\n4.0,1.0\n4.0,5\n0.0,5');await click('add-polygon');await save();await reload(false);await fill('record-review','human_reviewed');await save();primitiveRaw=await(await fetch(base+'/api/workbench/records/'+authored.id)).text();checkPrimitives(primitiveRaw);fs.writeFileSync(path.join(output,'controlled-primitive-record.json'),primitiveRaw);authored=await get(base,'records/'+authored.id);rows=rows.map(r=>r.id===authored.id?authored:r);
 await open(authored);assert.equal(await evaluate('document.getElementById("task-filter").querySelector("option[value=image_segmentation]")!==null'),true);await until(()=>evaluate('polygonCaptureReady(document.getElementById("asset-image"))'));
 // A clean primary-down gesture invalidates an earlier held Open response.
 stage='clean pointer-down fences older Open';const heldOther=rows.find(r=>r.id!==authored.id);
 await evaluate(`window.qaFetch=window.fetch;window.qaOpenHold=false;window.fetch=async(input,options)=>{const response=await qaFetch(input,options);if(String(input)==='/api/workbench/records/${heldOther.id}'&&!options?.method){qaOpenHold=true;await new Promise(resolve=>window.qaOpenRelease=resolve);}return response;}`);
 await evaluate(`document.querySelector('input[aria-label='+${JSON.stringify(JSON.stringify('Select '+heldOther.name))}+']').closest('.record').querySelector('button').click()`);await until(()=>evaluate('qaOpenHold'));assert.equal(await evaluate('dirty'),false);
 await evaluate('document.getElementById("asset-image").scrollIntoView()');const heldGesture=await evaluate('(()=>{const r=document.getElementById("asset-image").getBoundingClientRect();return {x:r.left+2*r.width/16,y:r.top+2*r.height/12};})()');
 await send('Input.dispatchMouseEvent',{type:'mousePressed',...heldGesture,button:'left',clickCount:1});assert.ok(await evaluate('polygonPointer!==null'));assert.equal(await evaluate('hasUnsavedEdits()'),true);assert.equal(await evaluate('(()=>{const e=new Event("beforeunload",{cancelable:true});window.dispatchEvent(e);return e.defaultPrevented;})()'),true);await evaluate('qaOpenRelease()');await pause(100);assert.equal(await evaluate('current.id'),authored.id);
 await evaluate('document.getElementById("asset-image").dispatchEvent(new PointerEvent("pointercancel",{pointerId:1,isPrimary:true}))');await send('Input.dispatchMouseEvent',{type:'mouseReleased',...heldGesture,button:'left',clickCount:1});assert.equal(await evaluate('polygonPending()'),false);assert.equal(await evaluate('dirty'),false);await evaluate('window.fetch=qaFetch');
 await removeAll();stage='primary and cancelled pointer guards';await point(2,2,'right');assert.equal(await evaluate('document.getElementById("polygon-points").value'),'');await point(2,2,'left',true);assert.equal(await evaluate('document.getElementById("polygon-points").value'),'');
 await evaluate('document.getElementById("asset-image").dispatchEvent(new PointerEvent("pointerdown",{pointerId:9,isPrimary:false,button:0}))');assert.equal(await evaluate('polygonPointer'),null);
 stage='old pointer owner and displayed-source mismatch guards';
 await evaluate('document.getElementById("asset-image").scrollIntoView()');let gesture=await evaluate('(()=>{const r=document.getElementById("asset-image").getBoundingClientRect();return {x:r.left+2*r.width/16,y:r.top+2*r.height/12};})()');
 await send('Input.dispatchMouseEvent',{type:'mousePressed',...gesture,button:'left',clickCount:1});assert.ok(await evaluate('polygonPointer!==null'));
 await evaluate('document.getElementById("asset-image").dispatchEvent(new PointerEvent("pointerup",{pointerId:44,isPrimary:true,button:0}))');assert.ok(await evaluate('polygonPointer!==null'));
 await evaluate('document.getElementById("asset-image").dispatchEvent(new PointerEvent("lostpointercapture",{pointerId:1,isPrimary:true}))');await send('Input.dispatchMouseEvent',{type:'mouseReleased',...gesture,button:'left',clickCount:1});assert.equal(await evaluate('polygonPending()'),false);
 await send('Input.dispatchMouseEvent',{type:'mousePressed',...gesture,button:'left',clickCount:1});const other=rows.find(r=>r.id!==authored.id);const switchOwner=open(other);await pause(80);await send('Page.handleJavaScriptDialog',{accept:true});await switchOwner;await send('Input.dispatchMouseEvent',{type:'mouseReleased',...gesture,button:'left',clickCount:1});assert.equal(await evaluate('polygonPending()'),false);await open(authored);await until(()=>evaluate('polygonCaptureReady(document.getElementById("asset-image"))'));await removeAll();
 await evaluate('document.getElementById("asset-image").src='+JSON.stringify(base+'/api/workbench/asset/'+other.id+'?revision='+other.source_revision));await until(()=>evaluate('document.getElementById("asset-image").complete'));await point(2,2);assert.equal(await evaluate('polygonPending()'),false);await reload(true);await until(()=>evaluate('polygonCaptureReady(document.getElementById("asset-image"))'));await removeAll();
 stage='pending vertices block save and denied task discard';await fill('polygon-points','1.25,1.25\n6.75,1.25');await submit('editor');await until(()=>editorIdle());assert.ok((await evaluate('document.getElementById("notice").textContent')).includes('unfinished polygon'));assert.equal((await get(base,'records/'+authored.id)).revision,authored.revision);
 assert.equal(await evaluate('(()=>{const event=new Event("beforeunload",{cancelable:true});window.dispatchEvent(event);return event.defaultPrevented;})()'),true);
 const denied=fill('task','image_caption');await pause(80);await send('Page.handleJavaScriptDialog',{accept:false});await denied;assert.equal(await evaluate('document.getElementById("task").value'),'image_segmentation');assert.ok(await evaluate('polygonPending()'));
 const accepted=fill('task','image_caption');await pause(80);await send('Page.handleJavaScriptDialog',{accept:true});await accepted;assert.equal(await evaluate('polygonPending()'),false);await fill('task','image_segmentation');
 stage='rendered invalid ring HTTP refusal';await add({label:'Invalid crossing',points:[[0,0],[5,4],[0,4],[4,0]]});await submit('editor');await until(()=>editorIdle());assert.ok((await evaluate('document.getElementById("notice").textContent')).includes('simple'));assert.equal((await get(base,'records/'+authored.id)).revision,authored.revision);await removeAll();
 stage='native fractional coordinate capture';for(const [x,y] of instances[0].points)await point(x,y);await fill('label',instances[0].label);await click('add-polygon');assert.deepEqual(await evaluate('targets[0].points'),instances[0].points);
 for(const instance of instances.slice(1))await add(instance);assert.deepEqual(await evaluate('targets'),instances);assert.equal(await evaluate('document.querySelectorAll("#box-overlay polygon").length'),4);assert.equal(await evaluate('document.querySelectorAll("#targets img,#targets script").length'),0);await picture('polygon-authoring','polygon-controls');
 stage='lost annotation acknowledgement and deliberate reload';await evaluate(`window.qaFetch=window.fetch;window.qaLost=true;window.fetch=async(input,options)=>{const response=await qaFetch(input,options);if(qaLost&&options?.method==='POST'&&String(input)==='/api/workbench/records/${authored.id}'){qaLost=false;await response.clone().json();throw Error('QA lost save acknowledgement');}return response;}`);
 await submit('editor');await until(()=>editorIdle());assert.equal(await evaluate('dirty'),true);const lost=await get(base,'records/'+authored.id);assert.equal(lost.revision,authored.revision+1);assert.equal(lost.review,'draft');await submit('editor');await until(()=>editorIdle());assert.equal((await get(base,'records/'+authored.id)).revision,lost.revision);assert.ok((await evaluate('document.getElementById("notice").textContent')).includes('changed'));await evaluate('window.fetch=qaFetch');await reload(true);assert.deepEqual(await evaluate('targets'),instances);
 stage='held repeated save preserves later rights edit and busy pointer refusal';await evaluate(`window.qaHold=false;window.fetch=async(input,options)=>{const response=await qaFetch(input,options);if(options?.method==='POST'&&String(input)==='/api/workbench/records/${authored.id}'){await response.clone().json();qaHold=true;await new Promise(resolve=>window.qaRelease=resolve);}return response;}`);
 await submit('editor');await until(()=>evaluate('qaHold'));await submit('editor');await point(2,2);assert.equal(await evaluate('polygonPending()'),false);await fill('rights-note-value','Later rights draft retained');await evaluate('qaRelease()');await until(()=>editorIdle());assert.equal(await evaluate('document.getElementById("rights-note-value").value'),'Later rights draft retained');assert.equal(await evaluate('rightsDirty'),true);await evaluate('window.fetch=qaFetch');await reload(true);
 stage='held rights acknowledgement preserves later pending polygon intent';await fill('rights-note-value','Authored QA rights note; no real permission claim');await evaluate(`window.qaHold=false;window.fetch=async(input,options)=>{const response=await qaFetch(input,options);if(options?.method==='POST'&&String(input)==='/api/workbench/rights/${authored.id}'){await response.clone().json();qaHold=true;await new Promise(resolve=>window.qaRelease=resolve);}return response;}`);
 await submit('rights-note-form');await until(()=>evaluate('qaHold'));await point(2,2);assert.equal(await evaluate('polygonPending()'),false);await fill('polygon-points','2.25,2.25\n3.5,2.25');const retainedEpoch=await evaluate('editorEpoch');await evaluate('qaRelease()');await until(()=>evaluate('!rightsBusy'));assert.equal(await evaluate('editorEpoch'),retainedEpoch);assert.equal(await evaluate('polygonPending()'),true);assert.equal(await evaluate('dirty'),true);await submit('editor');await until(()=>editorIdle());assert.ok((await evaluate('document.getElementById("notice").textContent')).includes('unfinished polygon'));await evaluate('window.fetch=qaFetch');await picture('polygon-pending-intent','polygon-controls');await reload(true);
 for(const row of rows)await review(row);rows=await fullRows(base);assert.ok(rows.every(r=>r.review==='human_reviewed'));const negative=rows.find(r=>!r.annotation.instances.length);await open(negative);assert.equal(await evaluate('targets.length'),0);
 await selectAll();const firstSet=await namedSet('Polygon QA exact reviewed revisions');await fill('release-format','image_detection_v1');await preview();assert.equal(await evaluate('releasePreview.eligible'),false);await fill('release-format','canonical_v1');await preview();assert.equal(await evaluate('releasePreview.eligible'),true);assert.ok((await evaluate('document.getElementById("release-preview").textContent')).includes('Polygon release: 6/100 records'));assert.equal(await evaluate('document.querySelectorAll("#release-preview img,#release-preview script").length'),0);
 const first=await freeze('first-polygons',rows);assert.equal(first.reader.polygon_instances,12);assert.equal(first.reader.positive_instances_with_empty_raster,3);assert.equal(first.reader.independent_authored_bitmap_checks,12);await picture('polygon-desktop-release','release-form');
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);await picture('polygon-narrow-release','release-preview');
 // The second owner's uncertain admission is recovered by saved-result lookup,
 // then a deliberate new import refuses that already-created identity/pixels.
 owner='second';await navigate(secondBase+'/workbench');stage='lost native acknowledgement';await evaluate("window.qaFetch=window.fetch;window.qaLost=true;window.fetch=async(input,options)=>{const response=await qaFetch(input,options);if(qaLost&&options?.method==='POST'&&String(input)==='/api/workbench/native-detection-import/row'){qaLost=false;await response.clone().json();throw Error('QA lost native acknowledgement');}return response;}");
 await importFile(first.raw);assert.equal(await evaluate('!!detectionPending'),true);assert.equal((await fullRows(secondBase)).length,1);await click('native-detection-check');await until(()=>evaluate('!detectionRunning&&!detectionPending'));assert.equal(await evaluate('detectionCounts.created'),1);await evaluate('window.fetch=qaFetch');await importFile(first.raw);assert.equal(await evaluate('detectionCounts.created'),5);assert.equal(await evaluate('detectionCounts.rejected'),1);
 let imported=await fullRows(secondBase);assert.equal(imported.length,6);assert.ok(imported.every(r=>r.review==='draft'&&r.provenance.rights==='unknown'));
 for(const row of imported){const acq=row.provenance.acquisition,up=acq.declared.upstream,before=rows.find(r=>r.id===up.record.id);assert.ok(before);assert.notEqual(row.id,before.id);assert.deepEqual(row.annotation,before.annotation);assert.equal(row.pixel_hash,before.pixel_hash);assert.equal(row.content_hash,before.content_hash);assert.equal(acq.archive_sha256,first.sha256);assert.deepEqual(up.category_table,first.reader.categories);const mapping=new Map(first.reader.categories.map(c=>[c.name,c.id]));assert.deepEqual(up.annotation_category_ids,before.annotation.instances.map(t=>mapping.get(t.label)));await open(row);assert.ok((await evaluate('document.getElementById("record-provenance").textContent')).includes(first.sha256));await save();assert.equal(await evaluate('current.review'),'draft');await reload(false);assert.deepEqual(await evaluate('current.annotation'),row.annotation);await fill('rights-note-value','Local QA rights correction; fixture only, no actual permission claim');await submit('rights-note-form');await until(()=>evaluate('!rightsBusy&&!rightsDirty'));assert.equal(await evaluate('current.provenance.rights'),'unknown');assert.equal(await evaluate('current.review'),'draft');if(row.annotation.instances.length&&!await evaluate('window.qaProvenanceCaptured===true')){await picture('polygon-native-provenance','record-provenance');await evaluate('window.qaProvenanceCaptured=true');}await review(row);}
 imported=await fullRows(secondBase);await selectAll();const secondSet=await namedSet('Imported polygons exact reviewed revisions'),second=await freeze('roundtrip-polygons',imported);assert.deepEqual(second.reader.categories,first.reader.categories);assert.equal(second.reader.independent_authored_bitmap_checks,12);
 const stale=imported.find(r=>r.annotation.instances.length);await open(stale);await evaluate('document.querySelector("#targets button").click()');await save();assert.equal(await evaluate('current.review'),'draft');assert.equal((await get(secondBase,'selections/'+secondSet.id)).current,false);await click('clear-selection');await click('load-selection');await until(()=>evaluate('!savedLoadBusy&&selected.size===6'));assert.deepEqual(await pairs(),secondSet.pairs);await preview();assert.equal(await evaluate('releasePreview.eligible'),false);assert.equal(await evaluate('document.getElementById("freeze-release").disabled'),true);await picture('polygon-stale-selection','release-preview');
 assert.deepEqual(Buffer.from(await(await fetch(first.url)).arrayBuffer()),first.raw);assert.deepEqual(Buffer.from(await(await fetch(second.url)).arrayBuffer()),second.raw);assert.equal((await get(base,'records/'+unrelated)).review,'draft');assert.deepEqual(errors,[]);
 const snapshot=JSON.parse(execFileSync(python,['-c','import json;from scripts.qualify_text_classification_local import source_snapshot;print(json.dumps(source_snapshot()))'],{cwd:root,encoding:'utf8'}));
 fs.writeFileSync(path.join(output,'session.json'),JSON.stringify({result:'PASS',candidate_head:snapshot.head,source_snapshot_sha256:snapshot.sha256,first:{url:first.url,archive:first.archive,download_guid:first.download_guid,sha256:first.sha256,fixed_set:firstSet,reader_sha256:sha(fs.readFileSync(path.join(output,'first-polygons-reader','polygon-reader-report.json')))},roundtrip:{url:second.url,archive:second.archive,download_guid:second.download_guid,sha256:second.sha256,fixed_set:secondSet,reader_sha256:sha(fs.readFileSync(path.join(output,'roundtrip-polygons-reader','polygon-reader-report.json')))},source_records:rows,imported_records:imported,rendered_polygon_capture_and_numeric_authorship:true,implicit_simple_ring_validation:true,explicit_negative_images:true,exact_native_fractional_coordinates:true,pending_vertices_save_refusal:true,explicit_task_switch_discard:true,primary_cancel_pointer_guards:true,busy_pointer_ignored:true,lost_annotation_ack_CAS_retry_no_duplicate_revision:true,held_repeated_save_and_later_rights_edit:true,held_rights_and_later_pending_geometry_retained:true,unchanged_and_numeric_entry_integral_float_signed_zero_primitive_proof:true,primitive_fixture_basis:'Controlled HTTP target seed and actual rendered numeric entry/Save/reopen/review; original12-instance authored reader fixture is restored afterward.',clean_primary_down_fences_older_open:true,second_owner_local_rights_draft_reload_review:true,chromium_rendered_link_downloads:true,download_events:downloads,separate_draft_reload_review:true,named_fixed_selection_reload_exact:true,lost_native_ack_saved_result_recovery:true,native_duplicate_retry_refused:true,native_new_ids_draft_unknown_rights_exact_evidence:true,whole_family_fixed_splits_retained:true,post_edit_saved_selection_stale_and_frozen_bytes_unchanged:true,actual_pinned_image_mask_readers:true,independent_authored_bitmap_checks:24,positive_empty_raster_instances:6,narrow_no_overflow:true,network:[...network.values()],network_scope:'Browser CDP local requests; fixture creation and Node verification are separate. Controlled fetch acknowledgement delays/drops preserve actual committed HTTP responses.',basis:'Retained authored tiny images, human-authored QA rings and simulated review clicks. Not a human-labelled benchmark or segmentation-quality proof.',model_instantiated:false,training:false,model_downloads:false,dataset_downloads:true,errors},null,2)+'\n');console.log('Polygon UI and actual file/reader roundtrip PASS: '+output);
})().catch(error=>{console.error('Stage:',stage,error);process.exitCode=1;}).finally(async()=>{if(ws)ws.close();for(const child of children)child.kill('SIGTERM');await Promise.all(children.map(child=>child.exitCode!==null?Promise.resolve():Promise.race([new Promise(resolve=>child.once('exit',resolve)),pause(1000)])));for(const child of children)if(child.exitCode===null)child.kill('SIGKILL');fs.rmSync(scratch,{recursive:true,force:true});});
