// Actual retained source metadata, simulated DOM/controller actions; real Chromium has its own gate.
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{spawnSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),code=`import sys,json,tempfile;sys.path.insert(0,'tests');from app import Dataset;from pathlib import Path;from test_sequences import body;from test_sequence_temporal_labels import annotation;import rheon_sequences as r\nwith tempfile.TemporaryDirectory() as tmp:\n d=Dataset(tmp);p=Path('tests/fixtures/rheon_actual_fee7b4a');row=r.admit(d.workbench,body((p/'run.json').read_bytes(),(p/'frames.jsonl').read_bytes()));print(json.dumps(dict(record=row,annotation=annotation(row))));d.close()`;
const result=spawnSync(process.env.PYTHON||'python3',['-c',code],{cwd:root,encoding:'utf8',timeout:30000});assert.equal(result.status,0,result.stderr);const fixture=JSON.parse(result.stdout);
const elements=new Map(),events={};let marks=0;
function node(tag='div'){return {tag,children:[],value:'',dataset:{},hidden:false,disabled:false,textContent:'',events:{},addEventListener(name,fn){this.events[name]=fn;},append(...nodes){this.children.push(...nodes);},replaceChildren(...nodes){this.children=nodes;},focus(){this.focused=true;},querySelectorAll(tag){return this.children.flatMap(child=>[...(child.tag===tag?[child]:[]),...child.querySelectorAll(tag)]);}};}
const $=id=>{if(!elements.has(id))elements.set(id,node());return elements.get(id);};
const context=vm.createContext({$,structuredClone,TextEncoder,JSON,Number,Object,Array,String,Error,Set,console,current:fixture.record,editorEpoch:0,markDirty:()=>{marks++;context.editorEpoch++;$('record-review').value='draft';},window:{addEventListener:(name,fn)=>events[name]=fn},document:{createElement:node}});
vm.runInContext(fs.readFileSync(path.join(root,'static/sequence-temporal-labels.js'),'utf8'),context);
const run=code=>vm.runInContext(code,context),clone=x=>structuredClone(x),show=(record=fixture.record)=>{context.current=record;$('task').value='sequence_transport';run('sequenceTemporalShown(current)');};
const click=id=>$(id).events.click(),fill=(name,value)=>{$('sequence-temporal-'+name).value=String(value);$('sequence-temporal-'+name).events.input();context.markDirty();};
const add=(label='Human A',first=0,last=8,note='Human rationale')=>{fill('label',label);fill('first',first);fill('last',last);fill('rationale',note);click('sequence-temporal-add');};
const ranges=()=>JSON.parse(run('JSON.stringify(sequenceTemporalRanges)')),payload=()=>JSON.parse(run('JSON.stringify(sequenceTemporalAnnotation(current,$("sequence-note").value))'));
const buttons=()=>$('sequence-temporal-list').querySelectorAll('button');
(()=>{
  show();$('sequence-note').value='Preserve separate note';assert.deepEqual(payload(),{note:'Preserve separate note'});
  $('record-review').value='human_reviewed';fill('label','Pending target');assert.throws(payload,/Add or Update/);click('sequence-temporal-cancel');assert.equal($('record-review').value,'draft');assert.deepEqual(payload(),{note:'Preserve separate note'});
  add('\u0085 Human A\u001c');assert.equal(ranges().length,1);assert.equal(ranges()[0].label,'Human A');assert.equal($('record-review').value,'draft');assert.equal($('sequence-note').value,'Preserve separate note');assert.equal(payload().temporal_labels.origin,'human_defined_annotation');
  const first=clone(ranges()[0]),epoch=run('sequenceTemporalEpoch');add(' Human A ',0,8,'Another reason');assert.equal(ranges().length,1);assert.match($('sequence-temporal-status').textContent,/Duplicate/);assert.equal(run('sequenceTemporalEpoch'),epoch);assert.equal(run('sequenceTemporalPending'),true);
  const removeOld=buttons()[1].onclick;removeOld();assert.equal(ranges().length,1);click('sequence-temporal-clear');assert.equal(ranges().length,1);assert.throws(payload,/pending/);click('sequence-temporal-cancel');assert.deepEqual(ranges(),[first]);
  buttons()[0].onclick();assert.equal(run('sequenceTemporalEditing'),0);assert.throws(payload,/pending/);fill('label','Human changed');fill('first',1);click('sequence-temporal-add');assert.equal(ranges()[0].label,'Human changed');assert.equal(ranges()[0].start_frame,1);
  add('Overlapping human B',1,1);assert.equal(ranges().length,2);buttons()[1].onclick();assert.equal(ranges().length,1);assert.equal(ranges()[0].label,'Overlapping human B');
  const saved={...clone(fixture.record),revision:2,annotation:payload()};show(saved);assert.deepEqual(ranges(),saved.annotation.temporal_labels.ranges);assert.equal(run('sequenceTemporalUsed'),true);
  $('sequence-note').value='Independent unsaved note';fill('label','BFCache pending');const staged=ranges(),pending=$('sequence-temporal-label').value,editorEpoch=context.editorEpoch;events.pagehide();assert.equal(context.editorEpoch,editorEpoch+1);assert.equal($('sequence-temporal-add').disabled,true);events.pageshow({persisted:true});assert.deepEqual(ranges(),staged);assert.equal($('sequence-temporal-label').value,pending);assert.equal(run('sequenceTemporalPending'),true);assert.equal($('sequence-note').value,'Independent unsaved note');assert.throws(payload,/pending/);click('sequence-temporal-cancel');
  const stale=buttons()[1].onclick;show({...clone(fixture.record),id:'b'.repeat(32)});stale();assert.equal(ranges().length,0);assert.match($('sequence-temporal-status').textContent,/different record/);
  show();add();for(const flag of ['rightsBusy','responseBusy','preferenceBusy','captionProposalBusy','textClassificationProposalBusy']){context[flag]=true;const before=ranges();click('sequence-temporal-clear');assert.deepEqual(ranges(),before);context[flag]=false;}
  $('editor').dataset.busy='true';click('sequence-temporal-clear');assert.equal(ranges().length,1);assert.doesNotThrow(payload,'Own Save may construct targets while editor busy');delete $('editor').dataset.busy;
  click('sequence-temporal-clear');assert.equal(ranges().length,0);assert.deepEqual(payload().temporal_labels.ranges,[]);assert.equal(payload().temporal_labels.origin,'human_defined_annotation');
  for(const [label,first,last,note,pattern] of [['X',8,0,'r',/first frame/],['X',0,9,'r',/frames 0/],['X',0,8,'',/nonempty/],['🦋'.repeat(81),0,8,'r',/80 code points/],['X',0,8,'\ud800',/Unicode/]]){add(label,first,last,note);assert.equal(ranges().length,0);assert.match($('sequence-temporal-status').textContent,pattern);click('sequence-temporal-cancel');}
  for(let i=0;i<16;i++)add('Human '+i,i%9,8);assert.equal(ranges().length,16);add('Too many');assert.equal(ranges().length,16);assert.match($('sequence-temporal-status').textContent,/16 temporal/);click('sequence-temporal-cancel');
  show();$('sequence-note').value='\x00'.repeat(4000);for(let i=0;i<16;i++)add('Label '+i,0,8,'\x00'.repeat(500));assert.ok(ranges().length<16);assert.match($('sequence-temporal-status').textContent,/64 KiB/);
  assert.equal(run('sequenceTemporalText("\\uFEFFX\\uFEFF","Label",80)'),'\uFEFFX\uFEFF');assert.equal(run('sequenceTemporalText(" 🦋 ","Label",80)'),'🦋');
  const malformed=clone(saved);malformed.annotation.temporal_labels.source.frames_sha256='0'.repeat(64);show(malformed);assert.throws(payload,/different record/);assert.match($('sequence-temporal-status').textContent,/malformed/);
  for(const value of [null,false,[]]){const bad=clone(saved);bad.annotation.temporal_labels=value;show(bad);assert.throws(payload,/different record/);assert.match($('sequence-temporal-status').textContent,/malformed/);}
  show(saved);events.pagehide();context.current={...saved,revision:3};events.pageshow({persisted:true});assert.equal($('sequence-temporal-add').disabled,true);assert.deepEqual(ranges(),saved.annotation.temporal_labels.ranges);assert.throws(payload,/different record/);
  show(context.current);assert.equal($('sequence-temporal-add').disabled,false);assert.doesNotThrow(payload,'Explicit new authoritative ShowRecord recovers mismatch');
  events.pagehide();show(context.current);assert.equal($('sequence-temporal-add').disabled,true,'Hidden-page ShowRecord cannot activate actions');events.pageshow({persisted:true});assert.equal($('sequence-temporal-add').disabled,false);
  show({id:'text',kind:'text',revision:1,source_revision:1});events.pagehide();events.pageshow({persisted:true});show(fixture.record);assert.equal($('sequence-temporal-add').disabled,false,'First sequence after restored nonsequence page recovers');
  console.log('Temporal target controller PASS: legacy/roundtrip, explicit Add/Edit/Remove/Clear/Cancel, pending save/destructive fencing, normalized duplicates, inclusive ranges, endpoint/source anchors, UTF8/Unicode/count bounds, busy/current/old-action guards and retained BFCache drafts. Human-only targets; no network or physical qualification.');
})();
