// Explicit synthetic v2 scheduling/receipt lifecycle; real HTTP/browser is separate.
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
function fixture(){
 const elements=new Map(),requests=[],events={},refreshes=[];
 const $=id=>{if(!elements.has(id))elements.set(id,{files:[],value:'',children:[],textContent:'',disabled:false,events:{},addEventListener(e,f){this.events[e]=f;},replaceChildren(){this.children=[];},append(x){this.children.push(x);}});return elements.get(id);};
 const context=vm.createContext({$,console,Uint8Array,atob,btoa,crypto:crypto.webcrypto,document:{createElement:()=>({textContent:''})},window:{addEventListener:(e,f)=>events[e]=f},notice:()=>{},refresh:async live=>refreshes.push(live()),sequenceFile:async(f,cap,name)=>{assert.equal(f.name,name);assert.ok(f.size<=cap);return Buffer.from(await f.arrayBuffer()).toString('base64');},fetch:(url,options)=>new Promise((resolve,reject)=>requests.push({url,options,resolve,reject}))});
 vm.runInContext(fs.readFileSync('static/sequence-batch.js','utf8'),context);
 const file=(label,name)=>{const raw=Buffer.from(label+' '+name);return {name,webkitRelativePath:'corpus/'+label+'/'+name,size:raw.length,arrayBuffer:async()=>Uint8Array.from(raw).buffer};};
 const item=(label,v2=true)=>['run.json','frames.jsonl',...(v2?['controls.json']:[])].map(n=>file(label,n));
 const submit=()=>$('sequence-batch-form').events.submit({preventDefault(){}});
 const respond=(q,value,ok=true,status=200)=>q.resolve({ok,status,json:async()=>value});
 const receipt=q=>{const b=JSON.parse(q.options.body),has=Object.hasOwn(b.files,'controls.json');const r={format:has?'tuldok_rheon_batch_v2':'tuldok_rheon_batch_v1',kind:'sequence',record_id:'a'.repeat(32),name:b.name};for(const k of ['request_id','batch_name','item_name','item_index'])r[k]=b[k];for(const [n,key] of [['run.json','run_sha256'],['frames.jsonl','frames_sha256'],['controls.json','controls_sha256']])if(b.files[n])r[key]=crypto.createHash('sha256').update(Buffer.from(b.files[n],'base64')).digest('hex');if(has)r.sequence_version=2;return r;};
 return {$,requests,events,refreshes,context,item,submit,respond,receipt};
}
async function until(fn){const deadline=Date.now()+2000;while(Date.now()<deadline){if(fn())return;await new Promise(r=>setTimeout(r,5));}throw Error('Bounded controller await timed out');}
(async()=>{
 let f=fixture();f.$('sequence-batch-folder').files=[...f.item('a-v1',false),...f.item('b-v2')];let p=f.submit();await until(()=>f.requests.length===1);let q=f.requests[0];assert.equal(f.receipt(q).format,'tuldok_rheon_batch_v1');f.respond(q,f.receipt(q));await until(()=>f.requests.length===2);q=f.requests[1];assert.equal(f.receipt(q).format,'tuldok_rheon_batch_v2');assert.equal(Object.keys(JSON.parse(q.options.body).files).length,3);f.respond(q,f.receipt(q));await p;assert.match(f.$('sequence-batch-status').textContent,/2 created, 0 rejected/);
 f=fixture();const ninetySix=Array.from({length:32},(_,i)=>f.item('run'+i)).flat();assert.equal(vm.runInContext('sequenceBatchPairs',f.context)(ninetySix).length,32);assert.throws(()=>vm.runInContext('sequenceBatchPairs',f.context)([...ninetySix,...f.item('extra')]));assert.throws(()=>vm.runInContext('sequenceBatchPairs',f.context)([...f.item('r'),f.item('r')[2]]));const bad=f.item('r');bad[2].size=65537;assert.throws(()=>vm.runInContext('sequenceBatchPairs',f.context)(bad));const many=Array.from({length:21},(_,i)=>f.item('r'+i));for(const row of many)row[1].size=2097152;assert.throws(()=>vm.runInContext('sequenceBatchPairs',f.context)(many.flat()));
 for(const departed of [false,true]){
  f=fixture();const files=f.item('a-v2');let finish;files[2].arrayBuffer=()=>new Promise(r=>finish=r);f.$('sequence-batch-folder').files=[...files,...f.item('z-later')];f.$('sequence-batch-group').value='old';p=f.submit();await until(()=>finish);f.$('sequence-batch-folder').files=[];f.$('sequence-batch-group').value='new';if(departed)f.events.pagehide();else f.$('sequence-batch-stop').events.click();finish(Uint8Array.from(Buffer.from('control')).buffer);await p;assert.equal(f.requests.length,0);
 }
 for(const departed of [false,true]){
  f=fixture();let finishDigest,count=0;const original=crypto.webcrypto.subtle.digest.bind(crypto.webcrypto.subtle);
  f.context.crypto={randomUUID:crypto.randomUUID,subtle:{digest:async(...args)=>{if(++count===3)await new Promise(r=>finishDigest=r);return original(...args);}}};f.$('sequence-batch-folder').files=f.item('v2');p=f.submit();await until(()=>finishDigest);if(departed)f.events.pagehide();else f.$('sequence-batch-stop').events.click();finishDigest();await p;assert.equal(f.requests.length,0);
 }
 f=fixture();const snapshot=f.item('v2');let finishControl;snapshot[2].arrayBuffer=()=>new Promise(r=>finishControl=r);f.$('sequence-batch-folder').files=snapshot;f.$('sequence-batch-group').value='old-group';f.$('sequence-batch-rights').value='old-rights';p=f.submit();await until(()=>finishControl);f.$('sequence-batch-folder').files=f.item('replacement');f.$('sequence-batch-group').value='new-group';f.$('sequence-batch-rights').value='new-rights';finishControl(Uint8Array.from(Buffer.from('v2 controls.json')).buffer);await until(()=>f.requests.length===1);q=f.requests[0];const snapBody=JSON.parse(q.options.body);assert.equal(snapBody.groups[0],'old-group');assert.equal(snapBody.rights,'old-rights');assert.equal(snapBody.item_name,'v2');assert.equal(Buffer.from(snapBody.files['controls.json'],'base64').toString(),'v2 controls.json');f.respond(q,f.receipt(q));await p;
 for(const mutate of [r=>r.sequence_version=true,r=>r.sequence_version='2',r=>r.controls_sha256='0'.repeat(64),r=>r.format='tuldok_rheon_batch_v1']){
  f=fixture();f.$('sequence-batch-folder').files=[...f.item('v2'),...f.item('z-later')];p=f.submit();await until(()=>f.requests.length===1);q=f.requests[0];const bad=f.receipt(q);mutate(bad);f.respond(q,bad);await p;assert.equal(f.requests.length,1);assert.match(f.$('sequence-batch-status').textContent,/1 uncertain/);const check=f.$('sequence-batch-check').events.click();await until(()=>f.requests.length===2);const wrong={found:true,...f.receipt(q),sequence_version:1};f.respond(f.requests[1],wrong);await check;assert.ok(vm.runInContext('sequenceBatchPending',f.context));assert.equal(f.requests.filter(r=>r.options).length,1);
 }
 f=fixture();f.$('sequence-batch-folder').files=f.item('v1',false);p=f.submit();await until(()=>f.requests.length===1);q=f.requests[0];f.respond(q,{...f.receipt(q),controls_sha256:'0'.repeat(64)});await p;assert.match(f.$('sequence-batch-status').textContent,/1 uncertain/);
 f=fixture();f.$('sequence-batch-folder').files=f.item('v2');p=f.submit();await until(()=>f.requests.length===1);q=f.requests[0];let finishJson;q.resolve({ok:true,status:200,json:()=>new Promise(r=>finishJson=r)});await until(()=>finishJson);f.events.pagehide();finishJson(f.receipt(q));await p;assert.ok(vm.runInContext('sequenceBatchPending',f.context));assert.equal(f.refreshes.length,0);
 console.log('Synthetic mixed folder controller PASS:96 files/32 trajectories/40MiB, mixed receipts, strict v1/v2 control proof, control read/digest Stop/departure, late JSON, saved-result mismatch and no replay.');
})().catch(e=>{console.error(e);process.exitCode=1;});
